### ISSUE TITLE
Searches by community area do not deliver expected results

### ISSUE THREAD

**Issue by danxoneil** [smartchicago/chicago-early-learning#384]
I've heard a number of reports from people working in the early childhood learning space who search for particular locations by searching the community area in which it is located.

I think the basic fix is that the community area is drawn too tightly. Fix would be to add a buffer (one mile?) to display.

Example:

El Valor Centro Infantil— does not show up in search for either “Humboldt Park” or “West Town”

**Comment by smarziano** [comment]
@danxoneil -- Has this been fixed already? El Valor Centro Infantil shows up in my search of "West Town"

**Comment by smarziano** [comment]
Closing this issue because I am unable to replicate this problem.
