### ISSUE TITLE
Account for alternative names for center locations

### ISSUE THREAD

**Issue by danxoneil** [smartchicago/chicago-early-learning#385]
There are lots of locations that have alternate / colloquial names. We'd like to have a system that accounts for that, so that when a user searches for an expected location, they are able to find it, even if the official name is something else.

**Comment by smarziano** [comment]
Here is a document provided by @shua123 which gives alternative names for all CPS school locations:
https://docs.google.com/spreadsheets/d/1J7Ao9yqBQV5K_W6tcY-iin99OTkjNHw7wPvBCprdIqo/edit#gid=1093867311

This should be incorporated to give users multiple options to search for CPS locations on the Chicago Early Learning portal.

**Comment by smarziano** [comment]
A couple of tasks/considerations related to this issue: 
- [ ] Add CPS alternative names for schools: short name, title, and long name
- [ ] Add a way for admins to put in a short name or edit alternative names in the admin tool
- [ ] Account for users searching for umbrella organization name vs. specific location name. An example of this is Henry Booth House. When searching for Henry Booth House only one location shows up although there are multiple locations under this organization. Here is a screenshot:
<img width="622" alt="screen shot 2015-11-02 at 8 16 15 pm" src="https://cloud.githubusercontent.com/assets/5550969/10899877/cbc75952-819e-11e5-8a66-ea5d24b0d053.png">
- [ ] Create a system that would allow for user to search for umbrella organization or more specific information. Here is another example: "Centers for New Horizons-Altgeld Early Learning Center" might be searched for as Centers for New Horizons or by "Altgeld" or a mix of both.
- [ ] Determine the value in showing all of the locations on the map if an umbrella organization is searched. This is something I want to think more on to see if it makes sense to show all of the (for example,) Centers for New Horzions locations on one view. This functionality would also be helpful in when thinking about showing home visiting programs (such as #477).

**Comment by smarziano** [comment]
These tasks will be completed with a better location autocomplete search (see #524). The tasks above are addressed with a more flexible search. We will get better search results by adding all of the long names for CPS locations and being consistent in naming conventions of locations that fall under umbrella organizations (see #519).

Once locations are added to autocomplete dropdown we can close this issue.

**Comment by smarziano** [comment]
Added and live on production. Closing this issue. Here is an example:

Searching the short name ("Hayt") or long name ("Stephen K Hayt Elementary School") gets to the same result:
<img width="1278" alt="screen shot 2015-12-28 at 3 35 17 pm" src="https://cloud.githubusercontent.com/assets/5550969/12025870/aea628d4-ad78-11e5-9d63-b4e264c509e1.png">
