### ISSUE TITLE
Create a map key

### ISSUE THREAD

**Issue by Ghlyon** [smartchicago/chicago-early-learning#395]
Create a key for the map. We need to explain the following icons: blue, blue with stars, green. Currently explanations are available by hovering over the icon in the "More Information" box. This is insufficient. We need explanations in a key. 

We also need to define "Accepts CCAP" in the Search box.

**Comment by smarziano** [comment]
Closing this issue. We helped provide more information to users, by adding important details of each location under the name of each location and when clicking on the map location mark.

![screen shot 2015-03-06 at 6 11 24 pm](https://cloud.githubusercontent.com/assets/5550969/6538777/47f8d73e-c42c-11e4-9a32-6a3e841b8303.png)
