### ISSUE TITLE
reformat comparison output

### ISSUE THREAD

**Issue by Ghlyon** [smartchicago/chicago-early-learning#400]
Searches are not always producing correct "finds." Example: 
Click Search. Click "Ages 0-3." 
Choose "Archer Heights (1)." 
Choose "Explore"-> 7 sites pop up. 
Of these 4 do not fit my search filter (Lizney Learning is 2-6; Little Angels is 2-5; Kiddy Care is 1-2, Kiddy Garden is 2-5. 

When you pick any specific option to look at in detail you can't go back to the original search output.

**Comment by smarziano** [comment]
Closing this issue. I replicated the search above and all of the results matched the criteria "Ages 0-3."
