### ISSUE TITLE
Create a "Contact Me" Form to kick off communication between users and locations

### ISSUE THREAD

**Issue by Ghlyon** [smartchicago/chicago-early-learning#408]
The "Contact me" process starts at the the comparison function. At the moment of comparison, we will allow parents/caregivers to not just compare locations, but to kick off the communication through a "Contact Me" function. Here’s a look at the new user flow we will build in this project:
•	User selects as many locations as they want to compare.
•	User is offered additional options with compared locations, including "Contact Me"
•	User selects "Contact Me" for all or a subset of this list to begin the communication process with chosen locations.
•	User completes a form that takes basic information (name, address, phone number 1, phone number 2, number of children and ages of each child). You can view a draft of this form here: https://smartchicago2012.wufoo.com/forms/contact-me/
•	System sends this form to each of the email account(s) associated with the chosen locations. 
•	User immediately receives a confirmation email generated by Smart Chicago that summarizes a list of the locations, location information (location name, address, website and phone number) and the date the request was submitted.The confrmation email will include a statement to help manage expectations about when they can expect to be contacted such as "Thank you. You have requested that the following locations contact you. You should expect to hear from these locations within ???? days. You may also follow up directly with locations using the contact information provided."
•    "Contact me" form fields will feed into a CSV-friendly data system updated daily that can be sorted and managed by CPS and DSFF administrators.

In order for this system to function:
•	CPS and DFSS will need to update each location with an appropriate email address. In some instances for CPS there will be a single email address for a centralized administration; for many instances for DFSS specific locations will serve as email "hubs" for multiple programs. These designations will be administered by CPS and DFSS using the existing admin tool.
•	This contact info will be stored on the Chicago Early Learning website database under a secure system.

**Comment by smarziano** [comment]
This feature has now been deployed. We will continue to work on ways to drive more users to compare and contact locations.

Closing this issue but related to future work is #475 and #476
