### ISSUE TITLE
"How do I enroll my child?"

### ISSUE THREAD

**Issue by Ghlyon** [smartchicago/chicago-early-learning#411]
We've been asked to enhance the FAQ section on the portal with enrollment information, drawing upon the scripts used by the Ready to Learn! hotline for content, including linking to the CPS and DFSS pages that provide information on their relevant programs: http://www.cps.edu/schools/earlychildhood/pages/earlychildhood.aspx and http://www.cityofchicago.org/city/en/depts/fss/provdrs/child/svcs/preschool_programs.html.

Need to get appropriate language from DFSS and CPS respectively. Likely we will list options for enrollment choices. One key issue is that each site needs to be associated with a phone number of where the parent should call for information.

Enabling people to download outreach materials is a second issue:
This page could also have links to PDF copies of Ready to Learn outreach materials: “Just need some flyers? Click here to download and print Ready to Learn! outreach materials. Hang these signs in your windows or hand them out. Thank you for your help getting Chicago Ready to Learn!”

Where does this information live on the site? What materials are available? Who puts materials on the site? One possibility is that this lives as an admin function and sites upload their own materials for their own sites; another is that this is an admin function for DFSS and CPS respectively but that space is allotted on the general site or on an existing or new page. see http://chicagoearlylearning.org/about @danxoneil

**Comment by smarziano** [comment]
Closing this issue because we have new specific tasks to give users more information regarding the enrollment process:
#484 - Add new page with enrollment video
#486 - Add enrollment process information on detail pages
#485 - Create specific URL to share enrollment sites
