### ISSUE TITLE
Spanish translation for FAQs and new features

### ISSUE THREAD

**Issue by Ghlyon** [smartchicago/chicago-early-learning#424]
Spanish language translations for the FAQs associated with #428 #427 
 #426 #421  #420  #417 #411, translation for site location descriptions and translation for new and updated content (#404 #403 and #395, possibly also #408) will primarily be handled using the updated admin tool.  We have created a google spreasheet to manage translation for any content that needs to be translated that cannot be managed using the admin tool.

**Comment by smarziano** [comment]
@danxoneil or @srobbin Do we have access to this google spreadsheet?

**Comment by srobbin** [comment]
@smarziano: I just sent you both an invite to edit the spreadsheet.

**Comment by smarziano** [comment]
Thanks, @srobbin!

Closing this issue since all of the content that we need to translate has been translated. In addition, we now have access to the spreadsheet to make any future changes.
