### ISSUE TITLE
Update FAQ "Will I have to pay anything to enroll my child" with calculators

### ISSUE THREAD

**Issue by Ghlyon** [smartchicago/chicago-early-learning#426]
Calculators will be built into the existing FAQ "Will I have to pay anything to enroll my child?" http://chicagoearlylearning.org/faq#topic2-1. We need language and the exact links for the calculators. CPS and DFSS will maintain their own caculators on their own pages and the FAQ will link to these. For example http://www.cps.edu/Schools/EarlyChildhood/Pages/EarlyChildhoodCalculator.aspx

**Comment by smarziano** [comment]
This is an outdated task, and we are expecting to receive new FAQs content for the Phase 1 launch (https://github.com/smartchicago/chicago-early-learning/issues?milestone=18). Closing this issue.
