### ISSUE TITLE
Update Internal pages layout

### ISSUE THREAD

**Issue by Ghlyon** [smartchicago/chicago-early-learning#436]
We would like to update the layout of internal pages to better showcase new and enhanced features. Here are the key differences in the updated internal page:
1) Move the address/search box out of the header into the search section
2) Highlight program provider and availability
3) Give users an option to see and use "more" search filters 
4) Update the header to include the Chicago Ready to Learn Hotline #412  and, if there's room, also the "Keep in Touch" option.
5) we also want to add a key to the map and build in other map-related features. #395 #396 #397 
Here's a sketch of the direction we'd like to go:
![internal page draft-2014-7-1](https://cloud.githubusercontent.com/assets/7240828/3448246/efaaad84-0156-11e4-9733-b23e13e16cf8.JPG)

**Comment by smarziano** [comment]
@srobbin Based on changes on the staging server: 
http://23.23.105.185/search/?lat=41.870583462266836&lng=-87.62008666992188&zoom=10

Here are recommendations for changes:
- Search filters that relate to each other should be next to each other (prefer 1 over the other). For example:

Full Day           
Part Day  

- The left-hand column with search and filtering options should be tighter to create a larger view of the map. 

- When Program information = None, it should be hidden. An example is below of how a location is represented when "None" is in the Program Information field.

![screen shot 2015-02-16 at 8 13 53 am](https://cloud.githubusercontent.com/assets/5550969/6215838/de07bac2-b5c9-11e4-8b57-06ade4d0b634.png)

**Comment by smarziano** [comment]
In addition, it is not clear that users will be able to contact different locations. We need to call out this feature in some way to show that users should favorite and then contact locations from this internal search page.

**Comment by srobbin** [comment]
The "None"s are now hidden. And unfortunately, I'm going to have to defer on the filter order, and column widths right now. The ability to contact should be addressed in #408.

**Comment by smarziano** [comment]
Closing this issue since we made a specific issue for reorganizing filters. See issue #536
