### ISSUE TITLE
Create a Print Option for Select or Favorite Locations

### ISSUE THREAD

**Issue by Ghlyon** [smartchicago/chicago-early-learning#455]
Create "Print" as an option along with Share (in addition to email, tweet, etc) when a user is reviewing single or compared locations. This issue relates to #459 
![screen shot 2014-08-13 at 1 31 33 pm](https://cloud.githubusercontent.com/assets/7240828/3910479/4068ef14-2318-11e4-8b98-3be05744b33f.png)

![screen shot 2014-08-13 at 1 31 45 pm](https://cloud.githubusercontent.com/assets/7240828/3910475/39f51a36-2318-11e4-8229-c3d1721e4c44.png)

**Comment by danxoneil** [comment]
Closing. We will rely on the regular print commands in OS. The permalink itself is the thing itself.
