### ISSUE TITLE
Add phone # & website information in text feature

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#463]
From a meeting with Chicago Early Learning partners, we heard that the phone number and website for the program should be included in the text feature. 

This would be match the details page on the website: http://chicagoearlylearning.org/location/765/mccutcheon/ 

Here is an example of the information currently produced for a location via text.
![img_2798](https://cloud.githubusercontent.com/assets/5550969/5961025/40b457c2-a79f-11e4-9458-f8eb070d22d4.PNG)

**Comment by srobbin** [comment]
This is live now. Give it a try, and let me know what you think.

Added in commit 38e23a5793399276836431c9de545b6d42d6a2ea.

**Comment by smarziano** [comment]
This a great. (example below to confirm) Closing this issue.

![img_2904](https://cloud.githubusercontent.com/assets/5550969/6322414/b35bd30c-bad9-11e4-92a3-16f02c75bacc.PNG)
