### ISSUE TITLE
Add better instructions in text feature

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#464]
From a meeting with Chicago Early Learning partners, we heard that the text feature does not give clear instructions that a user has to text back with a number to get more information about that program.

We would like to repeat the instructions at the end of the text messages since it info might be received over multiple text messages. The copy should read something like "Reply with the number of the program to learn more about that location." and be located at the end of the messages.

**Comment by srobbin** [comment]
Added in commit cca03dac8f1f65f34105ff19f47a194e66dad0c9, and pushed live.

**Comment by smarziano** [comment]
This looks good! (example below) Closing this issue.

![img_2903](https://cloud.githubusercontent.com/assets/5550969/6322404/50499b32-bad9-11e4-8035-6bf53b5a3597.PNG)
