### ISSUE TITLE
Spanish navbar options shows up in Chicago: Ready to Learn! banner

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#465]
When switching from English to Spanish, the nav bar options show up in the "For application information please call the Chicago: Ready to Learn! Hotline at (312) 229-1690" banner.

"Para información acerca de la aplicación, por favor llamar al Chicago: Listo para Aprender! Al (312) 229-1690, línea de acceso directo." should be separate banner, whereas the navbar options in Spanish should be:
Texto Para Info
Información acerca de nosotros
Preguntas frecuentes
Idioma 
Mantengase En Contacto

![screen shot 2015-02-10 at 9 09 22 pm](https://cloud.githubusercontent.com/assets/5550969/6141360/e98b7956-b169-11e4-9f4d-6d053843dc39.png)

**Comment by srobbin** [comment]
There are two things happening here. The newish "Keep in Touch" menu item has made the menu too long for the current design. If you look at the English version, and narrow your browser window, you'll notice the same thing happens, although at a much narrower point. Which leads to the second issue: the Spanish translation is longer text than the English.

I'm not sure what we should do here. Maybe just jump to the icons-only at a wider window?

**Comment by smarziano** [comment]
@srobbin Can we change the language in the navbar solely for the Spanish version? 
My recommendation might be to say "Sobre Nosotros" instead of "Información acerca de nosotros". This means About Us.

**Comment by srobbin** [comment]
Of course. I just updated the staging server:

http://23.23.105.185/

**Comment by smarziano** [comment]
@srobbin This looks great. Push to live server whenever you are ready.

For reference, did that small change in language fix the banner or did you have to make another change?

**Comment by smarziano** [comment]
Looking at the internal page, we are coming across the same problem but it is not blocking any text. It does block the zoom in feature on the map. 

There is probably a better way to say "Keep in Touch" in Spanish that is shorter. I will check on this. Another option might be to use the "mail icon."

![screen shot 2015-02-16 at 11 25 30 am](https://cloud.githubusercontent.com/assets/5550969/6216454/119ed93c-b5d0-11e4-8423-d316900c72b9.png)

**Comment by srobbin** [comment]
I've tried a couple of things, like removing "Chicago Early Learning" from the logo, and reducing the "Keep in Touch" to an icon, but nothing works. I think the header just needs to be redesigned at the HTML/CSS level.

**Comment by smarziano** [comment]
When we do re-work this, we need to change the language of "Texto para info." We should say something like "Envié un mensaje de texto."

**Comment by smarziano** [comment]
Closing this issue since it seems fixed once navbar was updated through work on issue #390.
