### ISSUE TITLE
Create announcement for open enrollment period

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#467]
Our partners would like to see an announcement about open enrollment on the home page. The text is as follows:
"Ready, Set...Enroll!
March 2 - May 1, 2015
Chicago Public Schools is now accepting preschool applications (click here)
Head Start, Early Head Start enrollment is yearlong."
"Click here" would link to cps.edu/readytolearn

This is a mockup of what they imagined it would look like as a splash page:
https://www.dropbox.com/s/uth0p8rmqulym3w/Portal%20Mock%20022415.pptx?dl=0

@srobbin Let me know how you think we can incorporate this. The current view in the mockup is widened so we need to think about how we can include this without making the homepage too busy and still easy to be used on a wide range of devices.

**Comment by smarziano** [comment]
@srobbin Here is the Spanish translation for the splash page, directly from CPS:

"Las Escuelas Públicas de Chicago estan aceptando aplicaciónes para preescolar ahora. Haga clic aquí

La inscripción para Headstart, Early Head Start es durante todo el año."

"Haga clic aquí" should be hyperlinked to cps.edu/readytolearn

**Comment by srobbin** [comment]
This is live on the site now.

![screen shot 2015-03-17 at 6 07 55 pm](https://cloud.githubusercontent.com/assets/44719/6699492/9289fba0-ccd0-11e4-9c42-2a4a1b3019bf.png)

**Comment by smarziano** [comment]
@srobbin On the English splash page, we have been asked to change "yearlong" to "year long"

Thank you!

**Comment by srobbin** [comment]
Done.

![screen shot 2015-03-18 at 10 20 15 am](https://cloud.githubusercontent.com/assets/44719/6712009/65275a26-cd58-11e4-8208-64705b11c329.png)

**Comment by smarziano** [comment]
Confirmed that all necessary changes have been made. Closing this issue.
