### ISSUE TITLE
Add better information about CPS application sites to map

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#471]
During enrollment periods, we want to be able to add information about application sites to our map function. Users will then be able to search and find an application site near them.
The list of current CPS-based enrollment sites are here:
http://www.cps.edu/Schools/EarlyChildhood/Documents/RTLflyer_English.pdf

This should be embedded into the admin function so that our partners can update the information as necessary with name, address, hours, and phone. The icon should appear on the map with a special designation of application site and the dates of enrollment period.

**Comment by smarziano** [comment]
For CPS-based spot placement that begins on July 6, 2015, we would like to display the three central locations (here is the info: http://cps.edu/SiteCollectionDocuments/FinalSpotPlacementFlyer.pdf).

The locations are as follows:
- Loop, 42 W. Madison St., 9:00 AM - 5:00 PM
- Colman, 4655 S. Dearborn St., 9:00 AM - 5:00 PM
- Hall Mall, 4638 W. Diversey Ave., 8:00 AM - 5:00 PM
Extended hours: all locations will be open on Wednesdays until 7:00 PM for July and August.

This will be under a new type of location: Application Site
Field types: Name, address, hours and description
Admins would have the ability to add, delete, and then turn on/off application sites for enrollment.

We would need to create a new icon for these sites that would be also be displayed on the map.

**Comment by frankwiles** [comment]
I believe we discussed this on our last call, but is it ok to just have a "Type" select box to the existing locations data to use for this with a new icon? Basically these would have all of the same fields as existing Locations, just show up with the other icon and obviously different data.

**Comment by smarziano** [comment]
Right, we did discuss that! So for the locations I provided above, these are administrative offices and do not have Early Learning programs. However, the other application sites (which will not be open during Spot Placement) can also be locations that have early learning programs.

That being said, I think it'll be easier to proceed as you described where we add it as a location and have an opportunity to check/uncheck a box to show if the site is an application site. 

The administrative offices that we add as application sites now should disappear on the map after enrollment is over and after an admin unchecks the "Application Site" box.

**Comment by frankwiles** [comment]
Any ETA on the icon we're going to use?

**Comment by smarziano** [comment]
I will be finishing the icons tonight. I am updating all the icons for these reasons:
- consistency with the new icon
- more distinguishable between CPS-based and community-based locations

**Comment by frankwiles** [comment]
Awesome.  I'll do my best to get the changes up as soon as I can.  Schedule wise just so you know we have [DjangoBirthday](https://djangobirthday.com) this weekend and the later part of next week I'm in Philly giving some talks at [Wharton Web Conference](https://www.sas.upenn.edu/wwc/) so availability is going to be a little tight the next week or so.

**Comment by frankwiles** [comment]
Ok this is up on staging now, example: http://23.23.105.185/search/?lat=41.87889176738813&lng=-87.62515068054199&zoom=14

It's named 'Loop' in the admin if you want to edit the info.

**Comment by smarziano** [comment]
Can we change the aspect ratio of these icons? They look the width are being squished. If this is a matter of getting different sized icons, let me know and I can do that for you. 

<img width="564" alt="screen shot 2015-07-23 at 7 00 31 am" src="https://cloud.githubusercontent.com/assets/5550969/8856760/8db32f92-3108-11e5-8140-a6e16ffabf18.png">

In addition, can we hide some of the fields that do not relate to the application site? These locations need to be handled differently from early learning program sites:
- On detail pages, we do not need to show accreditation, ages served, duration, weekday availability, program information, or quality rating.
- When a user clicks on the application site icon, they should show hour information or and a description that they are an application site.

**Comment by frankwiles** [comment]
Finished up these changes this morning, just had the chance to push them to staging.

**Comment by smarziano** [comment]
I am closing this issue because it is irrelevant to the City's current Early Learning enrollment process with the universal application process. There are no longer specific CPS application sites but instead Family Resource Centers (https://chicagoearlylearning.org/faq#list-of-family-resource-centers) to help parents enroll in either community-based or CPS-based programs.
