### ISSUE TITLE
Add map key to map to define colors/icons used

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#474]
We continue to hear from our partners that there is uncertainty from parents about the colors used on the map page for CPS-based (green), and community-based (blue) organizations. We also want to clarify that yellow icons are locations added to the Compare & Contact list.

Currently the only way a parent can find the difference is through a hover action over the symbol on the list. 
![screen shot 2015-04-16 at 3 42 35 pm](https://cloud.githubusercontent.com/assets/5550969/7190922/3d172d46-e44f-11e4-90d3-e369861f78dc.png)

Moving forward, we would like to add a map key that explains the difference between the different icons used on the map. This will also be incorporated into the mobile view.

**Comment by frankwiles** [comment]
This is up on staging now.  I shoved it next to the 'Reset Search' and 'More Filters' options as that seemed the best place to put it.  Let me know if you want something different.

**Comment by smarziano** [comment]
Here are my thoughts:
- Instead of "School" and "Center" we should say "CPS-based" or "Community-based" to match the filter options. This should be the same when hovering as seen in the screenshot above.
- In addition, we have a third map icon, "Accredited Center" that should be added
- As for location, I think it's great to use that space, but I would like to move it closer to the right-hand side where the map is. This will look better when we add a third icon.

_Side-note:_ When we do our CUTGroup user testing, I am interested to learn if we need to distinguish the pinpoints even more (maybe by shape), and if we will need to provide additional information about "Accredited Center" that reflects our FAQ page

**Comment by frankwiles** [comment]
Based on the icons in the system there is 'school', 'school-accredited', 'center', and 'center-accredited'... plus the 'starred/favorite' equivalents.  I don't think I can make all 4 icons show up in the key easily in a useable way without pushing down the key to be below the filter buttons.  That ok?

**Comment by smarziano** [comment]
@frankwiles I made a (ugly) draft. What do you think about this setup? The icons should not have backgrounds, and font can be changed and adjusted, of course. 

![map-key-draft](https://cloud.githubusercontent.com/assets/5550969/7736564/3a2ddd3e-ff0a-11e4-8a32-cdbadb074119.jpg)

**Comment by frankwiles** [comment]
Ok I have the naming conventions fixed and up on staging, sadly took me forever to figure out the issue was in the translation files due to how Vagrant is setup.  I'll see if I can finish up the key based on your mockup today as well.

**Comment by frankwiles** [comment]
Ok gave it another stab, it's up on staging but here is a screenshot of how it looks.  Fitting it right of the buttons got too crowded to make it legible and keep that sort of overall structure. 

![screen shot 2015-05-22 at 10 10 48 am](https://cloud.githubusercontent.com/assets/144159/7773556/dba8b7fe-006a-11e5-8e47-5230c33f027f.png)

**Comment by smarziano** [comment]
I think this structure is taking up too much space on the left-hand column. Can we make it smaller?
Another suggestion is to put the "More Filters" button above the "Reset Search" button to give more space horizontally.

Also, changes in language:
- Yellow icon: "Compare & Contact Locations"
- Star: "Nationally Accredited"

I exported the locations, and none of the CPS-based locations have national accreditation. Therefore, I think we can use the blue with star symbol.

**Comment by frankwiles** [comment]
Ok how about this? It's live on staging. 
![screen shot 2015-05-22 at 11 56 28 am](https://cloud.githubusercontent.com/assets/144159/7775544/9fe41e66-0079-11e5-8bfc-feba8c9b0e7d.png)

**Comment by smarziano** [comment]
Last change (I should have been clearer in my last comment), the blue star should be this icon:

![screen shot 2015-05-26 at 8 51 10 am](https://cloud.githubusercontent.com/assets/5550969/7813945/619ee114-0384-11e5-82c4-6b00aa17fc9e.png)

The organization looks much better. Thank you!

**Comment by frankwiles** [comment]
Ok should be all fixed on staging now!

**Comment by smarziano** [comment]
@frankwiles This looks good! Please close this issue once pushed live. Thank you.

**Comment by frankwiles** [comment]
Ok this, including all of the Django upgrades are live on production now.
