### ISSUE TITLE
Create way for Compare & Contact data to be exported to CSV through admin tool

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#475]
As part of the Compare & Contact feature (#408), we want to add a way for admins to be able to filter and export data about the users who are using the Compare and Contact feature to contact their locations.

**Comment by frankwiles** [comment]
Sorry bit confused on the actual needs on this one.  What aspects of the Contact are you wanting to filter on? For example I assume a 'all contacts on a per location basis' makes sense, but not sure what else you might be envisioning with this.

**Comment by smarziano** [comment]
The first priority is to be able to export all of the Compare & Contact information similar to the function on this Locations page: http://chicagoearlylearning.org/admin/portal/location/

Then, it would be good to be able to filter and export only certain entries either by site name, person, or type (CPS-based vs. community-based). This is similar to issue #478.

**Comment by frankwiles** [comment]
Simple full export is live on staging now FYI.

**Comment by smarziano** [comment]
@frankwiles This has been pushed live. I want to see about making a few changes. When a user exports Compare & Contact info, can you reformat the output? This is what I am looking to have changed:
- *Main priority* Add contacted location name & Compare & Contact email for that location
- Can the "child_" and "phone" fields be formatted as text? Ages 3-5 becomes 5-Mar and phone numbers become formulas when exported.
- Can we have the field columns in a different order? They are currently jumbled up, meaning that address information is not in order, and the "child_" fields are also not in order.

**Comment by smarziano** [comment]
I am closing this issue because this becomes irrelevant with issue #558.
