### ISSUE TITLE
Remove Enrollment Announcement Splash Page on Mobile

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#480]
CPS enrollment announcement can still be found on mobile versions. Since this enrollment period is over, we need to remove this splash page.  

![img_3153](https://cloud.githubusercontent.com/assets/5550969/7708708/11eb4156-fe1d-11e4-9930-1017aca75833.PNG)

**Comment by frankwiles** [comment]
Whoops apparently I missed that there was a separate mobile only block of markup for that.  Removed and live on production.
