### ISSUE TITLE
Provide Favorites/Starred URL with specific locations ID numbers

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#483]
We would like the ability to create favorites/starred URL that have location IDs. Currently when a user selects locations and then clicks "Compare & Contact" the URL is: 
http://chicagoearlylearning.org/starred/

We would like the ability to add locations IDs to the URL, such as:
http://chicagoearlylearning.org/favorites/896/
or
http://chicagoearlylearning.org/starred/896/

The goal is to compare multiple locations within one URL. 

This relates to our issue #481 and the ability to allow our partners to link to specific locations on the Compare & Contact view.

**Comment by frankwiles** [comment]
Ok I'm not understanding this one.  /starred/<ID>/ would only "compare" a single Location.  Is the goal here to create pre-defined/link-able "comparisons"? If so let's create a new URL like /compare/<name>/ and have a section of the admin allow you to create those comparisons.

**Comment by smarziano** [comment]
Yes, the reason for creating a pre-defined link is related to the screening tool (#481). The plan is that mRelief will create a screening tool on their website: http://mrelief.com/

The screener will produce a couple of locations using data from the portal, and then a link to compare and contact those locations on our page that is determined by the Entry ID.

**Comment by smarziano** [comment]
For additional info we would like a URL string that looks something like this: http://chicagoearlylearning.org/starred/896/732/124

Another example is how Chicago Public Schools (CPS) currently does their comparison feature. Searching and choosing schools on this site: http://schoolinfo.cps.edu/schoolprofile/SearchResults.aspx produces a URL string like this one: http://schoolinfo.cps.edu/schoolprofile/CompareSelectedSchools.aspx?Schools=400009;610513;609773;400011

**Comment by frankwiles** [comment]
Ok after digging in to figure out how to implement this it turns out it already works with commas. 

http://www.chicagoearlylearning.org/starred/211,638/

**Comment by smarziano** [comment]
Reopening this issue because while this string works, users cannot choose "Contact" or "Back to Search Results."
Here is an example: http://chicagoearlylearning.org/starred/934,829,906,/

When clicking the "Contact" button the user gets a server error. Clicking "Back to Search Results" does not lead to any results. The "Back to Search Results" button would should show similar locations within the same zip code of the starred locations. Ideally the search results would also maintain other filters such as ages served (using Flag fields of the entry IDs), but not sure of the current feasibility of that.

**Comment by frankwiles** [comment]
Issue there is the trailing comma.  If you go to:  http://chicagoearlylearning.org/starred/934,829,906/ "Contact" works fine, the extra commas causes it to try to find another ID that isn't there. 

"Back to Search Results" really doesn't make any sense in this use case as there was no search performed so not sure what we'd use to search on.  While it's likely the locations being compared are close to each other, even just picking one of the addresses as a search term doesn't seem to be ideal. Thoughts?

**Comment by smarziano** [comment]
Verified that "Contact" button does work with this string.

For "Back to Search Results": I believe it makes sense to change the button to say "Back to Search" and then it might clearer no matter how a user gets to the contact page. Once a user clicks on "Back to Search" button they will get to this screen: http://chicagoearlylearning.org/search/

**Comment by smarziano** [comment]
In addition, once a user selects "Back to Search," the locations that were already suggested to them (based on the specific location IDs in the URL) should remain selected under "Compare & Contact." This will allow the user to select more locations to compare against the ones already recommended.

**Comment by frankwiles** [comment]
Contact should be working, however keep in mind the system keeps you from spamming the Locations so if you have a Contact record already in place with that Location ID and your email address it doesn't do anything. 

Changed the code so it will store the suggested locations in their cookie so it's sticky.  Also fixed the back button.  It's not "ideal" in that there isn't a good interface for this, so if their browser window has no real history (i.e. they opened a new window for that link) it will work as expected.  If they re-use a tab it will just go back one page which isn't ideal, but otherwise would lose the search result options of most visitors.

**Comment by smarziano** [comment]
@frankwiles -- the "Back to Search Results" button should be changed to "Back to Search" and should not go back to the user's previous page, but instead go to this page: http://chicagoearlylearning.org/search/

**Comment by frankwiles** [comment]
Ok I'm confused, that should be what you're seeing on staging right now.  What behavior are you seeing that isn't right?

If I browse the site, search, and go to 'Compare and Contact' the back button takes me back a page (to my search results) otherwise it's a link to /search/.

**Comment by smarziano** [comment]
It's pretty confusing. Let me try to detail this out very specifically:
If I visit the Chicago Early Learning Portal > Search > Choose locations to "Compare and Contact" > Go to Compare & Contact page: http://chicagoearlylearning.org/starred/
Then the Back to Search Results page is perfect. It takes me back to my search results from the previous page.

If I visit a specific URL such as http://chicagoearlylearning.org/starred/934,829,906/ from an outside site and then click "Back to Search Results" the page takes me back to my last page in browser. So if I clicked that URL right now, and then clicked "Back to Search Results" I end up back at this Github page.

Since a partner is directing their users to the portal using these types of URLs, we want to make sure that once the user stays on the portal they are able to check out info about those locations and then search for more locations. That is why I think that if a user enters the portal through a specific location URL, and then click "Back to Search" (removed Results) it would make the most sense for them to come to this page: http://chicagoearlylearning.org/search/

**Comment by frankwiles** [comment]
Ok I'm following you now.  This is live on staging now.

**Comment by smarziano** [comment]
Perfect!

**Comment by smarziano** [comment]
@frankwiles This works on staging, but not live yet. Please push when you can. Thanks!

**Comment by frankwiles** [comment]
It's live, you may just need to refresh your cache.  For most browser's it's just a matter of holding down Shift while clicking the refresh icon.

**Comment by smarziano** [comment]
It works! Thanks.
