### ISSUE TITLE
Add new page with enrollment video 

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#484]
Innovation Delivery Team is creating a video to share the process of "How do you enroll?" They intend to have this completed on Monday, July 27. The roll-out will be on August 1, 2015. 

We would like to create a separate page for enrollment process information (text) and the video. On the homepage, we will have a call-out that says something to the effect: Questions about the enrollment process? Click here to learn more.

The video will be placed on Youtube and can be embedded onto this page.

**Comment by smarziano** [comment]
Content for new page to describe enrollment process. The video is still in the works but will be embedded on the right-hand side of the page.
___
<h1>Enrolling in Chicago: Ready to Learn! early learning programs is easy.</h1>

<h2>First, find an enrollment site near you.</h2>

For **community-based** programs, enroll directly at your preferred provider's location. Navigate the Chicago Early Learning Portal to identify a provider that will suit your needs, or call the Chicago: Ready to Learn! hotline at (312) 229-1690 for one-on-one assistance. 

For **CPS school-based** programs, apply at any of the following child-friendly locations:
- Loop, 42 W. Madison Street, 9:00 AM - 5:00 PM
- Colman, 4655 S. Dearborn Street, 9:00 AM - 5:00 PM
- Hall Mall, 4638 W. Diversey Avenue, 8:00 AM - 5:00 PM

_All sites are open until 7:00 PM on Wednesdays!_

Visit cps.edu/readytolearn to learn more about school based enrollment, including additional enrollment opportunities and what to bring. 

Call the Chicago: Ready to Learn! Hotline at (312) 229-1690 for one-on-one assistance.
___

<h2>Next, visit your program's site to begin the process of enrolling your child!</h2> 

A specialist will be there to walk you through the process step-by-step. Many people find it helpful to make a plan to visit an enrollment site. Make your plan here. 

[Note: "here" will link to planning pdf still to be created]

___

<h2>That’s it! Ready to get started?</h2> 
Join nearly 40,000 Chicago children participating in early learning programs. Classes are starting soon…
1) Give us a call or a visit; 
2) Discuss options with a specialist; 
3) Enroll your child for preschool today!

Click here to find programs! [link to search page]

One-on-one guidance: Call the Chicago: Ready to Learn! Hotline at (312) 229-1690. ¡Se habla Español!

___

@frankwiles: for the "First, find an enrollment site..." section, we should discuss the best way to add a function that users can either see all of the enrollment sites (#485) or drive them to search for programs. 

Can you add this new page with content to staging server as we wait for the video to be completed? Thanks!

**Comment by frankwiles** [comment]
This is up on staging here: http://23.23.105.185/enroll

Wasn't sure on the URL you wanted for it.  The 'Sidebar' there is just to help show the area where the video will go.  Let me know if you want anything changed.

**Comment by smarziano** [comment]
@frankwiles  Can you please complete these two tasks today?
- First, remove the "Sidebar" on the enrollment page. Make sure the content is using the full width of the page. It would be nice if this link: "Click here to find programs!" at the bottom was a button.

The URL is perfect. Video is still in the works. When ready please push live. 

- Second, can you add a splash page, similar to what we had in issues #473 & #480. The content is 
"Questions about the enrollment process? Click here to learn more." Linking to the new /enroll page.

**Comment by frankwiles** [comment]
Ok this is live on staging now.  If it looks ok let me know and I'll take it live, but is it ok for the icon and other changes to go live at the same time?

**Comment by smarziano** [comment]
@frankwiles Can you switch location of announcement text on homepage to below the intro text but above the search box? 

Once that is done, you can push live along with the icon changes but not the detail page changes if at all possible. We are just not close enough with the detail pages (#486).

**Comment by frankwiles** [comment]
Hmmm it'll be a lot of work to separate out those changes to master.  Let's see if I can get the Detail pages right quickly.  Commenting on that ticket now...

**Comment by smarziano** [comment]
Would it be easier to remove the line about making a plan in order to proceed today? That way we can work on the other issue later.

**Comment by smarziano** [comment]
@frankwiles Updates look great. Couple of small changes, one I mentioned before: Can you switch location of announcement text on homepage to below the intro text but above the search box?

Also, can you make small changes to the language?
Enrollment is happening now!
Questions about the enrollment process? Click here to learn more.

Thank you!

**Comment by frankwiles** [comment]
Oops guess I forgot those.  They're done and live now.

**Comment by smarziano** [comment]
Great! I am closing this issue. Will reopen if a video is produced that we can add to this enrollment page.

**Comment by smarziano** [comment]
Here is the video that should be included on this enrollment page: http://chicagoearlylearning.org/enroll

Video: https://www.youtube.com/watch?v=jk7rzrsTdpU&feature=youtu.be
Embed code:

````
<iframe width="560" height="315" src="https://www.youtube.com/embed/jk7rzrsTdpU" frameborder="0" allowfullscreen></iframe>
````

**Comment by frankwiles** [comment]
Ok video is up!

**Comment by smarziano** [comment]
@frankwiles Thanks, can you put it in the "Sidebar" location we had previously? Closer to the top (but under the title) and on the right-hand side of the page.

**Comment by frankwiles** [comment]
This is live now.
