### ISSUE TITLE
Add enrollment process information on detail pages

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#486]
The Innovation Delivery Team is interested in sharing enrollment information on each of the locations' detail pages (example: http://chicagoearlylearning.org/location/821/prieto/). This field should be called "Enrollment process." This will be something added to the admin tool, as well. 

We would like to add this before August 1, 2015. We still require the text from the Innovation Delivery Team, which is expected in mid-July. We expect to have only 2 types of information: one version for CPS-based locations and the second for community-based locations.

On the detail pages, this should be listed under the "Description" field:

![screen shot 2015-07-02 at 12 12 27 pm](https://cloud.githubusercontent.com/assets/5550969/8483077/a4e0a3d0-20b3-11e5-821e-eb98e17de3fe.png)

**Comment by smarziano** [comment]
@frankwiles -- We expect to receive the first draft of the content by the end of the day of Tuesday, July 14, 2015.

**Comment by smarziano** [comment]
Here is updated content for the detail pages. Under the name and address field we would like to add a field that is for enrollment information.

The title of the field: "Enroll Now!"
___
<h2>Community-based</h2>
For all community-based locations the language should be:
"Visit this location to begin the enrollment process. Many people find it helpful to make a plan to visit. You can make your plan here."

"Here" will be linked to a PDF, still to be provided.
___
<h2>CPS-based</h2>
For all CPS-based location, the content will be:
"Visit a child-friendly location near you:
- **Loop** 42 W. Madison Street      Hours: 9:00 AM - 5:00 PM
- **Colman** 4655 S. Dearborn Street     Hours: 9:00 AM - 5:00 PM
- **Hall Mall** 4638 W. Diversey Avenue     Hours 8:00 AM - 5:00 PM
All sites are open until 7:00 PM on Wednesdays!

Many people find it helpful to make a plan to visit. You can make your plan here."

"Here" will be linked to a PDF, still to be provided.
___

@frankwiles 
We want to add this field to the admin tool for so we can change in future enrollment periods.
It would also be useful to add a "Get directions" option on this section, but that is not as much of a priority as adding the above content. Please push to staging first.

**Comment by frankwiles** [comment]
Live on staging

**Comment by smarziano** [comment]
@frankwiles -- a couple of adjustments: can you move the enrollment information to under the phone number field on the detail pages?

In addition, can you add this full line (only part of it currently exists): Many people find it helpful to make a plan to visit. You can make your plan here.

We are going to receive a pdf document which we will link on the word "here" in this last sentence.

**Comment by smarziano** [comment]
In addition to the last comment, here are the links to the PDF for the plan. 
Here is the CPS version: https://www.dropbox.com/s/wrq6ae9hnquvjxr/Enroll%20Plan%20vCPS.pdf?dl=0

Here is the community-based version: https://www.dropbox.com/s/24z65nnwgpwmnn8/Community-based%20Plans%20v3.pdf?dl=0
In this document, there is a specific pdf for each site. @frankwiles, is there any easy way to connect the correct pdf to the site or a way to generate the information?

**Comment by frankwiles** [comment]
These are all done and live on staging. 

I just included the PDFs as static files on the site, so if the content needs to change in the future you can just replace these two PDFs https://github.com/smartchicago/chicago-early-learning/tree/staging/python/ecep/portal/static/files

**Comment by smarziano** [comment]
@frankwiles I am not seeing Enrollment information listed on Community-based sites:
![image](https://cloud.githubusercontent.com/assets/5550969/9046699/32e422e0-39f2-11e5-9779-8dfa4ef64a5a.png)

Information is listed on CPS detail pages. Thank you!

**Comment by frankwiles** [comment]
That location isn't set to be Community Based.  Here is an example where it is set and working http://23.23.105.185/location/1420/zapata/

**Comment by smarziano** [comment]
Thank you, @frankwiles, but this is a bit more complicated. The PDF has all of the community-based sites listed in one document. Is there any way that we can link the appropriate PDF page to the detail pages?

What is the easiest way to do this? Let me know how I can help. Thanks.

**Comment by frankwiles** [comment]
Do you mean have a separate PDF for each enrollment center perhaps? And then have each location link to the what closest center? Or do you mean something else entirely?

**Comment by smarziano** [comment]
In the community-based planning document PDF, each page is for a different location. We need to separate them and make sure the correct sheet is associated with each site. 

Would it be easier to generate the information on the PDF from our database if we had a blank PDF with editable fields? (Just a thought)

Does this help? Or make things more confusing?

Another note: I am discussing the URL at the bottom of the planning document with IDT since I have questions about where parents are being directed. Therefore, we should think about how easy/hard it would be to update the documents if necessary.

**Comment by frankwiles** [comment]
Sorry I was looking at the CPS PDF and didn't see the tons of pages for the community one.  Making a dynamic PDF isn't something we can get done today, but my first question is "Does it really need to be a PDF at all?" If I made a page that filled in the necessary info and looked ok printed wouldn't that be a better option?

**Comment by frankwiles** [comment]
Logos and general layout isn't a big deal, but does it need to be "pixel perfect" for example can we loose the "/" and "at" in the "I will visit on" field.

**Comment by smarziano** [comment]
You can loose the extra characters and "at" on the "I will visit on field" and make similar necessary changes on other fields

**Comment by frankwiles** [comment]
Ok this is live on staging, example community site: 

http://23.23.105.185/location/956/tuesdays-child/

Example form: 

http://23.23.105.185/enroll/plan/956/

It's not pixel perfect, but should be close enough.  I left the link off at the bottom since you said it was still being setup/debated. Let me know if this is good to go live!

**Comment by smarziano** [comment]
@frankwiles This is ready to go live. 

We will clean it up and add the link information at a later time.

**Comment by frankwiles** [comment]
Great.  It's live on production now!

**Comment by smarziano** [comment]
Reopening this issue to add a couple of tasks:
For **community-based sites** please add this sentence:
Want us to send you a reminder for your visit? Sign up here:
http://j.mp/ChiEnroll

_This text should follow the same formatting as on the bottom of this PDF: http://chicagoearlylearning.org/static/files/enrollment-plan-cps.pdf_

For **school-based sites** can you follow the same format as the community-based sites by generating a new page (instead of PDF)? This is just to keep consistency between types. Instead of adding the information of the site (like with community-based sites) all CPS school-based sites should have the same information found (again) on this PDF: http://chicagoearlylearning.org/static/files/enrollment-plan-cps.pdf

Also, can we add a "Print" button with a printer icon to these pages?

**Comment by smarziano** [comment]
This has been completed with pull request https://github.com/smartchicago/chicago-early-learning/pull/508
