### ISSUE TITLE
Replace map icons with new icons

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#487]
This relates issue #471. We would like to replace all of the icons currently used for the location pinpoints on the map. The new icons can be found in this folder: https://www.dropbox.com/sh/1qpxgw8u0ijgnyf/AAA0v5hxIywmWEkZsLE1MSQKa?dl=0

There are two sizes of the each icon (50x50 vs. 90x90). The purple "appsite" icon is for the CPS application sites reference in issue #471.

![appsite-icon-50x50](https://cloud.githubusercontent.com/assets/5550969/8583303/27a3f47e-2592-11e5-9461-5afaca9f3202.png)

@frankwiles -- please add on staging first. Thank you!

**Comment by frankwiles** [comment]
Live on staging.
