### ISSUE TITLE
Add Ages 0-3 & Ages 3-5 Fields to API

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#488]
@frankwiles -- We would like to share the Age "Flag" fields on the City of Chicago data portal:
https://data.cityofchicago.org/Education/Chicago-Early-Learning-Programs/ck29-hb9r
The data portal gets updated by this API: http://chicagoearlylearning.org/en/api/location

We need to first add the Ages 0 - 3 and Ages 3 -5 to the Chicago Early Learning API. Ideally, we would like to do a test first so that Jon Levy, Open Data Program Manager for the City of Chicago, can make sure the new field are uploaded properly.

This relates to screening tool in #481.

This task should be done as soon as possible. Thank you!

**Comment by smarziano** [comment]
@frankwiles Please prioritize this issue to get done today (July 22, 2015). Thank you!

**Comment by frankwiles** [comment]
This is done and live on staging and production.
