### ISSUE TITLE
Text function is not working

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#489]
When a user texts their zip code to this number: (773) 886-1819 a reply is never sent. 

I have checked multiple zip codes in thinking that it might have been just the zip code I chose, but none of them worked: 60623, 60628, 60660

**Comment by frankwiles** [comment]
This doesn't seem to be logging anything useful on the server side.  Does Twilio have any information on their end about the failures?

**Comment by smarziano** [comment]
@frankwiles I am seeing this error in Twilio: *Error: 11200 - HTTP retrieval failure* and *Error: 11205 - HTTP connection failure*

I have added you as a user to Smart Chicago's Twilio account. Can you investigate to see what is happening? Thank you!

**Comment by frankwiles** [comment]
Ok this is fixed now.  Turned out to be a small permissions problem in the production settings related to the previous Django upgrades.
