### ISSUE TITLE
Improve search page on mobile

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#492]
If users do not have a successful search on mobile, meaning they did not put in a proper address or location name, they are lead to the general search page: http://chicagoearlylearning.org/search/?lq=
However, this is difficult to navigate on mobile. Here is an example screenshot:

![image](https://cloud.githubusercontent.com/assets/5550969/9643750/6e541fac-5189-11e5-919b-7774d84c75aa.png)

The user is only able to see a piece of the list of community areas, and is unable to scroll to the list. The initial priority fix is to remove the map key for the user to see more of the list and navigate the site that way. After choosing a community area, the user should go to the map view of the site to remain consistent with the current functionality when the address search is successful:

![image](https://cloud.githubusercontent.com/assets/5550969/9644030/a8e6e8a6-518a-11e5-821c-fbe0f85211ec.png)

This user experience will also be improved by implementing ElasticSearch #490 and getting users to more accurate search results.

**Comment by theandrewbriggs** [comment]
This very likely won't make it into this milestone, January 2016 we'll start looking at the mobile experience as a whole.

**Comment by smarziano** [comment]
The biggest problems with search page on mobile will be addressed through other issues.
- Getting accurate results will be addressed with the issues within this milestone: https://github.com/smartchicago/chicago-early-learning/milestones/Improve%20Search%20Function
- Map icons are showing up on the list view (see example in first comment) will be addressed by moving the icons from under the filters and adding a legend to the map: #515 

In the future, we want to make it easier for parents to filter their search results and choose between list and map views. This will take more work in designing the mobile search experience.

I am closing this issue since we have created more specific issues that will improve this experience and will need to create more tasks in the future.
