### ISSUE TITLE
List Schools/Centers location by distance, not alphabetically

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#514]
Once a parent searches for an address, if they get a successful search page then the centers and schools are listed alphabetically instead of being sorted by distance.

It makes more sense that the top list results would be the closest results to the address searched for.

<img width="1235" alt="screen shot 2015-11-20 at 2 41 05 pm" src="https://cloud.githubusercontent.com/assets/5550969/11311330/c2071b06-8f94-11e5-8d0c-edbf535a8978.png">

**Comment by theandrewbriggs** [comment]
One potential problem with this is how does the list react when you move the map around? The current list displays all locations in the map window in alphabetical order, but sorting by distance won't really make sense if you move the window away from the entered target address.

A way we could avoid this is by keeping the target marker at the center of the map, regardless of where you move the map to, and keep listing results by distance from the map's center point.

**Comment by theandrewbriggs** [comment]
@smarziano I wasn't planning on including this in the Christmas Milestone; it's first on the list if I wrap up everything else.

**Comment by theandrewbriggs** [comment]
It is very unlikely that this feature can be implemented without serious data redesign. I think it's possible, but would take some substantial investigation. I can look into this if we think it's an absolutely necessary feature, but in the meantime I will not be working on this.

**Comment by smarziano** [comment]
Due to the amount of work this will take, I am removing this from our current milestone. We expect that after usability testing, that there might be additional improvements needed on the search page/map and we will include this enhancement at that time.
