### ISSUE TITLE
Add legend to map

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#515]
Currently map legend is listed next to the filters and take a lot of space from the list of schools/centers information. I would like the map legend to be listed on the map.
Here is what it currently looks like

<img width="1247" alt="screen shot 2015-11-20 at 3 04 01 pm" src="https://cloud.githubusercontent.com/assets/5550969/11311832/fdc60cbc-8f97-11e5-86b8-03b72e89d391.png">

**Comment by theandrewbriggs** [comment]
I'll see if, in addition to providing the legend, there's a way I can add filtering to the legend as well (e.g., clicking on the 'CPS-based' setting in the legend will only show CPS-based results).

**Comment by smarziano** [comment]
Currently, the icons do not have filtering function and, therefore, this is not something we need to see on the map. @theandrewbriggs will investigate further to find a simple solution.

**Comment by smarziano** [comment]
Before we considered including a filtering function in the legend. This was more of a space management tactic, but since layout has improved, this is not something we will move forward with unless we hear otherwise from our partners and users.
