### ISSUE TITLE
Create Custom Mapbox Map

### ISSUE THREAD

**Issue by theandrewbriggs** [smartchicago/chicago-early-learning#518]
Next steps from Issue #513. We should discuss the design concerns for a new custom map (MapBox's tools are very powerful). Some basics:

- We probably don't need things like road labels or major features (or do we?)
- Color palette

This shouldn't be too hard but we should discuss what's gonna go into this.

**Comment by smarziano** [comment]
Assigning this to myself so that I can look at some Mapbox default maps and see if there is a better option for us. My thinking is that this current map works for our needs.

**Comment by smarziano** [comment]
Just as follow-up, I think that the current map we are using works pretty well for our needs right now. On the staging site, the font is small. With larger text it might make sense to only show major street names so it does not get too busy. 

Here is a screenshot of the search page on staging:
<img width="1267" alt="screen shot 2016-02-09 at 1 36 52 pm" src="https://cloud.githubusercontent.com/assets/5550969/12928300/480ff24a-cf32-11e5-9962-04d83eb4a751.png">

**Comment by theandrewbriggs** [comment]
Just reiterating the previous point: we're gonna leave this map as it is, but I will look into making the default font larger on Retina screens.

**Comment by smarziano** [comment]
The default font is larger now and therefore, this is waiting on merge.
