### ISSUE TITLE
"More" button on search results list should lead to location page

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#522]
Once a user searches they can use the list on the left-hand side of the page to see nearby locations and find out more about those centers. The "More" button expands additional information, but with the current design it's difficult to navigate and read:
<img width="1265" alt="screen shot 2015-12-09 at 5 55 54 pm" src="https://cloud.githubusercontent.com/assets/5550969/11702764/ca71cdb8-9e9e-11e5-92e7-edd147ba9d60.png">

The user is unable to go to the location page from the list. Since we moved a lot of pertinent information in the row with the location's name, this information is not as important.

Tasks are:
- [x] Add "Ages served" under the name of the center with other detail information 
- [x] Change the action of the "More" button to lead to the location page

**Comment by theandrewbriggs** [comment]
Also a part of this issue (that could be broken out into its own issue), the components of the menu that expand down for more detail needs to be removed as well. The data payload can be reduced as well, as a lot of information being sent won't be needed any more.
