### ISSUE TITLE
Add Locations to Autocomplete dropdown

### ISSUE THREAD

**Issue by theandrewbriggs** [smartchicago/chicago-early-learning#524]
We're gonna have tiered results in the dropdown, distinguishing between Addresses and Locations. It'll look something like:

Search for '123':
   **Addresses**
        123 N Michigan Ave
        123 N Lasalle Ave
    **Locations**
        ABC-123 Preschool - Uptown
        ABC-123 Preschool - Lincoln Park

- [x] Add API endpoint in Django for dumping all locations from DB
- [x] Add tiered support in Jquery Autocomplete widget

**Comment by theandrewbriggs** [comment]
This will solve issues #469 and #385.

**Comment by smarziano** [comment]
This is live and works on production.
