### ISSUE TITLE
Fix alignment of header image and text blocks on mobile

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#529]
The header image and text blocks are aligned too far to the left. Here is a screenshot from my iPhone 5:
![img_4565](https://cloud.githubusercontent.com/assets/5550969/11981739/e708ca0e-a96a-11e5-945d-2d897d37cb44.PNG)

**Comment by theandrewbriggs** [comment]
@smarziano This is should be closed, correct?

**Comment by smarziano** [comment]
@theandrewbriggs Yup, I thought there was still an issue, but I cannot replicate it so I will close this issue now.
