### ISSUE TITLE
Add Ages served to list of locations

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#540]
Relates to issue #522. Since the "More" button will lead to the detail page vs expanding, it would be good to show "Ages Served" under the name on the list of locations where other important information is listed (such as full week, part day, head start, etc)

**Comment by theandrewbriggs** [comment]
This looks like it's still doable with existing data structure without digging too deep into underlying structures.

**Comment by smarziano** [comment]
I will ask our partners what makes sense to be listed under each center. I think Ages served is going to be a priority item, but other information like full day/part day might not be. Also, we might not need to distinguish between CPS-based/community-based during the new enrollment period.

**Comment by smarziano** [comment]
Cara Bader suggested that we could limit this info to:
**Center Name**
Address
Ages Served 
Full/Part Day

On desktop version, parents would still see the icon for CPS based/Community based in the list. On mobile, this would be not be represented and we want to see if this is something that should be added.

**Comment by theandrewbriggs** [comment]
Updated this display. @smarziano - Not a huge issue, but there's not a standard format for the ages served in the data:
<img width="288" alt="screen shot 2016-05-14 at 18 48 47 pm" src="https://cloud.githubusercontent.com/assets/3439795/15271240/c485b180-1a04-11e6-83c5-a9769ed6acd5.png">

**Comment by smarziano** [comment]
@theandrewbriggs Instead of using the single text field, should we use the (Y/N) fields for Ages 0-3 and Ages 3-5 to keep things standardized? 

I think with the Phase 1 launch we could switch it to all ages served when it becomes more consistent in ECM.

**Comment by smarziano** [comment]
@theandrewbriggs, a couple of other notes:

- Full/Part week is still appearing on the list view. This should be removed entirely
- The CPS-based/Community-based icons are missing from this view. They should be included on desktop (not mobile), but just the icon not the text.

**Comment by smarziano** [comment]
@theandrewbriggs Can we implement similar styling to the list view as we did on the center detail page for Ages Served?
![image](https://cloud.githubusercontent.com/assets/5550969/15276743/578d9cd4-1ab6-11e6-9365-934eea5b44e5.png)

Or instead of "Serves ages 0 to 3, 3 to 5" I think we should at least keep it as Ages 0 - 3, Ages 3 - 5 to keep it consistent with the filters. I do not think how it is on staging right now is very clear or easy to read.

**Comment by smarziano** [comment]
Adding label "Waiting on Merge" due to recent updates. I am sure this will be something we look at again when we do the data refresh for "Phase 1" enrollment period.

**Comment by smarziano** [comment]
This is now updated! As I said in my previous comment, I expect that we will make additional changes for Phase 1, but this is ready for Early Bird enrollment period. Closing this issue.
<img width="486" alt="screen shot 2016-05-16 at 8 57 38 am" src="https://cloud.githubusercontent.com/assets/5550969/15291572/45bce0b2-1b44-11e6-8a91-432de0fcdef3.png">
