### ISSUE TITLE
Load all Location Markers on map creation

### ISSUE THREAD

**Issue by theandrewbriggs** [smartchicago/chicago-early-learning#542]
Right now the client-side code (map-adjacent code, in the JS) queries Django for markers specifically in the viewport window of the map, which is why the map takes a second to load in markers after load or panning the map to a different location.

This creates unnecessary redundant communication between the server and the client software, as well as reproduces existing functionality that already exists within the Leaflet framework. 

Transitioning to loading the entire data payload of schools at runtime might increase the initial amount of data loaded in by the site, but will significantly cut down on data transmission while using the map itself, and also create a faster, more responsive experience for users while navigating the map.

This will also be an excellent opportunity to clean up a lot of the map code (both client- and server-side), which will make the map code easier to understand and modify in the future.

This is non-urgent, but should be done soon--it'll save development time in the long run--and should be done sometime after Issue #522 is completed.

**Comment by theandrewbriggs** [comment]
In theory, this will also fix existing bugs of the map not loading groups of markers. 

e.g.,
Note the dozen or so missing markers around the Graceland Cemetery:
![screen shot 2016-01-20 at 15 53 18 pm](https://cloud.githubusercontent.com/assets/3439795/12464348/1b77f4b6-bf8e-11e5-8cee-8d2e1d965f18.png)

**Comment by theandrewbriggs** [comment]
This can't happen without the new API data endpoint.

**Comment by smarziano** [comment]
@theandrewbriggs Is this something that we ever completed?

**Comment by theandrewbriggs** [comment]
Yes! This is complete.
