### ISSUE TITLE
Investigate ways to automatically generate location's latitude/longitude from address fields

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#553]
Through the admin tool, the process of generating a location's latitude and longitude coordinates is a manual process with the "Geometry" map. 

<img width="814" alt="screen shot 2016-04-06 at 11 00 33 am" src="https://cloud.githubusercontent.com/assets/5550969/14323618/d156b350-fbe6-11e5-8821-bf6effcceaec.png">

We want to investigate ways to make this more automatic using the address field data. 
@theandrewbriggs shared that the Google Maps python API will let us find coordinates based on addresses. Therefore, we could create a function dedicated to generating coordinates based on address data.

The biggest consideration is thinking about how this will work with the ECM system.

**Comment by smarziano** [comment]
@theandrewbriggs will build this out with the import function. We are waiting on the sample data set from our partners.

**Comment by smarziano** [comment]
@theandrewbriggs has discovered that there is bulk updater functionality already built in. He will investigate further to see how this fits in with Phase 1 launch.

**Comment by theandrewbriggs** [comment]
This component is being built out with the importer.

**Comment by smarziano** [comment]
This has been built out with the importer. @theandrewbriggs I am adding a "Waiting on Merge" label because based on previous conversations this seems to be completed.

**Comment by smarziano** [comment]
Closing this issue.
