### ISSUE TITLE
Update center data structure

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#559]
We will need to incorporate new center data fields from the refreshed data set. Therefore, in the admin tool/database, we will need to make some additions and adjustments to the fields that currently exist. 

Assigning myself to make sure we get this information from our partners.

**Comment by smarziano** [comment]
Here is the excel extract document that we received from our partners with the field names. 
[ELECM_Site_Extract.xlsx](https://github.com/smartchicago/chicago-early-learning/files/258203/ELECM_Site_Extract.xlsx)

_Note: we will need to cross-check this when we receive the first full data export._

**Comment by smarziano** [comment]
@theandrewbriggs Here are the field names from the csv document: https://www.dropbox.com/s/v3ff5dgxdzvl419/TopRow-Chicago_EarlyLearningSites.csv?dl=0

**Comment by theandrewbriggs** [comment]
This work is being performed alongside construction of the importer.

**Comment by smarziano** [comment]
This is done, too, with completion of issue #560.
