### ISSUE TITLE
Refresh center data

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#560]
This is closely related to #559, but once we update the data structure, then we will also need to make sure the data is refreshed. 

We will need to cross-check the new data with the old data to see if there are locations missing from this list and see if there is a reason that they were left off. An example is home-visiting programs (issue #477).

**Comment by smarziano** [comment]
@theandrewbriggs We received a new preliminary list of centers.
[Preliminary List all Preschools.xlsx](https://github.com/smartchicago/chicago-early-learning/files/224831/Preliminary.List.all.Preschools.xlsx)

Can you please cross-check this list with our current database? Add 1 tab with any locations we have that are not listed in this document and then add another tab with locations they have and we don't have in our database. 

In the upcoming weeks, we will get a full refresh of the data for the upcoming enrollment period.

**Comment by smarziano** [comment]
Assigning this to myself because I am working with partners to get the data updated.

**Comment by theandrewbriggs** [comment]
This is ongoing, will be performed in coordination with construction of ECM and CoE, some of this work will be completed with the importer.

**Comment by smarziano** [comment]
I am closing this issue because we have refreshed the data given to us. We will still need to include seat availability levels but that should be done with the nightly export.
