### ISSUE TITLE
Update Map to serve @2x PNG tiles on Location pages

### ISSUE THREAD

**Issue by theandrewbriggs** [smartchicago/chicago-early-learning#563]
The font is really small on the location page maps, they were never updated to serve the @2x tiles.

**Comment by smarziano** [comment]
Confirmed! This looks good, closing this issue. 

<img width="984" alt="screen shot 2016-04-22 at 3 48 16 pm" src="https://cloud.githubusercontent.com/assets/5550969/14754562/bdaa5420-08a1-11e6-9561-505c5b83f182.png">
