### ISSUE TITLE
Update to navigation bar

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#566]
We will be updating the navigation bar for the new enrollment period.
We will remove: "Text for Info" and "About" 
We will add (these will be new pages): "Apply now!" "For Parents" and "City Resources" 

Order will most likely be: 
Apply now!
For Parents
FAQs
City Resources
Keep in Touch
Español

**Comment by smarziano** [comment]
"Text for Info" was removed from the nav bar due to issue #607.

**Comment by smarziano** [comment]
We discussed removing "Keep in Touch" from the nav bar and placing it in the footer due to space considerations. From my last check-in with partners, the other topics should be in the nav bar.

**Comment by smarziano** [comment]
Instead of "For Parents" use "For Families" or maybe just "Families." This change is reflected in the buckets below the hero image #637.

**Comment by smarziano** [comment]
Here are symbols for the mobile version of the nav bar.

**Apply now!**
I think this could be a checkmark to match the rest of the "Compare and Apply" symbology. Another option is something like this https://thenounproject.com/search/?q=application&i=387993

**For Families**
https://thenounproject.com/search/?q=family&i=156650

**FAQs** 
We can keep this symbol the same.

**City Resources** 
I think we should use the Chicago star: https://thenounproject.com/term/chicago/218401/

**Español** 
ES (same as current)

**Comment by theandrewbriggs** [comment]
@smarziano: Can I get Spanish translations for 'Apply Now,' 'Families', and 'City Resources'? I wanna make sure we're leaving enough room in the breakpoints of the nav.

**Comment by smarziano** [comment]
Spanish translations:
Apply now! = ¡Aplique Ahora! or if we are short on space ¡Aplique!
Families = Para Familias  (I would try to have "For Families" in the English version too if possible)
City Resources = Recursos de la Ciudad (this is long... maybe just "Recursos" for "Resources"?)

**Comment by smarziano** [comment]
@theandrewbriggs Here is another option for the "Apply Now!" mobile symbol: https://thenounproject.com/search/?q=application+with+check&i=132233

**Comment by smarziano** [comment]
In addition to switching the mobile symbol in my last comment, can we also switch the placement of "City Resources" and "FAQs"? I think it would flow better.

**Comment by smarziano** [comment]
Updated! Waiting on merge...

<img width="1276" alt="screen shot 2016-06-18 at 7 55 05 pm" src="https://cloud.githubusercontent.com/assets/5550969/16174607/c7547fe0-358e-11e6-9b8c-a4b7c4d423b3.png">

<img width="390" alt="screen shot 2016-06-18 at 7 56 57 pm" src="https://cloud.githubusercontent.com/assets/5550969/16174608/d6ea3076-358e-11e6-8b1d-d257786d75a9.png">

**Comment by smarziano** [comment]
Confirmed this is live. Closing issue!
