### ISSUE TITLE
Create a footer

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#567]
We are removing "About" from the top navigation bar (#566). Our partners would like to see this as part of a footer. I expect that this footer would persist on all pages, but maybe not map-relevant pages.

"About" would still link to https://chicagoearlylearning.org/about

**Comment by smarziano** [comment]
Additional thoughts:
Due to nav bar spacing, we think "Keep in Touch Email Newsletter" would be good to move to the footer.
Maybe a statement that this is the City of Chicago's Early Learning Portal (this would be removed from the hero image)? Built by Smart Chicago Collaborative?

**Comment by smarziano** [comment]
Update: footer on all pages except map search pages, also could be excluded from the Compare & Apply /starred pages because there is not a standard size of page that depends on number of centers that parents favorited.

**Comment by smarziano** [comment]
Here is the view of the footer on my screen, on staging:
<img width="1278" alt="screen shot 2016-06-23 at 8 05 48 am" src="https://cloud.githubusercontent.com/assets/5550969/16292354/576bf490-3919-11e6-9704-a7c808e5858f.png">

Here are thoughts/suggestions:
- I think it would read better if the "About" piece and "Built by" piece were together. "About the Chicago Early Learning Portal | Built by Smart Chicago Collaborative"
- Let's shorten the give feedback statement to "Give us feedback to help make the Early Learning Portal better" with "Give us feedback" hyperlinked to the form
- I think the hyperlink teal is really hard to read on the footer.

While this isn't a lot of stuff in the footer, I think it still works and is good to have.

**Comment by smarziano** [comment]
The hyperlinks are not properly connected to the proper pages in the footer. The "About" hyperlink should go to the /about page, the "Give us feedback" should go to the Wufoo form, and the "Keep in Touch" piece should go to http://chicagoearlylearning.us5.list-manage.com/subscribe?u=085247dea37361c266002462c&id=5161f6a47c

**Comment by theandrewbriggs** [comment]
I think we should maintain branding for Chicago Early Learning in Spanish - that component of the logo doesn't change. I ran some of the translations by a native Spanish speaker in my office and he gave me some slightly tweaked translations which will be up on staging soon.

**Comment by theandrewbriggs** [comment]
This is all on staging.

**Comment by smarziano** [comment]
@theandrewbriggs I agree about the Spanish translation. I'm not a big fan of two names of a site (one in English and one in Spanish). 

Therefore, in Spanish change to...
- Sobre del portal del Chicago Educación Temprana
- Opine para mejorar el portal del Chicago Educación Temprana

Regarding the Keep in Touch piece, I am not happy with the translation as it is because it's too long and taking too much space. Let's shorten this piece only in Spanish.

Currently: Manténgase en contacto por subscribiendo a nuestro Early Learning Boletín de Correo Electronico.
New: Subscriba a nuestro boletín informativo de Chicago Educación Temprana.

-------- 
English changes:

- Let's consistently call it "Chicago Early Learning"... so "Give us feedback to help make the Chicago Early Learning portal better" and "Keep in touch by signing up for the Chicago Early Learning email newsletter"
- A big problem I think I'm having with the footer is that the left and right sides are not aligned with the text on the page. 
- Spelling error: feeback > feedback

**Comment by theandrewbriggs** [comment]
These changes are live on staging.

**Comment by smarziano** [comment]
Almost completed. The "Give feedback" phrase is not translated on the Spanish version. "Opine para mejorar el portal del Chicago Educación Temprana" link "Opine para mejorar" to the form.

**Comment by smarziano** [comment]
This has been completed. Adding "Waiting on Merge" label.

**Comment by smarziano** [comment]
This is live. Closing issue. We should think in the future of what other important info might be placed in the footer. Right now, there's not too much, but I think it's still very useful for parents!
