### ISSUE TITLE
Add pass parameters to apply. subdomain

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#568]
If a parent uses the Chicago Early Learning portal in Spanish, we would want to add a pass parameter to the URL string of apply.chicagoearlylearning.org so that will lead to a Spanish application or the Spanish language enrollment system.

We also want to pass all of the location IDs from a user's favorites list to ECM. This relates closely to issue #483.

**Comment by theandrewbriggs** [comment]
This logic will exist in the JS layer for the starred page. Waiting on final ECM URL structure.

**Comment by smarziano** [comment]
The URL structure will be something like this: 
https://apply.chicagoearlylearning.org/?cartid=226|222|229|230|234|228

ECM IDs will be separated by |
According to our partners, no language parameters will be added since users will be able to choose at the login screen.

**Comment by smarziano** [comment]
Waiting on merge. 

When on the Compare & Apply page with centers favorited (https://staging.chicagoearlylearning.org/favorites/211,881,222,613,1019,824,616,588/) will generate a handoff URL when clicking the "Apply" button with the ECM IDs. It will only choose locations that are in ECM (issue #660) and up to 6 locations (#655).

**Comment by smarziano** [comment]
After working with partners, there have been some updates made to the URL structure and this now works. Closing issue!
