### ISSUE TITLE
Update splash announcement with application link

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#580]
For the "Early Bird" launch we will be updating the splash announcement text and the position on the homepage:

- [x] Update text

**Apply Today!**
Application for Fall 2016 preschool enrollment is now open, click here to apply.
Questions?  Refer to our FAQ guide for more info.

[here] will be linked to apply.chicagoearlylearning.org
[FAQ guide] will link to the FAQs page: https://chicagoearlylearning.org/faq

- [x] Our partners would like to see the splash announcment under "Find the right program for your child" header on the homepage. 

@theandrewbriggs I think this might be harder to do on mobile based on how mobile is currently built. I think another suggestion is to remove the text box ("Welcome to...") in the hero image and move this "Apply Today!" information there vs making it a separate splash announcement. Thoughts about this? I will check in with our partners if you think this is a good move.

**Comment by theandrewbriggs** [comment]
![screen shot 2016-05-10 at 16 37 19 pm](https://cloud.githubusercontent.com/assets/3439795/15163344/8a06c22c-16cd-11e6-89ad-7506417fc208.png)

**Comment by theandrewbriggs** [comment]
@smarziano Here's the updated mobile homepage with the repositioned announcement

**Comment by smarziano** [comment]
That positioning will work, @theandrewbriggs!

**Comment by smarziano** [comment]
Updated for Early Bird enrollment period. Closing this issue.
<img width="584" alt="screen shot 2016-05-16 at 8 59 18 am" src="https://cloud.githubusercontent.com/assets/5550969/15291620/847e03d0-1b44-11e6-8e24-a41340cd37d2.png">
