### ISSUE TITLE
Center's detail page map does not interact as expected

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#586]
Whenever I am on a center's detail page (https://chicagoearlylearning.org/location/211/), if I try to scroll down the page (using my trackpad) sometimes the map showing the center's location will actually move. If I try to move the map back, my mouse changes to the hand tool which makes it seem like I would be able to move the map, but I am unable to.

I would expect to be able to zoom in and out, but I am not sure if any other map movements are necessary. Therefore, I would limit movements to zooming in and out and not change to the hand cursor when hovering over the map.

@theandrewbriggs let me know what you think or if you have questions.

**Comment by smarziano** [comment]
On staging, removing the scroll zoom is a much better solution. The last change I would make is to remove the "hand tool" when users hover over the map. The hand makes it appear that you can move that map around (which you can't).

**Comment by smarziano** [comment]
Hand tool when hovering over the map has been removed on staging. Waiting on merge.

**Comment by theandrewbriggs** [comment]
Pushed to production.

**Comment by smarziano** [comment]
This is confirmed! Closing this issue.
