### ISSUE TITLE
Staging: "Text for Info" phone number is missing

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#593]
@theandrewbriggs On staging, when you go to /sms the phone number to text is missing from this page. It is also missing on the "Text for info" bucket on the homepage.

See screenshot below... it says "Text your zip code to and"
<img width="522" alt="screen shot 2016-05-14 at 10 01 29 pm" src="https://cloud.githubusercontent.com/assets/5550969/15271786/7247ee86-1a1f-11e6-93df-4d0517f7c577.png">

**Comment by theandrewbriggs** [comment]
This is a production vs staging issue - there's no global setting for the twilio number on staging so nothing renders here.

**Comment by smarziano** [comment]
Got it, @theandrewbriggs! Closing this issue.
