### ISSUE TITLE
Staging: Filters are misaligned

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#594]
This relates to issue #477 when we added the word "Offers" to the "Home Visiting" filter. It seems to have misaligned the filters, especially "Accepts CCAP."

<img width="496" alt="screen shot 2016-05-14 at 10 03 18 pm" src="https://cloud.githubusercontent.com/assets/5550969/15271798/e19354ec-1a1f-11e6-9434-427be33a26ce.png">

A suggestion might be to switch "Accepts CCAP" filter with "Offers Home Visiting" and then center "Visiting" since it falls on the second line.

**Comment by theandrewbriggs** [comment]
@smarziano This is dependent on window size, we don't have a ton of control over how these display and stack when you shrink the window down unless we lock the sidebar and sacrifice map space; I think this could be done next week after early bird launch, tweaking these would probably take a really long time we don't have today.

**Comment by smarziano** [comment]
I am moving this issue to our "Phase 1" enrollment milestone.

**Comment by theandrewbriggs** [comment]
Here's a solution where everything stays on the same line, so if one row gets pushed down, they all get pushed down together. I think this is the closest we can get to retaining the same order (@smarziano  ignore the actual order for now, I need to go and change it later, I'm just trying to get feedback on the look):
<img width="387" alt="screen shot 2016-05-26 at 16 49 13 pm" src="https://cloud.githubusercontent.com/assets/3439795/15591331/0405e15c-2362-11e6-9c19-b0c11a4f278c.png">

**Comment by smarziano** [comment]
I am not sure if I like this better. Let's keep it as it is. I say this because we have done a lot of work to consolidate space, and I don't think this is helpful. If we find a different solution in the future, great, but right now let's close this issue.
