### ISSUE TITLE
Update formatting of FAQs hyperlinks

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#602]
Regarding this page: https://chicagoearlylearning.org/faq

I like the new setup with the FAQs page where it links to specific questions or topics. I would like to see a color or other distinction between Topics and Questions when they are hyperlinked at the top. I feel like this is a just a lot of blue and it's pretty hard to read. I also think we could make the font sizes smaller.

**Comment by theandrewbriggs** [comment]
Waiting on final site redesign plans; current table of contents is difficult to read, come up with new color scheme for URLs.

**Comment by smarziano** [comment]
Also, let's think about how FAQs look on mobile. It's a bit hard to read when questions run to a second or third line. It might be better to have these indented. Here's a screenshot from my phone:

![img_5327](https://cloud.githubusercontent.com/assets/5550969/15948138/bd1eac98-2e64-11e6-9ebb-f2c25fffc77d.PNG)

**Comment by theandrewbriggs** [comment]
Do we want a header image here like on the other static pages? Just a thought.

**Comment by smarziano** [comment]
@theandrewbriggs Try this one for a header image... I like that idea to keep it consistent with all the other pages.

![theresa7](https://cloud.githubusercontent.com/assets/5550969/16444537/1f1d1984-3de7-11e6-9046-dc428b3049d0.jpg)

**Comment by smarziano** [comment]
<img width="1027" alt="screen shot 2016-07-01 at 6 14 24 am" src="https://cloud.githubusercontent.com/assets/5550969/16510914/2164f94c-3f53-11e6-8d29-1f5cc53e9800.png">

Adding a header image to be consistent with the rest of the page is a nice addition. Also updating the color to distinguish between questions and headers makes it easier to read.

**Comment by smarziano** [comment]
Looks great! Closing issue.
