### ISSUE TITLE
Different zoom level for zip code and community area searches

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#604]
We need to look at having different zoom level for address searches vs zip code or community area searches. Parents and Early Learning providers are not finding the appropriate location because the pinpoint is at the center of the zip code/community area and does not take the shape into account.

This came up specifically with Stock Elementary. If you type in "Edison Park" it does not appear because of the current zoom level:

<img width="1229" alt="screen shot 2016-05-16 at 2 54 23 pm" src="https://cloud.githubusercontent.com/assets/5550969/15301988/1bf7f01e-1b76-11e6-80f7-bf0448ab4eb4.png">

Stock Elementary is a little further north:
<img width="1226" alt="screen shot 2016-05-16 at 2 54 55 pm" src="https://cloud.githubusercontent.com/assets/5550969/15302002/31bf7250-1b76-11e6-81ce-336091831894.png">

Note: The current zoom level is very important for address searches because we heard from our partners that parents weren't getting locations close enough to the address they searched for. This relates to the work in this milestone: https://github.com/smartchicago/chicago-early-learning/issues?q=milestone%3A%22Improve+Search+Function%22

**Comment by theandrewbriggs** [comment]
Update on this: Google passes some metadata in with its autocomplete results, so I'm working on reconfiguring the map to recognize some of these types and, when appropriate, set a slightly higher zoom level. 
![screen shot 2016-05-23 at 16 32 14 pm](https://cloud.githubusercontent.com/assets/3439795/15485329/33d3f758-2104-11e6-962c-10b821fa61f1.png)
![screen shot 2016-05-23 at 16 32 35 pm](https://cloud.githubusercontent.com/assets/3439795/15485330/33dd5e1a-2104-11e6-9882-be08d755a08e.png)

**Comment by smarziano** [comment]
We changed the zoom levels with commit: https://github.com/smartchicago/chicago-early-learning/commit/d67300dbb9892c157e71b0a53336436b0aca2846

This applied specifically to zip code and community name searches. We wanted to make sure all of the locations within that area were being shown so we wanted a higher zoomed out level. We still wanted to make sure that address searches were much closer and showed much more relevant results.

This is live & closing issue.

More documentation of changes made:
**Zip Code Search (Example is 60647)**
Here was the old view when you search for zip code 60647:
<img width="1265" alt="screen shot 2016-05-24 at 12 53 24 pm" src="https://cloud.githubusercontent.com/assets/5550969/15520614/d4880860-21cc-11e6-811e-727cb089af20.png">
 
Here is our updated version on staging which is a wider view:
<img width="1264" alt="screen shot 2016-05-24 at 12 53 15 pm" src="https://cloud.githubusercontent.com/assets/5550969/15520624/e43ca77a-21cc-11e6-91ee-c5d32141f849.png">

This is closer to what you receive from Google maps for search 60647:
<img width="1267" alt="screen shot 2016-05-24 at 12 53 34 pm" src="https://cloud.githubusercontent.com/assets/5550969/15520635/eca2820e-21cc-11e6-99bb-8a257b50ec7d.png">

**Community name search (Example is North Lawndale)**
Old view:
image004.png
<img width="1267" alt="screen shot 2016-05-24 at 12 59 22 pm" src="https://cloud.githubusercontent.com/assets/5550969/15520647/fa8f587e-21cc-11e6-8314-8d900a41afd1.png">

New view:
<img width="1268" alt="screen shot 2016-05-24 at 12 59 13 pm" src="https://cloud.githubusercontent.com/assets/5550969/15520652/025c06ec-21cd-11e6-9385-8d76d44efa05.png">

Corresponding map on Google:
<img width="1274" alt="screen shot 2016-05-24 at 12 59 30 pm" src="https://cloud.githubusercontent.com/assets/5550969/15520659/0f24b112-21cd-11e6-87b8-4333c584f23c.png">
