### ISSUE TITLE
Spanish: Center detail pages are not showing all of the information

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#606]
Currently, there's information missing from the center detail page that is definitely in the admin tool. Here is an example:
https://chicagoearlylearning.org/location/243/?

<img width="1222" alt="screen shot 2016-05-18 at 12 33 20 pm" src="https://cloud.githubusercontent.com/assets/5550969/15368723/df57b722-1cf4-11e6-943a-35893c531bab.png">

We are missing the ages served, accreditation, head start info on for this location in this example.

**Comment by smarziano** [comment]
The centers' information has been added, but they are not properly translated. A lot of this information is in Spanish in the admin tool. Example: is QRIS rating (Evaluación de calidad) is Gold (Oro) is properly translated in the admin tool.

Things that are not translated in the admin tool and would probably need to be updated in the database:
- Ages 0 - 3
- Ages 3 - 5
- Offers Home Visiting

**Comment by smarziano** [comment]
This has been updated on staging and is waiting on merge:
<img width="902" alt="screen shot 2016-05-31 at 6 45 57 pm" src="https://cloud.githubusercontent.com/assets/5550969/15694035/01953fec-2760-11e6-9c85-513582508beb.png">

**Comment by smarziano** [comment]
This is now on production, closing issue.

**Comment by smarziano** [comment]
I am reopening this issue because the center's detail pages are not showing the description field when there is a Spanish description. Here is an example of a Spanish description I just added for Korean American Community Services: https://chicagoearlylearning.org/location/324/

<img width="985" alt="screen shot 2016-06-06 at 8 40 26 am" src="https://cloud.githubusercontent.com/assets/5550969/15823903/5adb5d6e-2bc2-11e6-891f-ebd39957e5c2.png">

**Comment by theandrewbriggs** [comment]
Pushed to production.

**Comment by theandrewbriggs** [comment]
Current blocker: If a location has no Spanish description, the template renders the English description when viewing the site in Spanish. 

@smarziano to determine if this behavior is acceptable.

**Comment by smarziano** [comment]
I keep going back and forth on this. I feel like when an English description comes up in the Spanish version that it appears more of an error than workaround solution. 

I feel more inclined to not show description if there isn't a Spanish description added. I'm sure, though, Spanish-speaking families can find other ways to translate and at least showing the English version will give them options to do that. 

Another alternative is that when we only have an English version to let people know that. Something like:
"**Descripción** _(no hay una descripción en español)_"

Any thoughts on this, @theandrewbriggs? I'll keep thinking about it and see what maybe our partners say!

**Comment by smarziano** [comment]
We decided to add a statement explaining that there wasn't a description in Spanish. Relates to commit https://github.com/smartchicago/chicago-early-learning/commit/c652fc1ba91ef2ac039a3e38315f84fbbab5ce19

This is live. Closing issue! 

<img width="262" alt="screen shot 2016-06-09 at 11 11 13 am" src="https://cloud.githubusercontent.com/assets/5550969/15937017/e830faf8-2e32-11e6-8b8b-70f0ed4b711e.png">
