### ISSUE TITLE
Spanish: Navigation bar text is not fitting

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#607]
This relates to issue #605, but the navigation bar in the Spanish version is not fitting:

<img width="1226" alt="screen shot 2016-05-18 at 9 52 06 am" src="https://cloud.githubusercontent.com/assets/5550969/15363416/4c01c58c-1cde-11e6-81fb-5fa1ad49fff2.png">

**Comment by theandrewbriggs** [comment]
From a technical standpoint this is the same issue as #605.

**Comment by smarziano** [comment]
We did two things here to solve this problem. First, we removed Text for Info in preparation of Phase 1 launch since our plan is to create a new tab:

<img width="1260" alt="screen shot 2016-05-19 at 12 15 58 pm" src="https://cloud.githubusercontent.com/assets/5550969/15402869/e78144d2-1dbb-11e6-9a66-6787c53e6ba5.png">

Second, on smaller screen sizes we removed "Chicago Early Learning" from the logo to manage space better:

<img width="1159" alt="screen shot 2016-05-19 at 12 19 42 pm" src="https://cloud.githubusercontent.com/assets/5550969/15402889/fb7cffee-1dbb-11e6-9d65-7a1b73ec09a9.png">

**Comment by smarziano** [comment]
Actually, @theandrewbriggs, I am reopening this issue because I would prefer to keep the full logo on the homepage since we have space in the nav bar.

Here is what the homepage looks like on a slightly smaller screen:
<img width="1170" alt="screen shot 2016-05-19 at 12 25 24 pm" src="https://cloud.githubusercontent.com/assets/5550969/15403088/de6be7b6-1dbc-11e6-9ddc-f7e6d6ce30fa.png">

Let me know if this is possible.

**Comment by smarziano** [comment]
This is fixed via commit https://github.com/smartchicago/chicago-early-learning/commit/6e7f788c101387c8bece7ae44929834eb4c71a5b

Closing this issue!
