### ISSUE TITLE
Highlighted buttons do not clear after clicking

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#611]
After clicking on a button on the /search page, the button continues to remain highlighted with the help text also highlighted. This is clearly seen after clicking on "More filters," for example, or the "Compare and Apply."

Here is an example:
<img width="496" alt="screen shot 2016-05-19 at 9 06 48 am" src="https://cloud.githubusercontent.com/assets/5550969/15396356/58d908c4-1da1-11e6-9726-c97a04b5e198.png">

<img width="501" alt="screen shot 2016-05-19 at 9 06 42 am" src="https://cloud.githubusercontent.com/assets/5550969/15396357/5bcf6e7e-1da1-11e6-9486-fc1ac13e01a1.png">

**Comment by theandrewbriggs** [comment]
This has something to do with the hint.css library we're using for tooltips. Dig into this post-Phase One launch.

**Comment by smarziano** [comment]
This is fixed with commit https://github.com/smartchicago/chicago-early-learning/commit/d76a64cf0c1099e418c6ebe6d9dbd397c2bb288a

**Comment by smarziano** [comment]
This fix is now live. Closing issue.
