### ISSUE TITLE
Spanish: Clicking on "Less Filters" changes the "More Filters" back to English

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#615]
Once getting to a search page in Spanish, the "More Filters" is in Spanish (Más Filtros), but if you click that and then click "Less Filters" button the "Más Filtros" button reads "More Filters" (in English):

<img width="494" alt="screen shot 2016-05-19 at 12 44 54 pm" src="https://cloud.githubusercontent.com/assets/5550969/15403617/7eac55ec-1dbf-11e6-88b4-656c4752a081.png">

<img width="499" alt="screen shot 2016-05-19 at 12 45 04 pm" src="https://cloud.githubusercontent.com/assets/5550969/15403621/86ef8292-1dbf-11e6-9b8b-5bb410209f1b.png">

<img width="497" alt="screen shot 2016-05-19 at 12 45 21 pm" src="https://cloud.githubusercontent.com/assets/5550969/15403626/8fffa542-1dbf-11e6-96c2-e5f68610c687.png">

Another note is that the "Less Filters" button needs to be translated to "Menos filtros"

**Comment by smarziano** [comment]
This is fixed and on staging. Adding "Waiting on Merge" label.

**Comment by theandrewbriggs** [comment]
Pushed to production.

**Comment by smarziano** [comment]
Confirmed that this is working. Closing!
