### ISSUE TITLE
Spanish: store translations within database

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#617]
When we begin to update the data structure #559 we need to make sure to store and connect the proper Spanish translations that currently exist in the admin tool. 

I don't know how much we will need to change to accommodate this but want to keep this in mind as we work.

**Comment by theandrewbriggs** [comment]
As part of building the importer, we're going to keep all of the old data around in a re-named object, and clone the database. All post-launch data will only ever be stored in this new Location object, old Location objects will remain in the database.

**Comment by smarziano** [comment]
We need translations for low/medium/high for the new allocation level/seat availability field.

**Comment by smarziano** [comment]
Spanish translations for low/medium/high
Low = bajo
Medium = medio
High = alto

**Comment by smarziano** [comment]
Closing!
