### ISSUE TITLE
Remove "Text for Info" bucket

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#625]
@theandrewbriggs Since Text for Info is not working and we are going to remove it for June 13 launch, can we remove this bucket entirely on the homepage starting immediately? Let's just have two columns with the other information.

**Comment by theandrewbriggs** [comment]
This change is now live on production.

**Comment by smarziano** [comment]
@theandrewbriggs I think the two columns that currently exist should be wider, right now it looks like something is missing or didn't load. Can we widen the two current columns? At the same time, let's keep the dimensions that currently exist for the three buckets because we expect to have three buckets at launch.

**Comment by smarziano** [comment]
This works better! Closing this issue. 
<img width="1103" alt="screen shot 2016-06-01 at 1 54 07 pm" src="https://cloud.githubusercontent.com/assets/5550969/15721826/5e3f7d98-2800-11e6-92df-753c12f91648.png">
