### ISSUE TITLE
Content: Update buckets under hero image on the homepage

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#637]
We will be updating the content under the hero image on the homepage for the Phase 1 launch. We expect to have three buckets to showcase three topic areas. Right now, the expectation is to have something like 1) For Families, 2) Find and Compare, and 3) Enroll.

I am waiting for content updates from our partners.

**Comment by smarziano** [comment]
@theandrewbriggs Here is content for below the fold:

<h3>For Families</h3>
Children who participate in high-quality early learning experiences are better prepared for success in both kindergarten and over a lifetime of learning. **Click here** to learn more about how to invest in your child’s success through early learning, the different types of programs offered, and tips to help you choose a high quality program.
**Learn more about high quality early learning »**

 _Bolded areas above should lead to a new "For Families" page /families_

<h3>Find & Compare</h3>
Search by the address where you live or work to quickly find all the early learning programs located near you. Refine your search to find the features you most care about. Choose your "favorites" and compare them on a list.
**Find and compare locations now »**

Linked to /search

<h3>Apply Today</h3>
Are you ready to apply for a preschool program for your 3- or 4-year old? Fill out an application online through your individual family portal today.  Questions about the application and enrollment process or programs for younger children please read our **FAQ** or call 312-229-1690.
**Fill out an application online »** 

FAQ linked to /faq and "Fill out an application online" is linked to apply.chicagoearlylearning.org.

------------
Here are the images I would like to use for each of the buckets:
**For Families**
![forfamiliesbucket](https://cloud.githubusercontent.com/assets/5550969/15871993/dcd5225a-2cbc-11e6-8db9-87c016bc15a7.png)

**Find and Compare**
I want to use a new screenshot of our map, but want to wait until we get new map icons (#633). @theandrewbriggs use the "Find and Compare" bucket image we have now as a placeholder.

**Apply Today**
![roseland3](https://cloud.githubusercontent.com/assets/5550969/15872084/3a1a3446-2cbd-11e6-90df-6006c71ed578.jpg)

--------------
I am still waiting for Spanish content from our partners. The "Find and Compare" bucket has not changed:
_Busque por la dirección donde usted vive o trabaja para encontrar rápidamente todos los programas de educación temprana, ubicados cerca de usted. Afine su búsqueda para así encontrar las características que mas le interesen. Escoja sus "favoritos" y compárelos con la lista.

Encuentre y compare ubicaciones ahora »_

**Comment by smarziano** [comment]
Here is a screenshot to use for the "Find and Compare" bucket:
![findandcomparescreenshot](https://cloud.githubusercontent.com/assets/5550969/16024171/f7d2823c-3185-11e6-825e-7f570bfd1d89.png)

**Comment by smarziano** [comment]
Update to the "Apply Today" bucket:
"Are you ready to apply for a preschool program for your 3- or 4-year old? [Click here](chicagoearlylearning.org/howtoapply) to learn more about the application and enrollment process or call 312-229-1690. Then fill out an application online through your individual family portal today.  Questions about the application and enrollment process or programs for younger children please read our [FAQ](chicagoearlylearning.org/faq).
Fill out an application online »"

Click here will go to the new enrollment page (/howtoapply).

**Comment by smarziano** [comment]
A couple of small changes to the "Apply Today" bucket:
- Hyperlink "here" to "Click here"
- Hyperlink "Click here" to /how-to-apply
- Change this text to be less repetitive and more informative: "Questions about the application and enrollment process or programs for younger children please read our FAQ." **to** "Questions about programs for younger children (ages 0 - 3)? Please read our FAQ."

**Comment by theandrewbriggs** [comment]
This is all on staging.

**Comment by smarziano** [comment]
Changes have been made for English version and are live. Still need Spanish translations. I'm closing this issue and creating a new one for post-launch work.
