### ISSUE TITLE
Content: Create new "For Families" page

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#647]
We are going to create a new "For Families" page that has information about why early learning programs are important. This can be accessed from the text buckets under the hero image (#637) and in the nav bar (#566).

I expect the URL to be chicagoearlylearning.org/families
We are waiting on content from our partners.

**Comment by smarziano** [comment]
<h1>Parent Information </h1>

<h2>Learn. Succeed. Grow!</h2>

The City of Chicago is dedicated to ensuring every child in every neighborhood can access a quality education that begins in their earliest years. No matter what needs a family faces, the City and its partners a focused on providing secure, quality early learning programs for children that build a foundation for success in the rest of his or her academic and professional career.

<h2>Benefits of Early Learning</h2>

Early learning programs and experiences activate your child while they are at the most important stage of developing the abilities that will become the foundation for success in school and beyond. Early learning activities are designed to support the development of physical, intellectual and social and emotional skills. Through creative and structured play activities with their peers, children are improving their use and understanding of motor skills, numbers and relationships, language, and emotional control.  

Children that are exposed to early learning activities are not only better prepared to enter kindergarten, but they have greater success in graduating high school, raising their future earning and career potential, and achieving their adult goals.

<h2>Explanation of Different Programs Offered</h2>

Different programs serve children of different ages and are funded in a variety of ways. Many sites have more than one type of program. The descriptions below will help you understand the general differences between programs.

While early childhood education is important for the healthy development of every child, each family has different needs. It is important to select a program that fits your family's budget and schedule, and one that provides a safe and stimulating environment for your child. You should call and visit each program that you are interested in to find out more about whether it is a good fit for your family.

<h3>Preschool</h3>

This program provides educational and early childhood development activities that promote school readiness for three to five year old children from low-income families. Programs may also include free medical, dental, and mental health services and nutritious meals, as well as parent education and training.  These programs may also be referred to as Head Start or Preschool for All, based on the funding and services provided. Programs can be Half Day or Full Day.

<h3>Infant and Toddler Programs</h3>

This program provides educational and early childhood development activities for children from birth to three years old from low-income families. Programs may also include free medical, dental, and mental health services and nutritious meals, as well as parent education and training. These programs may also be referred to as Early Head Start, Prevention Initiative, or Early Intervention, based on the funding and services provided.

The early education programs at the City of Chicago are available in a number of different settings:

- Chicago Public Schools (CPS) Based: Elementary schools in the Chicago Public Schools district offer early education programs to children ages three to four.
- Community Based: Community-based organizations provide early childhood education for children birth to age five in preparation for kindergarten (hours may vary). Eligible children enrolled in participating child care centers receive an enhanced educational program. These are targeted to low- and moderate-income working parents.
- Home Visiting: Visiting coaches offer early care in the child’s home. The coaches deliver educational and early childhood development activities that promote school readiness for children from birth to three years old from low-income families.

<h2>Tips for Choosing a Great Program for Your Child</h2>

It does not take any special knowledge to be able to identify a high quality early childhood program. You will see the signs clearly:

- Educated, attentive, and engaged teachers and staff
- Teachers who speak to children at eye-level and speak directly to infants and toddlers
- Teachers who show affection toward children (holding, cuddling)
- A safe, healthy, and child-friendly environment
- A well-equipped room with accessible materials and toys, placed at eye level for the children
- Stimulating activities and appropriately structured routines
- Child engagement with activities
- Children offered meals (breakfast and lunch) and naptime
- Individual, small-group, and large-group activities
- A daily routine
- The use of indoor and outdoor spaces
- Age-appropriate language, literacy, math, science, art, music, movement, and dramatic play activities
- Independent play
- Visitors welcomed with appropriate parental consent
- Frequent hand-washing by children and adults
- Exchanging information between families and teachers about the child's development and learning progress
- Teachers with four-year degrees as well as training in early childhood education specifically
- A maximum of 8 infants and toddlers, a maximum of 20 preschoolers in a classroom
- 1:3 teacher: child ratios for infants and 1:10 teacher: child ratios for preschoolers

To learn more visit: http://www.ounceofprevention.org/news/characteristics-of-quality-early-learning.php

It is a good idea to schedule a visit to meet program staff. Many parents find it helpful to write down a list of questions before calling or visiting. Here are a few suggestions of things to ask, in addition to your own specific questions:

- What will my child do each day?
- What makes your program special?
- How do you include parents in the classroom?
- How long has the preschool been in business?
- What kind of accreditations or certifications do you and your staff have?
- Can I volunteer and visit my child’s classroom?
- How can I help in my child’s program?
- How do I apply to enroll my child?
- Will I have to pay anything?
- What are the eligibility criteria for this program?
- What are the hours for pick-up and drop-off?
- What kind of information or documents will you need for my child (birth certificate, immunization records, etc.)?
- Will my child need a physical exam before enrolling?
- Is there a wait list for this program? How long is it?
- Are there any additional fees I should know about?
- Are there requirements for parent/family involvement? What are they?
- Do I have to have a job in order to send my child to this program?
- What are the attendance policies?
- On what days or weeks is the program closed?

--------------------
Here are a couple of choices for photo(s). Maybe have one at the top as a smaller header? Or a couple within the text?

![marycrane6](https://cloud.githubusercontent.com/assets/5550969/16090976/43c571aa-32f7-11e6-8f04-d7f139d31e50.jpg)

![theresa21](https://cloud.githubusercontent.com/assets/5550969/16090983/4835f1b0-32f7-11e6-95d6-19e1542e8f01.jpg)

**Comment by smarziano** [comment]
@theandrewbriggs I really like the direction of the City Resources page: https://staging.chicagoearlylearning.org/city-resources

In a similar fashion, can we add breaks to this text with a horizontal line as we did between orgs on the /city-resources page? I think it will help make this not seem like a run-on of information.

**Comment by theandrewbriggs** [comment]
These changes are live on staging. I can add more line breaks if need be.

**Comment by smarziano** [comment]
We're getting there! Couple of changes

- [ ] I think the title of the page should read "Learn. Grow. Succeed!" to match the other language changes. (what you have now was in the text provided, but let's make this change)
- [ ] Re: the second image we used, I am not sure if it's the right one. Here's another option:
![belmont1](https://cloud.githubusercontent.com/assets/5550969/16442518/de1f7cb6-3ddb-11e6-8bd8-612a9143650e.jpg)
Cropped to maybe...
![forfamilies2](https://cloud.githubusercontent.com/assets/5550969/16442539/f5f7cb04-3ddb-11e6-84d7-8b22affc32db.jpg)

**Comment by smarziano** [comment]
Changes have been made and pushed to staging. Adding "waiting on merge"

**Comment by smarziano** [comment]
Confirmed that all of this is live. Closing issue!
