### ISSUE TITLE
Content: Create new "City Resources" page

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#648]
We are going to create a new "City Resources" page that has information about other city resources that are important for parents with children of this age group. This can be accessed from the text buckets under the hero image (#637) and in the nav bar (#566).

I expect the URL to be chicagoearlylearning.org/cityresources
We are waiting on content from our partners.

**Comment by smarziano** [comment]
<h1>City Resources</h1>

The City of Chicago and Mayor Rahm Emanuel are committed to bringing access to high quality early learning opportunities to families throughout the city. In addition to great programs for children at schools and community agencies, there are a number of opportunities to start stimulating your child with early learning in other environments.

<h2>Chicago Park District</h2>
Many parks offer early childhood recreation classes— moms, pops, and tots interaction, play group, preschool, puppetry, storytelling, and Moms, Dads, & Tots Gymnastics. Early childhood participants develop and enhance their motor, listening and social skills through movement education programming. [Visit the Chicago Park District website to find and sign up for a class near you](http://www.chicagoparkdistrict.com/).

<h2>Chicago City of Learning</h2>
[Chicago City of Learning (CCOL)](https://chicagocityoflearning.org/) is a groundbreaking initiative that joins together learning opportunities for young people in a way that allows them to think about, pursue, and develop their interests. CCOL partners to bring early childhood experiences to spaces during the summer to prepare children to enter kindergarten in the Fall. Visit CCOL to find opportunities near you.

<h2>Chicago Public Library</h2>

The [Chicago Public Library (CPL)](http://www.chipublib.org/) has many enriching opportunities for children including early learning spaces at libraries and preschool reading hours. CPL also features mobile units that bring hands-on STEAM (science, technology, engineering, arts and math) learning activities for young children along with family literacy programming facilitated by librarians throughout the city. The CPL has three mobile units with these STEAM-based learning kits deployed throughout the city – one for each Library District. Contact CPL for details.

<h2>Tinkering Lab at the Chicago Children’s Museum</h2>
The [Chicago Children’s Museum](http://www.chicagochildrensmuseum.org/) features a number of early learning spaces for children to support the development of communities where play and learning connect. One permanent exhibit, The Tinkering Lab, features an early learning nook of safe interactive objects and touchable tools. The Children’s Museum also partners to bring early learning and engagement spaces to other places in the city. Contact the Chicago Children’s Museum for details. 

<h2>Chicago Department of Public Health</h2>
The foundation for early learning and a child’s success starts with maternal and infant health. The Chicago Department of Public Health’s neighborhood health clinics offer care for expectant mothers and wellness services for children. [Contact the Chicago Department of Public Health for details.](http://www.cityofchicago.org/city/en/depts/cdph.html)

**Comment by smarziano** [comment]
I think this might be a good image to use on this page:

![marycrane4](https://cloud.githubusercontent.com/assets/5550969/16102602/a3932958-3336-11e6-8dba-306aba277a06.jpeg)

**Comment by smarziano** [comment]
I like using the image in the previous comment as a header image.

I was thinking we could mimic the format of the About page on this page, too. I think it will break up the page and make it easier to read. If you agree, @theandrewbriggs, here are the logos:

![chicagoparkdistrictseal](https://cloud.githubusercontent.com/assets/5550969/16141514/0c760404-3422-11e6-84d0-6d98119384f7.png)

![ccol](https://cloud.githubusercontent.com/assets/5550969/16141533/411ecf56-3422-11e6-9ea2-d707fa7e6b46.png)

![cplreverse_web_190x105](https://cloud.githubusercontent.com/assets/5550969/16141657/acc21b90-3423-11e6-951f-0052e2cdf297.png)
^ This is in white. Can you invert?

![ccmlogo](https://cloud.githubusercontent.com/assets/5550969/16141673/d5c25b0e-3423-11e6-9258-bfc11dd82531.jpg)

![logo_partner_cdph](https://cloud.githubusercontent.com/assets/5550969/16141688/f7411c84-3423-11e6-970c-e77b46850bf8.png)

**Comment by theandrewbriggs** [comment]
A new draft of this is up on staging; waiting for input on header image style. Beyond that, mobile styling needs to be done.

**Comment by smarziano** [comment]
@theandrewbriggs I like how this header image looks. I think this should be used on other content pages /families and /how-to-apply, too.

I'm not adding a "Waiting on Merge" label because of the mobile styling that needs to happen.

On this City Resources pages. Please also hyperlink the "Contact" sentences of each paragraph with the website of the organization. This is specifically for CPL, CCOL, and CCM.

**Comment by smarziano** [comment]
Another note: Can you please align all of the logos? Some of them are a little further to the left and right of others. It would be great if the centers aligned.

**Comment by theandrewbriggs** [comment]
These changes are live on staging.

**Comment by smarziano** [comment]
Beautiful page! "Waiting on Merge" label added.

**Comment by smarziano** [comment]
Closing issue!
