### ISSUE TITLE
Add New Legend

### ISSUE THREAD

**Issue by theandrewbriggs** [smartchicago/chicago-early-learning#651]
Add the new legend provided by design team. Adding this new legend will fix the #585 loading problem.

![screen shot 2016-06-12 at 14 31 34 pm](https://cloud.githubusercontent.com/assets/3439795/15993437/db00c248-30ab-11e6-949e-59c300d8cd6c.png)

**Comment by smarziano** [comment]
@theandrewbriggs I am actually going to request that this legend is updated to change "None" to "Few."

**Comment by smarziano** [comment]
Here's the new legend with updates to the opacity level and the change in language:
![map_key2](https://cloud.githubusercontent.com/assets/5550969/16025996/be94c664-3190-11e6-9f4d-48c04588e254.png)

**Comment by smarziano** [comment]
@theandrewbriggs Here is the higher res version of the map key. 
![map_key_hires](https://cloud.githubusercontent.com/assets/5550969/16053168/3c07f020-322d-11e6-9fae-c2a5f594ba1f.png)

**Comment by smarziano** [comment]
Legend is added, but it is also on the top neighborhood layer. We had this issue before.

See this page: https://staging.chicagoearlylearning.org/search/

**Comment by smarziano** [comment]
Updated with commit https://github.com/smartchicago/chicago-early-learning/commit/2906a89ebd8e0a228601364a0f411cac096726e6 

Adding "Waiting on merge" label.

**Comment by smarziano** [comment]
This is all set. Closing issue.
