### ISSUE TITLE
Update favicon

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#653]
Since we will be updating the logo (#649), we should also update the favicon. I am assigning this to myself to see if the designers have the capacity to do this work this week.

**Comment by smarziano** [comment]
We got a few options from the designers but I think they look very pixelated. Moving this issue to "Phase 1" Launch clean-up milestone to continue working on this.

**Comment by smarziano** [comment]
@theandrewbriggs Here is the favicon file: https://www.dropbox.com/s/m7zhxkj3e2yrge9/favicon.ico?dl=0

**Comment by theandrewbriggs** [comment]
Requested designers add higher-res retina-grade favicon to the file, will push this when that happens.

**Comment by theandrewbriggs** [comment]
For reference:
<img width="204" alt="screen shot 2016-07-14 at 11 40 12 am" src="https://cloud.githubusercontent.com/assets/3439795/16847673/cbb59ae6-49b7-11e6-9e4d-a429442d9e64.png">

**Comment by smarziano** [comment]
This is now live. Closing issue.
