### ISSUE TITLE
Content: Update /enroll page to /howtoapply

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#654]
Currently, the /enroll page redirects to the FAQs page. We previously had an enrollment page that gave information about the process - issue #484. We want to update this enrollment page with the content below. The URL should be /howtoapply, and /enroll should redirect to this new enrollment page.

<h1>Enroll</h1>

Enrolling your child in early childhood programs is easy and open year round. All you need is to complete three easy steps:

1. Find your preferred program(s)
2. Submit an application online [link] or at a Family Resource Center
3. Visit your provider or Family Resource Center to confirm your placement.

<h2>Finding programs</h2>

The City of Chicago and its partners offer early learning programs at over 600 sites throughout the city. Visit our search page [link] to identify sites in areas near your home or work. The Early Learning Portal allows you to identify a programs quality rating, schedule and ages served.

We encourage you to reach out to preferred providers to ask questions or schedule a visit. Resources to help identify if a program is a good fit for your family are included on our family information page [link].

If you need assistance with general questions or finding options near you, feel free to call the Chicago Early Learning Hotline at (312) 229-1690. If you have specific questions for our city departments and providers call the CPS Office of Early Childhood Education (773) 553-2010, DFSS Children’s Services Division (866) 647-2489, or the number listed on a provider’s detailed info page. 

<h2>Apply</h2>

This year, Chicago launched an online application to apply for preschool programs at over 600 sites throughout the city accessible from your home computer, shared computer or mobile phone. Visit apply.chicagoearlylearning.org to sign up for family account and profile, create an application for your child(ren), and select your preferred sites. You will be able to immediately see if you are eligible for a preliminary placement with a provider.

If you do not have access to a computer or mobile phone or would prefer in person assistance, visit one of 10 Family Resource Centers throughout the city, where a Family Resource Specialist can assist you. A list of Family Resource Centers is available here. 

You can also call the Chicago Early Learning Hotline at (312) 229-1690 and submit an application over the phone.

If you are interested in programs for children birth to aged three – contact your preferred provider directly.

<h2>Visit to confirm</h2>

Once you have received a preliminary placement, you will be directed to your provider or a Family Resource Center to provide additional information that may confirm your placement. We recommend that you call your site in advance to confirm the necessary materials and a good time to visit.

Once your placement is confirmed, you will receive any additional info necessary to finish registration and start the program. Please let your provider know if you need an immediate placement, or you are interested in enrolling for the next program year. Both options may be available.

If your child or family is in a temporary living situation, living in a shelter, or sharing a house with another family, you will not be required to provide documentation. Falsifying this information may result in loss of placement.

If you are looking to enroll your child in a birth to three year old program or home visiting services, please contact your preferred sites directly or call the Hotline for assistance.

--------------------
Here is a photo option for this page:

![roseland3](https://cloud.githubusercontent.com/assets/5550969/16103277/b0345032-333c-11e6-9760-dda48df2fd83.jpeg)

**Comment by theandrewbriggs** [comment]
This is live on staging.

**Comment by smarziano** [comment]
This is almost there, @theandrewbriggs. Couple of edits:

- [ ] For the header image, I think the cropping is not sitting right with me. I would like the image moved down so you can see more of the children's faces in the back (if that makes sense). Here is an example image:
![how-to-apply-image-example](https://cloud.githubusercontent.com/assets/5550969/16442139/b19f3828-3dd8-11e6-8800-a62c310fb840.jpg)

- [ ] Add link. "2. Submit an application online or at a Family Resource Center." Link to apply.chicagoearlylearning.org when clicking "Submit an application online"

- [ ] Add section breaks found on /families and /city-resources

**"Finding Programs"**

- [ ] Add link to /search to "search page" for "Visit our search page to identify sites in areas near your home or work."

- [ ] Change to "The Chicago Early Learning Portal" in this sentence "The Early Learning Portal allows you to identify a programs quality rating, schedule and ages served."

- [ ] Add link to /families to "family information page" in this sentence: "Resources to help identify if a program is a good fit for your family are included on our family information page."

**"Apply"**

- [ ] Link to /faq#list-of-family-resource-centers in "here" of this sentence:  "A list of Family Resource Centers is available here."
- [ ] Telephone link to (312) 229-1690 in this sentence: "You can also call the Chicago Early Learning Hotline at (312) 229-1690 and submit an application over the phone."

Please also make sure there are no other [link] notes on this page. Thanks!

**Comment by smarziano** [comment]
@theandrewbriggs In this sentence under the "Apply header: "A list of Family Resource Centers is available <here" please remove the <.

Otherwise, good to go. Adding "waiting on merge" label.

**Comment by smarziano** [comment]
This is entirely done and live. Closing issue.
