### ISSUE TITLE
Add error message/instructional text if users click "Apply" with 6+ locations 

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#655]
This relates to #568. After users add locations to their "Compare and Apply" list, if they click "Apply" we will only be able to pass the IDs of up to six locations to the ECM system. Therefore, we should add some help text so that if users have **more than** six locations, so they can narrow down their choices on this page.

**Comment by theandrewbriggs** [comment]
@smarziano Do you have copy for this?

**Comment by smarziano** [comment]
English:
Please select up to **6** locations to continue to the application process. Compare your favorites below to pick the best options for your family. 

Spanish:
Por favor escoja no más de **6** programas para continuar a la procesa de aplicaciones. Compare sus favoritos punto por punto para escoger la mejor opción para su familia.

**Comment by smarziano** [comment]
Current view on staging with seven locations chosen for Compare & Apply:
<img width="945" alt="screen shot 2016-06-23 at 8 50 17 am" src="https://cloud.githubusercontent.com/assets/5550969/16293072/8f9d5164-391f-11e6-96ea-1b219ab0f597.png">

Here are some updates:
- Add Spanish translation
- Do not italicize the 6 (I know I wanted to emphasize this, but it looks weird)
- Is there any reason to be able to "x" out of this notification?

In addition, as a future enhancement, it would be ideal not to refresh the page anytime a person removes a location. This should be it's own separate issue, and can be something we look into post-launch.

**Comment by theandrewbriggs** [comment]
These changes are up on staging; the "x" has been removed.

**Comment by smarziano** [comment]
Confirmed that these changes have been made and are live. 

Bigger question is if we want to stop parents from moving forward until they narrow down their list. Right now it's unclear if parents have more than 6 sites which ones are being passed to ECM. 

I am creating a new issue in milestone "Phase 1" Launch Clean-up.
