### ISSUE TITLE
Switch homepage search bar text

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#657]
At some point during the search updates, we changed the search bar to read "Enter an address, community, or zip code," but we should change it back to "Enter an address, center, or zip code" so that parents know that they can search for a specific center. 

Spanish translation is "Ingrese su dirección, nombre de una escuela, o código postal"

This was something our partners also wanted to see changed.

**Comment by smarziano** [comment]
This is almost ready to go! @theandrewbriggs, please add Spanish translation.

**Comment by theandrewbriggs** [comment]
This is on staging.

**Comment by smarziano** [comment]
Confirmed that this is on staging. Adding "Waiting on Merge" label. 
<img width="631" alt="screen shot 2016-06-24 at 7 53 14 am" src="https://cloud.githubusercontent.com/assets/5550969/16328231/bb1bc46c-39e0-11e6-888b-f62f56c14691.png">

**Comment by smarziano** [comment]
Confirmed that this is live. Closing.
