### ISSUE TITLE
Add notifications about 0-3 centers when users click "Apply" on /starred

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#660]
This relates to issue #655 in adding helpful text.

For programs that only serve 0-3 ages we need to think of helping parents understand that they need to call the center directly vs trying to apply via ECM. We have some content that reads: "Ages 0 - 3: If your child will be younger than 3 years old prior to September 1, 2016, there are infant/toddler programs available. Please contact the site directly for enrollment information for these programs."

If parents click the "Compare and Apply" page we need to add helpful text if the program only serves 0-3 year olds.

We still want parents to be able to compare these locations, but we need to make it clear that they can't apply for these locations.

All 0-3 only programs have the ECM ID of 0 and there are less than a 100 of them in the dataset.

Assigning to myself to identify locations and start writing the help content for this.

**Comment by smarziano** [comment]
On a center detail page (https://staging.chicagoearlylearning.org/location/310/home-based-childrens-place-association/) I think it is pretty clear when a program is **only** 0-3 (infant/toddler) to contact the site directly. 
<img width="974" alt="screen shot 2016-06-19 at 8 42 25 am" src="https://cloud.githubusercontent.com/assets/5550969/16177697/34952e72-35fa-11e6-977f-0739b5b6504f.png">

I am not sure if we need to have another notification when parents click "Compare and Apply" on the center detail page. I do think it will be useful on the Compare and Apply page. 

<img width="972" alt="screen shot 2016-06-19 at 8 47 15 am" src="https://cloud.githubusercontent.com/assets/5550969/16177707/7b12c828-35fa-11e6-92eb-b8c9d2882cc8.png">

We discussed having a bright note at the top of programs that are 0-3 **only**. I would say something like "This program only serves children ages 0-3, please call the site directly to apply."

Spanish version of that note is: "Este programa solamente atiende niños entre las edades de 0-3, por favor contacte directamente al programa."

**Shorter version of those notes**
English: "Serves only ages 0-3, contact the site directly to apply."
Spanish: "Atiende solamente las edades de 0-3, contacte directamente al programa."

**Comment by theandrewbriggs** [comment]
I'm gonna add this notification based not on 0-3 only data but on ECM id data, programs with no ECM ID will raise the flag; does this work?

**Comment by smarziano** [comment]
If that is the case, then we should just have a general note saying "Contact this site directly to apply" or "Contacte directamente al programa para aplicar."

I say this because there might be outlier programs like home-based visiting programs, tuition-based programs (although all of this might have been removed), Montessori in CPS programs, etc, that are on the portal but not in ECM. This would be a broader error message.

**Comment by smarziano** [comment]
This notification definitely stands out on the /starred page:

<img width="878" alt="screen shot 2016-06-19 at 4 23 55 pm" src="https://cloud.githubusercontent.com/assets/5550969/16179914/52d17680-363a-11e6-8838-76234b1f08b3.png">

Just need to add Spanish translation.

**Comment by theandrewbriggs** [comment]
This is on staging, along with Spanish translation.

**Comment by smarziano** [comment]
Confirmed that this is live and translation has been added. Closing issue!

<img width="317" alt="screen shot 2016-07-01 at 10 25 18 pm" src="https://cloud.githubusercontent.com/assets/5550969/16532454/ba9d1c2a-3fda-11e6-9bdd-19dbb4635338.png">
