### ISSUE TITLE
Spanish: Translate Legend for Spanish version of site

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#661]
We need to update the language on the new legend to Spanish (#651). I am assigning this to myself.

**Comment by smarziano** [comment]
![map_key_es](https://cloud.githubusercontent.com/assets/5550969/16171638/a4151d96-3539-11e6-93b5-bc4c4ca98ba0.png)

**Comment by theandrewbriggs** [comment]
Can you get the first line to wrap on those?

**Comment by smarziano** [comment]
Is it ok to move everything slightly to the left for this text? Wrapping it makes it hard to read because it is close to the third line.

![map_key_es](https://cloud.githubusercontent.com/assets/5550969/16171734/5b27100a-353c-11e6-88f4-4e8c393cf77c.png)

**Comment by smarziano** [comment]
Here's another version with the CPS language all on one line:
![map_key_es](https://cloud.githubusercontent.com/assets/5550969/16171818/1bab7030-353f-11e6-9414-63699172c9c5.png)

**Comment by smarziano** [comment]
This is now been pushed live. Closing issue.
