### ISSUE TITLE
Update QRIS ratings design

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#662]
We want the QRIS rating symbols to be updated to match the refresh we are doing to the rest of the website. I am working with the designers to update their design, assigning to myself.

**Comment by theandrewbriggs** [comment]
New icons are live on staging.

**Comment by smarziano** [comment]
Confirmed on staging - "Waiting on Merge" label added. I think they are a big improvement to the diamonds we currently have. 

<img width="1276" alt="screen shot 2016-06-29 at 8 58 12 am" src="https://cloud.githubusercontent.com/assets/5550969/16442016/acd8402e-3dd7-11e6-8e7f-1ab95da735f1.png">

**Comment by smarziano** [comment]
This has been pushed live. Closing this issue.
