### ISSUE TITLE
Staging: /starred page is not showing "Compare & Apply" locations

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#667]
Currently on staging, you are able to add locations to your "Compare and Apply" list, but once getting to the /starred page, they do not appear for comparison. 

<img width="509" alt="screen shot 2016-06-29 at 10 51 11 am" src="https://cloud.githubusercontent.com/assets/5550969/16444603/8308436a-3de7-11e6-9183-2b71f76e612c.png">

<img width="1122" alt="screen shot 2016-06-29 at 10 51 27 am" src="https://cloud.githubusercontent.com/assets/5550969/16444589/72eda4b6-3de7-11e6-8b00-5193bdcbe58a.png">

**Comment by theandrewbriggs** [comment]
I couldn't repeat this bug? It could be a bad internet thing, if the script that loads those in hangs they won't ever show up.

**Comment by smarziano** [comment]
This was an issue where I had old centers favorited in my Compare & Apply list, and then upon recent commits the unmatched IDs were causing a server error. Closing issue.
