### ISSUE TITLE
Updated /starred text with new "Apply" content

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#668]
We want to make edits to content to reflect Phase 1 launch on this Compare & Apply page: https://staging.chicagoearlylearning.org/starred/

_Press the “Apply“ button to complete an application form for your top two site preferences or call the Chicago Early Learning Hotline at (312) 229-1690._

**should be changed to**
 
Press the “Apply“ button to build your Chicago Early Learning parent profile and complete an application. You will be able to view your preliminary placement or waitlist status for the sites indicated below, and may submit an application for up to two of your site preferences (one placement and one waitlist). 

Call the Chicago Early Learning Hotline at (312) 229-1690 if you would like assistance completing the application over the phone.

@theandrewbriggs I will do my best to translate this to Spanish before launch, if not, we should receive translations shortly post launch.

**Comment by smarziano** [comment]
Translation for the second piece starting at "Press the 'Apply' button...(and one waitlist)." is

Presione el botón "Aplicar" para construir su perfil como padre de familia en “Chicago Early Learning” y así completar su solicitud.   Usted podrá ver el estado de su solicitud preliminar, ubicación asignada, o en espera preliminar de los sitios indicados a continuación.  Usted podrá entregar una solicitud para dos lugares como máximo de su preferencia (Uno de ubicación y uno lista de espera).

**Comment by theandrewbriggs** [comment]
I still need a translation for the "Call the Chicago Early Learning Hotline at (312) 229-1690 if you would like assistance completing the application over the phone." part.

**Comment by smarziano** [comment]
Adding translation here, too: Por favor llamar al Chicago Early Learning línea de acceso directo al (312) 229-1690 para asistencia.

<img width="999" alt="screen shot 2016-07-01 at 12 01 45 am" src="https://cloud.githubusercontent.com/assets/5550969/16504141/16e4c904-3f1f-11e6-8723-3065b25f6ca0.png">

Ready to go! Waiting on merge tag added

**Comment by smarziano** [comment]
Confirmed that this is live.
