### ISSUE TITLE
Center detail page: pass ID parameter from center detail page

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#669]
When parents are on a center detail page and they see this text: _"Ages 3 - 5: If your child is 3 or 4 years old prior to September 1, 2016, your child will be eligible for preschool programs. Click here to fill out an application for two preferred sites or call the Chicago Early Learning Hotline at (312) 229-1690 for assistance."_ (https://github.com/smartchicago/chicago-early-learning/issues/588#issuecomment-219309139)

The question is should "Click here" pass the ID to ECM similar to what happens on the /starred page (#568)?

**Comment by theandrewbriggs** [comment]
We could do that, it's fine with me, and shouldn't be too hard. There's some other behavior that needs to be figured out around non-ECM schools.

**Comment by smarziano** [comment]
The majority of this is on staging for preschool programs, but yes, we need to figure out non-ECM 3-5 programs, specifically.

@theandrewbriggs For testing-- Drummond is an example of a 3-5 program that is not in ECM because it is a Montessori program: https://staging.chicagoearlylearning.org/location/911/

**Comment by smarziano** [comment]
Notification added for non-ECM + 3-5 age programs. Waiting on merge tag added.

<img width="978" alt="screen shot 2016-07-01 at 12 58 08 am" src="https://cloud.githubusercontent.com/assets/5550969/16505707/ee2c4f5c-3f26-11e6-88e0-3df5a22e2cc5.png">

**Comment by smarziano** [comment]
Confirmed that this is live. Closing issue.
