### ISSUE TITLE
Stop parents from moving to ECM if they have 6+ locations in Compare & Apply List

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#678]
This relates to issue #655. We should think about whether or not we should allow parents to move forward from the /starred page to ECM if they have more than 6 locations in their list. Right now, it's unclear for parents which location IDs are being passed and it might be better if parents narrowed down their list first before moving forward.

I am assigning to myself to bring up with our partners.

**Comment by smarziano** [comment]
It makes sense to stop parents from moving to ECM if they have more than 6 locations because we don't want parents to lose their selections. They should using Chicago Early Learning as a way to compare locations and narrow down their options. Assigning to @theandrewbriggs for implementation.

**Comment by theandrewbriggs** [comment]
This functionality has been added to staging. The "Apply" button is disabled in this view, could possibly use more obviously disabled styling.
![screen shot 2016-08-11 at 11 30 27 am](https://cloud.githubusercontent.com/assets/3439795/17597191/6930f99c-5fba-11e6-8e80-04168d12cb8c.png)

**Comment by theandrewbriggs** [comment]
@smarziano Thoughts on this 'disabled' styling for the Apply button?
![screen shot 2016-08-16 at 15 22 49 pm](https://cloud.githubusercontent.com/assets/3439795/17714441/686a5ee0-63c5-11e6-882a-08549a5deb10.png)

**Comment by smarziano** [comment]
I struggle with this. Does disabling the "Apply" button just seem like something is broken vs giving enough instruction to the user that they need to narrow down their list? I know that there is a large red box that is supposed to make this clear but is it too much text? 

Do you think the red error message should go under the "Apply" button so it doesn't feel like part of the text?

I am ok with this solution right now, but I feel like there might be a better option, so it might be something to keep thinking about. As for now, this is waiting on merge.

**Comment by smarziano** [comment]
This is now live, closing this issue.
