### ISSUE TITLE
Spanish: Translation on content pages

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#680]
Post-launch, we are still waiting on Spanish translations for these pages:
- [x] City Resources: https://chicagoearlylearning.org/city-resources
- [x] For Families: https://chicagoearlylearning.org/families
- [x] How to Apply: https://chicagoearlylearning.org/how-to-apply
- [x] FAQs: https://chicagoearlylearning.org/faq
- [ ] Also, the City of Chicago blurb on the about page: https://chicagoearlylearning.org/about
- [x] Connect4Tots blurb on City Resource page

**Comment by smarziano** [comment]
<h1> Enroll </h1> 
https://chicagoearlylearning.org/how-to-apply

The header text "Enroll" = Matricular
Translated under the header image is:

Matricular a su hijo (a) en el programa de aprendizaje de temprana edad es fácil y está disponible todo el año.  Sólo se necesita completar tres pasos fáciles:

1.	Encontrar el programa(s) preferido
2.	[Someter una solicitud](https://s56.esserver.com/cel035.enginuity.web.v6/) a través del internet o en un Centro de Recursos Familiares.
3.	Visitar a su proveedor o a un Centro de Recursos Familiares para confirmar su puesto.

<h2> Finding programs = Entérese de programas </h2>
La Ciudad de Chicago, junto con sus afiliados ofrece programas de aprendizaje a temprana edad en más de 600 localidades en varias áreas de la ciudad.  Visite nuestra página de internet ([www.chicagoearlylearning.org](www.chicagoearlylearning.org)) y busque un centro más cercano al lugar de su trabajo o residencia. También puede identificar programas, clasificarlos, buscar horarios y las edades atendidos.

Le recomendamos buscar proveedores preferidos y hacerles preguntas y enterarse de sus horarios.  Recursos para ayudar a identificar si un programa es una buena opción para su familia están incluidos en [nuestra página de información familiar](https://chicagoearlylearning.org/families).

Si usted necesita ayuda con preguntas generales o de cómo encontrar opciones cerca de usted, no dude de llamar a la Línea de Aprendizaje Temprano de Chicago en (312) 229-1690.
Sí usted tiene una pregunta específica para nuestros departamentos y proveedores de la ciudad de Chicago, puede llamar a la oficina de CPS (las escuelas públicas de Chicago) educación a temprana edad (773) 553-2010. DFSS (Departamento de Apoyos y Servicios para Familias) división de servicios para niños  (866) 647-2489, o a el número de teléfono que aparece en la página detallada de los proveedores.

<h2> Apply = Solicitar </h2>
Este año, la cuidad de Chicago lanzó una aplicación en el internet para que familias puedan solicitar los programas preescolares en más de 600 centros en la ciudad accesible desde su computadora o su teléfono móvil. Visite [la aplicación en el internet](https://s56.esserver.com/cel035.enginuity.web.v6/) para adquirir una cuenta y perfil familiar, crear una aplicación para su hijo(s), y seleccionar su centro(s) preferido(s). Usted se enterará inmediatamente si usted es elegible para una colocación preliminar con un proveedor.

Si usted no tiene acceso a una computadora o un teléfono móvil o si prefiere asistencia en personal, puede hacerlo visitando uno de los 10 Centros de Recursos Familiares que tenemos a través de la ciudad, donde nuestros especialistas le pueden asistir a usted. Una lista de Centros de Recursos Familiares está disponible [aquí](https://chicagoearlylearning.org/faq#list-of-family-resource-centers).

También puede llamar a la Línea de Aprendizaje Temprano de Chicago en (312) 229-1690 y someter una solicitud por teléfono.

Si usted está interesado(a) de un programa para niños recién nacidos hasta la edad de tres años, comuníquese con su proveedor directamente.

<h2> Visit to confirm = Verificar su visita </h2>

Una vez obtenido el puesto preliminar, usted será asignado a su proveedor o un Centro de Recursos para proporcionarle información adicional el cual podría confirmar su puesto.  Le recomendamos llamar a su centro asignado para el material necesario y el horario adecuado para la entrevista.

Una vez que su puesto sea confirmado usted recibirá información adicional necesaria para completar su solicitud y empezar el programa.  Por favor comuníquele a su proveedor si necesita un puesto de inmediato o si está interesado(a) en el programa del próximo año. Estas dos opciones podrían estar disponibles.

Si su hijo(a) o la familia está atravesando por una situación de vivienda temporal, en un refugio o compartiendo la vivienda con otra familia, usted no necesitará proporcionar ningún documento. Proveyendo información falsa sobre este asunto podría ser la causa para la pérdida del puesto.

Si usted está buscando para inscribir a su hijo(a) en un programa desde el nacimiento hasta la edad de tres años o prefiere servicios de visitas a domicilio, por favor póngase en contacto con su preferido proveedor de servicios preescolares, o a la Línea de Aprendizaje Temprano de Chicago en (312) 229-1690 para asistencia.

-------------- 

**Note: Later, we will need to relink to the Spanish FAQs for List of Family Resource Center.**

**Comment by smarziano** [comment]
<h1> Parent Information</h1>
https://chicagoearlylearning.org/families

The header text "Parent Information" should be "Información para los padres"

<h2> Learn. Grow. Succeed! = Aprender. Crecer. ¡Triunfar! </h2>
La ciudad de Chicago se dedica a asegurarse de que cada uno de nuestros niños en todos los vecindarios, tengan acceso a una educación de calidad que empieza en los primeros años. No importa qué necesidades tenga la familia, la ciudad y sus afiliados se enfocan en proveer un programa de enseñanza para niños de temprana edad que sea seguro y de alta calidad, creando una base para los logros de ellos(a) en su futuro académico y profesional.

<h2> Benefits of Early Learning = Beneficios de enseñanza temprana </h2>
Programas de enseñanza a temprana edad activa a su hijo(a) mientras pasan por la etapa más importante de desarrollar las habilidades que serán la base de sus éxitos en años escolares y más adelante.  Actividades en la enseñanza a temprana edad están diseñadas a mantener el desarrollo físico, intelectual, social y capacidad emocional. A través de juegos y actividades estructuradas con sus pares, los niños estarán mejorando su uso y el entendimiento de los números, relaciones, lenguajes y control emocional.

Niños que han participado en enseñanza y actividades de temprana edad no solamente tienen una buena preparación para entrar al Kínder, tendrán un éxito asegurado al culminar su escuela secundaria, logrando obtener un ingreso salarial más alto en el futuro, acorde con el potencial de sus profesiones para alcanzar sus metas como adulto.

<h2> Explanation of Different Programs Offered = Explicación de los diferentes programas ofrecidos </h2>
Diferentes programas sirven a niños de diferentes edades y son financiados en una variedad de maneras. Muchos centros ofrecen más de un tipo de programa. Las descripciones a continuación le ayudarán a entender las diferencias generales entre los programas.

Mientras que la educación de temprana edad es importante para el desarrollo saludable de cada niño, cada familia tiene diferentes necesidades. Es necesario seleccionar el programa que más se adapte a sus necesidades de presupuesto, horarios, y que proporciona un ambiente seguro y estimulante para su hijo(a). Le aconsejamos llamar y visitar cada centro que le interese para decidir cuál sería el programa que más le convendría.

<h3> Preschool = Pre-escuela </h3>
Este programa ofrece actividades de desarrollo de la infancia y principios educativos que promueven la preparación escolar de los niños de tres a cinco años de edad de familias de bajos ingresos. Estos programas también pueden incluir servicios gratuitos de salud médica, dental y de salud mental y comidas nutritivas, como también educación y entrenamiento para los padres. Estos programas también pueden ser conocidos como Head Start o Pre School For All, dependiendo en la financiación y los servicios prestados. Los programas ofrecidos pueden ser de medio día o día completo.

<h3> Infant and Toddler Programs = Programas para niños y bebes </h3>
Este programa provee educación para el desarrollo en la temprana edad con actividades para niños (a) de recién nacidos hasta los tres años de edad para familias de bajos ingresos. Estos programas también pueden incluir servicios gratuitos de salud médica, dental y de salud mental y comidas nutritivas, como también educación y entrenamiento para los padres. Estos programas también pueden ser conocidos como Early Head Start, Prevention Initiative, o Early Intervention, dependiendo en la financiación y los servicios prestados.

Los programas de educación temprana de la ciudad de Chicago están disponibles en una serie de situaciones diferentes:

- **Chicago Public Schools (CPS)**: Las escuelas primarias en el distrito de Escuelas Públicas de Chicago ofrecen programas de educación temprana a niños de tres a cuatro años de edad.
- **Organizaciones de servicios la comunidad**: ofrecen educación temprana para niños recién nacidos a los cinco años de edad en la preparación para el Kínder (horario puede variar). Los niños en centros de cuidado de niños reciben un programa educativo mejorado. Estos programas están dirigidos a padres de bajos y moderados ingresos.
- **Visitas a su residencia**: visitas de personas entrenadas para ofrecer asistencia a los niños(a) en su propio hogar. Estos les proveerán educación y desarrollos educativos para promover una buena preparación educativa para niños recién nacidos hasta los tres años para familias con bajos ingresos.

<h2> Tips for Choosing a Great Program for Your Child = Consejos de cómo elegir el mejor programa para su hijo (a) </h2>

No se necesita un conocimiento especial para ser capaz de identificar un programa preescolar de alta calidad. Verá usted claramente los signos:

- Maestros y personal que son educados y atentos
- Maestros que hablan a los niños a nivel del ojo y hablan directamente a bebés y niños pequeños
- Maestros que demuestran afecto hacia los niños (cargándolos y abrazándolos)
- Un ambiente seguro, saludable y amistoso para niños
- Salones bien equipados con materiales y juguetes accesibles, y ubicados a la altura de la vista de los niños
- Actividades y rutinas adecuadamente estructurados
- Participación de los niños con las actividades
- Los niños reciben comidas (desayuno y almuerzo) también pueden tener siesta
- Hay actividades individuales y en grupos pequeños y grandes
- Una rutina diaria
- Uso de espacios fuera y dentro
- Actividades apropiadas (a la edad) de lenguaje, literatura, matemáticas, ciencia, el arte, la música, el movimiento y el juego dramático
- Juegos independientes
- Visitantes son bienvenidos con el permiso de los padres
- Lavado frecuente de las manos de los adultos y niños
- Intercambio de información entre los maestros y las familias acerca del desarrollo y
el progreso de aprendizaje del niño
- Los maestros con títulos de cuatro años y con entrenamiento en educación infantil
- Un máximo de 8 bebés y niños pequeños en un salón o un máximo de 20 niños en edad preescolar en un salón
- No menos de un maestro en un salón por cada bebe menos de tres años
- No menos de un maestro en un salón por cada diez niños de tres a cinco años

Para más información visite: [http://www.ounceofprevention.org/news/characteristics-of-quality-early-learning.php](http://www.ounceofprevention.org/news/characteristics-of-quality-early-learning.php)

Sería una buena idea hacer una cita para visitar y reunirse con los empleados del programa. Muchos padres les ayuda escribir una lista de preguntas antes de llamar o visitar el programa preescolar. Aquí están algunas sugerencias de preguntas, además de sus propias preguntas:

- ¿Qué hará mi hijo cada día? 
- ¿Qué hace qué su programa sea especial? 
- ¿Cómo participan los padres? 
- ¿Por cuánto tiempo ha estado este programa preescolar abierto? 
- ¿Qué tipo de acreditaciones o certificaciones tienen usted y su personal?
- ¿Puedo ser voluntario y visitar la clase de mi hijo?
- ¿Cómo le puedo ayudar a mi hijo(a) en este programa? 
- ¿Cómo puedo inscribir a mi hijo(a)?
- ¿Tendré que pagar algo? 
- ¿Cuáles son los criterios de elegibilidad para este programa?
- ¿Cuál será el horario de entrada y salida? 
- ¿Qué tipo de información o documentos se necesitan para inscribir a mi hijo(a) (certificado de nacimiento, libro de vacunas, etc.)?
- ¿Necesita mi hijo(a) un examen físico antes de matricularlo?
- ¿Hay alguna lista de espera para este programa? ¿Y si lo hay, qué tiempo toma? 
- ¿Habrá algún costo adicional qué se necesite saber?
- ¿Existe algún requisito para involucrar a padres y familias? ¿Y cuáles serían? 
- ¿Necesito tener un trabajo para poder inscribir a mi hijo(a) en este programa? 
- ¿Cuáles son las normas de asistencia?
- ¿Cuáles días o semanas estará cerrada el programa?

**Comment by smarziano** [comment]
<h1> City Resources </h1>

https://chicagoearlylearning.org/city-resources
Header text: City Resources = Recursos de la ciudad

La ciudad de Chicago, y el alcalde Rahm Emanuel, está comprometido a traer alta calidad a la enseñanza temprana. Además de programas para los niños en las escuelas y en agencias comunitarias, hay una serie de oportunidades para comenzar a estimular a su hijo en el aprendizaje temprano y otros entornos. 

<h2> Chicago Park District </h2>
Muchos parques ofrecen clases de recreo para la enseñanza de primera edad. Participantes de enseñanza temprana tienen oportunidad de fomentar el arte de escuchar de socializar a través de los programas se educación. [Visite la página de internet de los parques de chicago](http://www.chicagoparkdistrict.com/) para encontrar y matricularse para clases cerca a ud.

<h2> Chicago City of Learning </h2>
Chicago City of Learning (CCOL) es una iniciativa innovadora que une a las oportunidades de aprendizaje para a los jóvenes de una manera que les permite pensar, perseguir, y desarrollar sus intereses. [Visita CCOL](https://chicagocityoflearning.org/) para encontrar oportunidades cerca de usted.

</h2> Chicago Public Library (CPL) </h2>
La Biblioteca Pública de Chicago o CPL tiene muchas oportunidades para los niños que incluyen espacios para la educación temprana y leyenda de libros para niños menos de cinco años. CPL también cuenta con unidades móviles que traen programas de STEAM (ciencia, tecnología, ingeniería, artes y matemáticas) actividades de aprendizaje para niños pequeños junto con la programación de educación familiar facilitado por los bibliotecarios de toda la ciudad. El CPL tiene tres unidades móviles con kits de aprendizaje basadas en STEAM desplegados por toda la ciudad. [Póngase en contacto con CPL](http://www.chipublib.org/) para más detalles.

<h2> Tinkering Lab at Chicago Children's Museum </h2> 
El Museo Infantil de Chicago tiene disponible una serie de espacios de aprendizaje temprano para apoyar jugar con aprendizaje. Una exposición permanente, The Tinkering Lab, cuenta con un rincón de aprendizaje temprano. El museo infantil también se compromete para traer espacios de enseñanza temprana para otros sitios de la ciudad. [Póngase en contacto con el Museo Infantil de Chicago](http://www.chicagochildrensmuseum.org/) para más detalles.

<h2> Chicago Department of Public Health </h2>
La base para el aprendizaje temprano y éxito de un niño comienza con la salud materna e infantil. Las clínicas vendarías del Departamento de Salud Pública de Chicago ofrecen atención para las mujeres embarazadas y servicios de bienestar para los niños. [Póngase en contacto con el Departamento de Salud Pública de Chicago](http://www.cityofchicago.org/city/en/depts/cdph.html) para más detalles.

-------------------------------
**Note: I left the names of the organizations in English since the Spanish translation file had half in English and half in Spanish. Keeping the names in English will maintain consistency and the Spanish translation for that name is in every blurb which should avoid confusion.**

**Comment by smarziano** [comment]
FAQs have been added in Spanish. We are just waiting on the City of Chicago blurb for the About page.

**Comment by theandrewbriggs** [comment]
Add Connect4Tots block on City Resources page (#714) to list needing translations.

**Comment by smarziano** [comment]
Connect4Tots translation (issue #174)
-----------------------

Connect4Tots es un servicio de mensajes de texto para padres y tutores de bebés entre 1 y 3 años de edad. Los padres y tutores que se registren recibirán de 2 a 3 mensajes de texto cada semana, con información acerca del desarrollo y crecimiento de sus niños, así como la salud, la educación, los servicios públicos y eventos en la ciudad de Chicago.
 
**Para registrarse, los padres y tutores deben enviar el mensaje de texto TOPTOPT7 al 311311 o usar este formulario en línea.**
 
En el momento del registro, se le pedirá que especifique el sexo y la fecha de nacimiento del niño, su dirección en la ciudad y el idioma en que prefiere que le envíen los mensajes. Una vez registrado, recibirá automáticamente de 2 a 3 mensajes por semana con orientación y consejos útiles.
 
Se pueden aplicar tarifas estándares de mensajes de texto.
 
**Información adicional**
 
Connect4Tots cuenta con el patrocinio de la ciudad de Chicago y Urban Labs de la Universidad de Chicago. Este centro evaluará los efectos del programa mediante el análisis del uso que hacen los participantes de la información y los recursos incluidos en los mensajes de texto. Para obtener más información sobre el programa, puede comunicarse con Urban Labs a través de Connect4Tots es un servicio de mensajes de texto para padres y tutores de bebés entre 1 y 3 años de edad. Los padres y tutores que se registren recibirán de 2 a 3 mensajes de texto cada semana, con información acerca del desarrollo y crecimiento de sus niños, así como la salud, la educación, los servicios públicos y eventos en la ciudad de Chicago.
 
Para registrarse, los padres y tutores deben enviar el mensaje de texto TOPTOPT7 al 311311 o usar este formulario en línea.
 
En el momento del registro, se le pedirá que especifique el sexo y la fecha de nacimiento del niño, su dirección en la ciudad y el idioma en que prefiere que le envíen los mensajes. Una vez registrado, recibirá automáticamente de 2 a 3 mensajes por semana con orientación y consejos útiles.
 
Se pueden aplicar tarifas estándares de mensajes de texto.
 
Información adicional
 
Connect4Tots cuenta con el patrocinio de la ciudad de Chicago y Urban Labs de la Universidad de Chicago. Este centro evaluará los efectos del programa mediante el análisis del uso que hacen los participantes de la información y los recursos incluidos en los mensajes de texto. Para obtener más información sobre el programa, puede comunicarse con Urban Labs a través de Connect4TotsFeedback@cityofchicago.org.

**Comment by smarziano** [comment]
The City of Chicago blurb on the about page: https://chicagoearlylearning.org/about still requires a translation and has not been changed from last year. This is not a priority translation for May 15. Therefore, I will move this to our next phase of work.

**Comment by smarziano** [comment]
I'm closing this issue since we did an audit and translation of all pages. I will create new issues related to the appropriate sections of the website.
