### ISSUE TITLE
Mobile: QRIS ratings are missing from list view 

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#682]
When viewing the list of centers on a mobile device, the QRIS ratings are not appearing. We should add them for consistency between mobile and desktop.

**Comment by theandrewbriggs** [comment]
QRIS icons were set to `display: none` in the responsive style file before the redesign, and turning them back on doesn't really work. We'll reconsider the list display when redesigning the mobile site.

![screen shot 2016-07-14 at 16 23 10 pm](https://cloud.githubusercontent.com/assets/3439795/16856440/a7cdf68c-49df-11e6-9f58-5f9cc68e6434.png)

**Comment by smarziano** [comment]
I agree that we need to focus more energy on this. Therefore, I am moving this to the next milestone that relates to improving map code and mobile.

**Comment by smarziano** [comment]
I am closing this issue because we are going to be completely redesigning this list view and this is not something we are adding to the list search results view.
