### ISSUE TITLE
Mobile: Include a condensed legend to show availability levels

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#686]
I am adding this in the Phase 1 Clean-up milestone because it is a priority item, but imagine that it might be part of the Improve Map Code milestone: https://github.com/smartchicago/chicago-early-learning/milestone/19

While there is not enough space on the map to show the full legend, an important addition would be to clarify the color coding of centers based on availability level. I imagine a small legend bar at the bottom of the map page could show the seat availability color bar.

**Comment by theandrewbriggs** [comment]
We've decided to punt on this issue; this will be addressed by mobile redesigns.

**Comment by smarziano** [comment]
Closing this issue. We will focus on a larger mobile redesign outlined in this milestone: https://github.com/smartchicago/chicago-early-learning/milestone/19
