### ISSUE TITLE
Mobile: Lead to list view after user searches by address/community area/zip code

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#693]
Currently, on our mobile site parents are led to a map view after they search by address, community area, or zip code. We have faced difficulties with the map view:
- Sharing the information about the symbology of the map markers without a legend (and space management with a legend!)
- Loading map markers as parents move around the map, especially on slower connections
- Opening up the pop-up information on the map
- Providing clear instructions of adding locations to their Compare & Apply list

We think that through the list view we will have an easier time giving parents this important information and clear action steps.

Therefore, once parents search by address they will be led to a page with a map that confirms that their address search was correct and then lists locations by distance from that marker (#514).

**Comment by smarziano** [comment]
Here is what is currently on staging:
![img_8237](https://user-images.githubusercontent.com/5550969/29877659-db6e56b0-8d65-11e7-89c1-87c18a80a603.PNG)

Changes that need to be made:
- [ ] Update CPS-based and Community-based icons (@amynicole #890)
- [ ] Change text from "Vew Map" button to "View on Map" button
- [ ] Switch location of "View on Map" and "Compare" buttons 
- [ ] Add "Refine Search" link under the search statement
- [ ] Check/update "See more options" button size @amynicole 
- [ ] Incorporate additional filters in search statement (https://github.com/smartchicago/chicago-early-learning/issues/889#issuecomment-325998977)

**Comment by amynicole** [comment]
The "see more options" button in staging is fine. It looks like we're using the shorter buttons on this page to make them fit better. It makes sense to keep them all uniform on this page.
