### ISSUE TITLE
Indicate that seat availability is subject to eligibility

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#704]
Parents have expressed to Early Learning specialists that our the representation of seat availability is misleading because placement is assigned based on need and there are eligibility requirements within the application process. Parents think there is a seat available at a location but then are waitlisted.

We need to add a note that availability is "subject to eligibility." A couple of thoughts: 
- Add a note to the map legend
- Add a note to the center detail pages
- Add a new FAQs

@theandrewbriggs any thoughts on this? I am going to edit the map legend (both English and Spanish) to get rolling on these changes. I'll also provide you some language around the center detail pages. I'm open to suggestions to make this as clear as possible for parents.

**Comment by smarziano** [comment]
@theandrewbriggs Here are the new versions of map key in English & Spanish

![map_key_v2](https://cloud.githubusercontent.com/assets/5550969/17534888/20eb492c-5e51-11e6-85fc-7607887a3069.png)

![map_key_es_v2](https://cloud.githubusercontent.com/assets/5550969/17534887/18b25f16-5e51-11e6-9327-aedc8981a560.png)

**Comment by theandrewbriggs** [comment]
@smarziano The line in the spanish legend is misaligned

**Comment by theandrewbriggs** [comment]
New legends have been added, as well as disclaimer text in both the location detail pages and the starred location lists.

**Comment by smarziano** [comment]
I find the "subject to eligibility" text to be a little too small on staging (English version):
<img width="1261" alt="screen shot 2016-08-16 at 3 53 11 pm" src="https://cloud.githubusercontent.com/assets/5550969/17715424/9f2f1390-63c9-11e6-8c70-a97d27a1931b.png">

I increased the font size, please see if this works better, @theandrewbriggs:
![map_key_v3](https://cloud.githubusercontent.com/assets/5550969/17715469/d3a8eccc-63c9-11e6-952f-0911af374c79.png)

**Comment by smarziano** [comment]
We added a note on the center detail pages, the /starred page, and the map legend. We are also planning to get additional content on the FAQs page. As for now, this issue is closed.
