### ISSUE TITLE
Add Connect4Tots Information to City Resource page

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#714]
@theandrewbriggs Please add the following information to the /city-resources page.

----------------------

<h2>Connect4Tots</h2>
Connect4Tots is a text-message service for parents and guardians of toddlers ages 1 to 3. Parents and guardians who enroll will receive 2-3 text messages each week with information on their child’s growth and development as well as connections to health, education, public service, and event resources in the City of Chicago. 
 
To enroll, parents and guardians should text TOPTOPT7 to 311311.
 
Connect4Tots is sponsored by the City of Chicago and University of Chicago Urban Labs. Its purpose is to connect Chicago-area parents/guardians of children ages 1 to 3 with evidenced-based information on their child’s developmental milestones and connect them to Chicago-area resources, such as vaccinations and free clinics, public assistance enrollment services, age-appropriate events, and early learning resources. 
 
Urban Labs will evaluate the effects of the program by analyzing participants’ use of the information and resources included in the text messages. For more information on the program, please contact Urban Labs at Connect4TotsFeedback@cityofchicago.org.

----------------- 
Here is a copy of the logo: https://www.dropbox.com/s/2y6kiuvnxb7tiym/91-100%20ConnectForTots_Logo_Selected%20for%20fianl%20approval_07152016.pdf?dl=0

**Comment by theandrewbriggs** [comment]
@smarziano I can't use the attached .pdf for the logo, it'll need to be an image format like .jpg or .png.

**Comment by smarziano** [comment]
@theandrewbriggs I always forget this. Here's the file in .png format:
![91-100 connectfortots_logo_selected for fianl approval_07152016](https://cloud.githubusercontent.com/assets/5550969/17713928/0e587178-63c3-11e6-9499-119716f825cf.png)

**Comment by smarziano** [comment]
This is now live, closing issue.

<img width="1060" alt="screen shot 2016-08-17 at 5 52 01 pm" src="https://cloud.githubusercontent.com/assets/5550969/17756082/57c26612-64a3-11e6-8cb5-d95afd5c8507.png">

**Comment by smarziano** [comment]
@theandrewbriggs I need the information to be updated to use this text instead. It was edited and I previously missed the updated version when creating this issue.

-----------------------------

Connect4Tots is a text-message service for parents and guardians of toddlers ages 1 to 3. Parents and guardians who enroll will receive 2-3 text messages each week with information about their child’s growth and development, as well as connections to health, education, public service, and event resources in the City of Chicago.
 
**To enroll, parents and guardians should text TOPTOPT7 to 311311 or use this [online form](http://chitot.cityofchicago.org/demo/C4KSubscriptionForm.jsp).** 
 
At the time that you enroll, you will be asked to provide your child’s date of birth and sex, your city address, and your preferred language to receive texts. Once enrolled, you will automatically receive 2-3 messages per week with helpful guidance and tips.
 
Standard text messaging rates may apply.
 
**Additional Information**
 
Connect4Tots is sponsored by the City of Chicago and the University of Chicago Urban Labs. The Urban Labs will evaluate the effects of the program by analyzing participants’ use of the information and resources included in the text messages. For more information on the program, please contact Urban Labs at C4TotsFeedback@cityofchicago.org

**Comment by smarziano** [comment]
New information is now live with commit https://github.com/smartchicago/chicago-early-learning/commit/e4037a88833737a3bb206a09483763023999a86f

We are still waiting on Spanish translations, #680.
