### ISSUE TITLE
Update "Apply Now" language to indicate for current school year only

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#729]
Our partners would like to make a few small text changes to the Chicago Early Learning portal to indicate that applications are currently only being accepted for this current school year.

When "Apply now" or "Apply" is written our partners would like to see this note:
“Please note:  applications are being accepted for the current school year only.  The application for Fall 2017 will be available in Spring 2017”

**Translation:** Por favor note lo siguiente: Las solicitudes para programas pre-escolares atreves de esta página web sólo se están aceptando para el año escolar en curso. Las solicitudes para programas pre-escolares del otoño de 2017 estarán disponibles atreves de esta página web en la primavera de 2017.

Site locations for these text changes:
- Homepage in the “splash text” box on the header image https://chicagoearlylearning.org/
- Text under “Apply Today” bucket on the homepage https://chicagoearlylearning.org/
- FAQs: https://chicagoearlylearning.org/faq#how-do-i-apply-to-a-program
- Compare & Apply page: https://chicagoearlylearning.org/starred/
- Text under “Apply” https://chicagoearlylearning.org/how-to-apply

**Comment by theandrewbriggs** [comment]
This is done and live on production.

Some of the placements of the note may need to be adjusted. The FAQ had to be updated separately in the Django Admin tool.

**Comment by smarziano** [comment]
This looks good! Thanks for updating the FAQ, too.

Closing this issue.
