### ISSUE TITLE
Update application links to COPA parent application

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#731]
In preparation for the new early learning application period, we need to update all of the links from the old ECM parent application to the new COPA parent application. Here is a list of current locations on the Chicago Early Learning portal. 
- [x] "Apply now!" link in the navigation bar
- [x] "Fill out an application online »" in the "Apply Today" text bucket on the homepage
- [x] FAQ: How do I apply to a program?
- [x] FAQ: Do I need to apply online?
- [x] "2. Submit an application online" on /how-to-apply page
- [x] "Visit the online application site" on /how-to-apply page
- [x] "Click here to fill out an application for two preferred sites or call the Chicago Early Learning Hotline at (312) 229-1690 for assistance." on location detail page (example: https://chicagoearlylearning.org/location/533/salvation-army-new-moms/)
- [x] "Apply" on /starred page

**Comment by theandrewbriggs** [comment]
All but FAQs are updated to COPA production URL on staging. FAQs need to be edited in production admin panel
