### ISSUE TITLE
Create new "Get the Word Out" page

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#733]
Our partners are interested in creating a new "Get the Word Out" page that will provide outreach information for ~~parents and parent advocates~~ external partners. 

**Components include:**
- Community events calendar: thinking that this will be a Google calendar controlled by City staff that we embed on this page
- Outreach team's contact information
- Downloadable and shareable Facebook/Instagram posts

**Requirements:**
- [x] Create new page; url possibly /outreach
- [x] Embed code for the Google calendar
- [x] Collect text content
- [x] Compile links to social media posts and flyers

~~We expect to add a link to this page on the footer.~~

**Comment by smarziano** [comment]
There has been a change in the purpose of this page, which I highlighted above. This page will provide outreach materials to external organizations who work with children/families. 

There should be a message at the top of this page (pop-up?) for parents to direct them to the Chicago Early Learning homepage if they end up on this page.

**Comment by smarziano** [comment]
URL should be /outreach

Embed code for Google calendar: 
```
<iframe src="https://calendar.google.com/calendar/embed?src=6nfr2okcbal0reqhfdfn0nvbd4%40group.calendar.google.com&ctz=America/Chicago" style="border: 0" width="800" height="600" frameborder="0" scrolling="no"></iframe>
```

**Comment by smarziano** [comment]
On this page, our partners want to add a data dashboard to showcase number of new applications, website clicks, outreach events, etc. The plan is that our City partners would use Tableau and we would embed the dashboard onto this page. 

**Resources:**
https://onlinehelp.tableau.com/current/server/en-us/embed.htm
https://onlinehelp.tableau.com/current/server/en-us/embed_dashboard.htm

**Comment by smarziano** [comment]
Update re: my last comment– we will be wait to embed the Tableau dashboard until the Redesign launch later this summer. Our partners did not want to share this now because there won't be data at first to share. The rest of this page should be built out as planned.

Text to add (specifically under the Google calendar):

- "Do you need specific materials for outreach at your site, school, or headquarters? [Fill out a request form](https://docs.google.com/forms/d/e/1FAIpQLSdZOG2UtlyQzX8kYMHzH9A3-m-ibYKSiTpFGAvXkAMJc8tlYA/viewform)." 
- "Share results from a preschool application outreach effort, such as door knocking, tabling, or manning a booth at a location around the city. [Fill out this form](https://docs.google.com/forms/d/e/1FAIpQLSf3-Pc7X8IQOkTuql58_x1XD3YT44SAUgtYUkTv7bykbuX8Xw/viewform).

**Comment by smarziano** [comment]
# Outreach 2017
Thank you for helping spread the word about enrolling 3 and 4 year olds in early learning programs across Chicago. With **your help,** we will **enroll more children** than ever before, especially our highest need families.

Here you will find social media links, talking points, and outreach resources to help share information with Chicago families.


## Upcoming Outreach Events
[Insert Google calendar]
`<iframe src="https://calendar.google.com/calendar/embed?src=6nfr2okcbal0reqhfdfn0nvbd4%40group.calendar.google.com&ctz=America/Chicago" style="border: 0" width="800" height="600" frameborder="0" scrolling="no"></iframe>
`
Do you need specific materials for outreach at your site, school, or headquarters?[ Fill out a request form](https://docs.google.com/forms/d/e/1FAIpQLSdZOG2UtlyQzX8kYMHzH9A3-m-ibYKSiTpFGAvXkAMJc8tlYA/viewform).

Share results from a preschool application outreach effort, such as door knocking, tabling, or manning a booth at a location around the city. [Fill out this form](https://docs.google.com/forms/d/e/1FAIpQLSf3-Pc7X8IQOkTuql58_x1XD3YT44SAUgtYUkTv7bykbuX8Xw/viewform).

## Outreach Toolkits

### Show
[Insert brief text description of flyer] [download symbol]
[Add image of flyer as an example]

### Tell
Tell families about Chicago Early Learning. Here are some talking points you can share with your families:

<p align="center">The Chicago Early Learning online preschool application is now open! Follow these easy steps to get your child enrolled in preschool: </p>

**Step 1)** Visit ChicagoEarlyLearning.org to create an online account for your family
**Step 2)** Fill in information on your family, such as employment and income, information on your child, and then apply for your top choice preschool site
**Step 3)** If your child qualifies, you will receive an email on June 1st with information on how to verify your child's preschool seat

<p align="center">See you for the first day of school in September! </p>

<p align = "center"> If you have questions, please visit ChicagoEarlyLearning.org, or call the Chicago Early Learning Hotline: 312-229-1690  </p>

There are also great resources on ChicagoEarlyLearning.org:

- Visit the [FAQs page](https://chicagoearlylearning.org/faq) to get answers to common questions
- Tell parents about the [beneifts of early learning](https://chicagoearlylearning.org/families)

### Share

Share the news with families on social media. Use any of these captions below on Facebook, Twitter, Instagram, Snapchat or more:

- The Chicago Early Learning preschool application is now open! Parents looking for quality preschool programs for 3 and 4 year olds in the fall can register today! #chicagoearlylearning 
- Are you a parent of a 3 or 4 year old? Don't miss out on early access to over 600 preschool programs throughout the city for next school year. Apply today. Start in September! #chicagoearlylearning 
- With over 600 options throughout the city let us help you find the best match for your 3 and 4 year old. Get started at chicagoearlylearning.org #chicagoearlylearning 
- **OR** create your own caption on social media! Just don't forget to use #468 

Download these images to add to your social media messages:
[Image 1]                                         [Image 2]
[Download symbol]                        [Download symbol]

**Comment by smarziano** [comment]
Images for the social media piece on this page:
![cel-social1](https://cloud.githubusercontent.com/assets/5550969/25968608/c517232a-3657-11e7-9ddb-f793cfbf2215.jpg)
![cel-social2](https://cloud.githubusercontent.com/assets/5550969/25968609/c519378c-3657-11e7-82f0-184cdc6886bd.jpg)

**Comment by smarziano** [comment]
Update from partners is that they do not want to show the outreach calendar until after enrollment period has started. They would like to collect more information about events happening. 

The other pieces (Show/Tell/Share) should be added for May 15 launch. We are still waiting for content.

I will create a separate issue to include dashboard and calendar for the next phase of work.

**Comment by theandrewbriggs** [comment]
Primer on Facebook and Twitter Cards: https://css-tricks.com/essential-meta-tags-social-media/

**Comment by smarziano** [comment]
![marycrane5](https://cloud.githubusercontent.com/assets/5550969/26029836/a94c015c-3804-11e7-9fae-60f2b5cbf009.jpg)

I think this is a cute photo for the outreach page.

**Comment by smarziano** [comment]
@theandrewbriggs I would move forward with creating this page as outlined in the above comment https://github.com/smartchicago/chicago-early-learning/issues/733#issuecomment-300887173 just without the "Show" piece since I have not heard back about the flyers.

**Comment by smarziano** [comment]
@theandrewbriggs Two changes I would make to this page and I think it'll be ready to go:

Either center or align to the left these phrases: 
"The Chicago Early Learning online preschool application is now open! Follow these easy steps to get your child enrolled in preschool:"
"See you for the first day of school in September!"
"If you have questions, please visit ChicagoEarlyLearning.org, or call the Chicago Early Learning Hotline: 312-229-1690"

The of alignment of the steps 1, 2, 3 is great as it is. 

Can we easily create a way for people to click a link and download the social media images?

**Comment by smarziano** [comment]
More work to come via #758 & #759, but this is done now.
