### ISSUE TITLE
Redirect from ECM application system to placeholder

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#745]
As we approach a transitional period before the new application period begins, we want to redirect from the apply. subdomain (which leads to the ECM application), to a placeholder page. 

Here are some of the steps involved:
- [x] Create a new page with a URL like /announcement
- [x] Styling could match an informational page like /city-resources to keep it simple
- [x] Add an image to this page. I like this one:
![theresa13](https://cloud.githubusercontent.com/assets/5550969/25625858/4acf1dba-2f23-11e7-9670-7d8238735d6e.jpg)
- [x] Add text (in English):

> Are you looking for preschool for your 3 or 4 year old starting in the fall?
> 
> Chicago Early Learning Preschool Applications open May 15th for the 2017 – 2018 school year!
> 	
> Chicago Early Learning supports Chicago families looking for early learning at community sites and schools across the city. 
> 
> For immediate enrollment before the fall, please call 773-553-2010, or call the community site you would like your child to attend.
> 
> For any other questions, please call the Chicago Early Learning Hotline: 312-229-1690

Note: the top two sentences are the main pieces of the information so may sure those are bold, big, highlighted on page. Link telephone numbers.

- [x] Add text in Spanish (still waiting for copy)
- [x] Change all locations that direct users to ECM to this /announcement page. See #731 for a list of links that require updating.

**Comment by smarziano** [comment]
Here is the Spanish translation:

> ¿Está buscando los programas de aprendizaje temprano para su hijo de 3 o 4 años empezando en el otoño?
> 
> La aplicación de Educación Temprana de Chicago estará disponible el 15 de mayo para el año escolar 2017 a 2018. 
> 
> Educación Temprana de Chicago apoya a las familias de Chicago quienes quieren la educación temprana en los sitios de la comunidad, y en las escuelas públicas por toda la ciudad.
> 
> Para la inscripción inmediata antes del otoño, llame a 773-553-2010, o llame al sitio de la comunidad a lo que quiere que asista su hijo. 
> 
> Para otras preguntas, por favor llame a nuestra línea directa para el apoyo familiar: 312-229-1690. 
>

**Comment by theandrewbriggs** [comment]
5/6 addressed in new branch `static`, yet to be pushed to staging site.

**Comment by theandrewbriggs** [comment]
Old ECM urls removed in `static` branch.

**Comment by theandrewbriggs** [comment]
Now live on staging: https://staging.chicagoearlylearning.org/announcements

**Comment by smarziano** [comment]
Reformat text to be bolder/more announcement-y, especially the first two lines. Center the text. Bold May 15.

## Are you looking for preschool for your 3 or 4 year-old starting in the fall?

### Chicago Early Learning Preschool Applications open **May 15th** for the 2017 – 2018 school year!

**Comment by theandrewbriggs** [comment]
This is now live on production: https://chicagoearlylearning.org/announcements

**Comment by smarziano** [comment]
This page is currently not mobile responsive.

**Comment by smarziano** [comment]
Mobile responsive with commit https://github.com/smartchicago/chicago-early-learning/commit/870454227a47e487ec94b84153f7a5a29626a6e0

This is now complete. Closing!
