### ISSUE TITLE
Update Connect4Tots information on /city-resources page

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#746]
Our partners have requested that the Connect4Tots information on the /city-resources page is updated. @theandrewbriggs I would prefer to show it on staging first because they are concerned about it being too much text on this page. 

English Version:

> 
> Connect4Tots provides text messages on FREE resources for parents and guardians of toddlers ages 1 to 3. Connect4Tots parents and guardians receive 2-3 text messages weekly with information about child’s growth and development, connections to health & safety, education, public service, event resources in the City of Chicago, and more!
> 
> ### Sign Up Today!
> 
> **Text TOTOPT7 to 311311 or directly through [our online form](chitot.org/enroll).**  
> 
> When you enroll, you will be asked to provide your child’s date of birth and sex, your city address, and your preferred language (English, Spanish, or Polish) to receive texts. Once enrolled, you will automatically receive 2-3 messages per week with helpful guidance and tips.
> 
> Standard text messaging rates may apply.
> 
> ### Tell your Chicago Friends!
> All you already a Connect4Tots parent? Let your other Chicago friends who are parents of toddlers know so they can get important text messages on FREE resources for those who qualify.
> 
> ### Additional Information
> 
> Connect4Tots is sponsored by the City of Chicago and the University of Chicago Urban Labs. Urban Labs will evaluate the effects of the program by analyzing participants’ use of the information and resources included in the text messages. Please review [our consent](http://chitot.org/consent) for more information. For more information on the program, please contact Urban Labs at Connect4TotsFeedback@cityofchicago.org.

Spanish version:

> Connect4Tots proporciona mensajes de texto en recursos GRATUITOS para padres y tutores de niños de 1 a 3 años de edad. Los padres y tutores de Connect4Tots reciben de 2 a 3 mensajes de texto semanalmente con información sobre el crecimiento y desarrollo del niño, enlaces a servicios de salud y seguridad, educación, asistencia pública, recursos para eventos   en la ciudad de Chicago y más.
> 
>### ¡Inscríbase Hoy!
> 
> **Escriba TOTOPT7 en el 311311 o hágalo directamente en [este formulario en línea](chitot.org/enroll).** 
> 
> Al inscribirse se le pedirá que proporcione la fecha de nacimiento y sexo de su hijo, su dirección y el idioma de su preferencia (inglés, español o polaco) para recibir los mensajes de texto. Una vez inscrito, recibirá automáticamente de 2 a 3 mensajes por semana con asesoramiento y consejos útiles.
> 
> Se aplican tarifas estándar de mensajería de texto.
> 
>### ¡Cuéntele a sus amigos de Chicago!
> ¿Ya es un padre de Connect4Tots? Permita que sus amigos de Chicago que son padres de niños pequeños se enteren para que aquellos que cumplan con los requisitos, también puedan recibir mensajes de texto importantes en recursos gratuitos. 
> 
>### Información adicional
> 
> Connect4Tots es patrocinado por la Ciudad de Chicago y por University of Chicago Urban Labs. Urban Labs evaluará los efectos del programa al analizar el uso que hacen los participantes de la información y los recursos incluidos en los mensajes de texto. Por favor revise [nuestro consentimiento](http://chitot.org/consent) para obtener más información. Para más información sobre el programa, por favor contacte a Urban Labs en Connect4TotsFeedback@cityofchicago.org.

**Comment by theandrewbriggs** [comment]
@smarziano That "our consent" link is dead.

**Comment by theandrewbriggs** [comment]
Live on staging: staging.chicagoearlylearning.org/city-resources

**Comment by theandrewbriggs** [comment]
This is now live on production: https://chicagoearlylearning.org/announcements

**Comment by smarziano** [comment]
@theandrewbriggs It looks like this page is **not** mobile-responsive.

**Comment by smarziano** [comment]
@theandrewbriggs I think your last comment was meant for issue #745 or you meant to write https://chicagoearlylearning.org/city-resources

There is a broken link that exists, but our partners said they are working to fix this issue. I am going to close this issue. It might require reopening if we need to switch that link.
