### ISSUE TITLE
Update "Clear *all* Selections" button on /starred page

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#750]
This relates to updates via #740. Since we are utilizing checkboxes in the new /starred page design, one of our partners mentioned that she thought she could select the sites and then click "Clear selections" to remove only those sites she had checked. She did not expect that all of the sites would be cleared.

Therefore, we could either create that functionality so that a user can select a number sites and then only clear those. Or (and the easier option) is to change this button to say "Clear all selections" instead. 

<img width="1009" alt="screen shot 2017-05-09 at 2 10 51 pm" src="https://cloud.githubusercontent.com/assets/5550969/25868114/5e29d578-34c1-11e7-8d44-228a806f9c45.png">

**Comment by smarziano** [comment]
Spanish translation: "Borre todas las selecciones"

**Comment by theandrewbriggs** [comment]
@smarziano I used "Clear All Sites" instead of "Selections" because I think it's the word "selection" that's the problem - Can I get a translation for that?

**Comment by smarziano** [comment]
The translation for that would be "Borre todos los centros"
