### ISSUE TITLE
Update favicon to match other style changes

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#754]
2016 issue as FYI: #653 

Since we will be updating the logo I also want to update the favicon to match the style updates.

**Comment by amynicole** [comment]
[favicons (1).zip](https://github.com/smartchicago/chicago-early-learning/files/1005939/favicons.1.zip)

Favicon files, optimized for desktop, iOS, Android, and Windows mobile.

**Comment by smarziano** [comment]
This looks great, @amynicole! Assigning @theandrewbriggs because this is ready to be added to the site now.

**Comment by smarziano** [comment]
I think the yellow is way too light on desktop to see what it is. I can barely see the favicon. Maybe if it is without the blue-ish background (like the android option) we should make the pencil blue.

**Comment by amynicole** [comment]
[favicons (1).zip](https://github.com/smartchicago/chicago-early-learning/files/1022753/favicons.1.zip)

Here's an updated favicon with a blue pencil.

**Comment by smarziano** [comment]
Adding my comment here so it doesn't get lost in Slack– I’m also open to using the blue background with yellow pencil on desktop or this blue with the transparent option. I just can’t see the yellow with the transparent background.

**Comment by amynicole** [comment]
Got it! Here's the blue background!
![favicon-16x16](https://cloud.githubusercontent.com/assets/7504439/26370840/a9ee7826-3fbe-11e7-9884-238856093f60.png)
![favicon-32x32](https://cloud.githubusercontent.com/assets/7504439/26370839/a9eb769e-3fbe-11e7-8fda-c4f2b4c7e44c.png)

**Comment by amynicole** [comment]
Got it! Here's the blue background! Andrew, can we use the chrome and android files from the previous version?
[favicon blue background.zip](https://github.com/smartchicago/chicago-early-learning/files/1023387/favicon.blue.background.zip)

**Comment by smarziano** [comment]
<img width="282" alt="screen shot 2017-06-15 at 8 05 12 am" src="https://user-images.githubusercontent.com/5550969/27182593-6395227c-51a1-11e7-914e-c4431da8713c.png">
I just want to say that this looks so much better! Adding "Waiting on Merge" tag since this is up on staging.
