### ISSUE TITLE
Footer: Add Chicago Early Learning social media icons

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#755]
Our partners are going to be creating specific Chicago Early Learning social media accounts. We should plan to add the associated social media icons to the footer. Currently, the accounts have not been made yet, so I'm assigning this to myself.

**Comment by smarziano** [comment]
Staging:
<img width="993" alt="screen shot 2017-06-15 at 8 51 30 am" src="https://user-images.githubusercontent.com/5550969/27184462-dd7b67bc-51a7-11e7-8f6d-0de703d068f4.png">

I think it looks a little odd that these are stacked vertically. I wonder if it would be better horizontal either on the left-hand or right-hand corner under the footer text.

**Comment by theandrewbriggs** [comment]
@smarziano Here's the logos under the "Keep in touch" block
![screen shot 2017-06-15 at 20 11 00 pm](https://user-images.githubusercontent.com/3439795/27207781-ebf2d1c2-5206-11e7-9596-43706664882a.png)

**Comment by theandrewbriggs** [comment]
@smarziano Here they are under the left block:
![screen shot 2017-06-15 at 20 15 54 pm](https://user-images.githubusercontent.com/3439795/27207864-84e70f1a-5207-11e7-863f-b25192adc8ac.png)

**Comment by smarziano** [comment]
@theandrewbriggs I think the left-hand side works, but I just wonder if it will be better on the right-hand side when people view it on mobile so that it is all the way on the bottom of the page.
