### ISSUE TITLE
About: Hyperlink names of organizations 

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#760]
City of Chicago: https://www.cityofchicago.org/city/en.html
Chicago Public Schools: http://www.cps.edu/
Chicago Department of Family and Support Services: https://www.cityofchicago.org/city/en/depts/fss.html
Smart Chicago Collaborative: http://www.smartchicagocollaborative.org/

**Comment by theandrewbriggs** [comment]
Which links are these in reference to?

**Comment by theandrewbriggs** [comment]
Jk, about page, we talked about this yesterday
