### ISSUE TITLE
Line up links on homepage under text buckets

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#769]
It was suggested to me that the links below the text buckets line up horizontally.
<img width="906" alt="screen shot 2017-05-13 at 3 25 51 pm" src="https://cloud.githubusercontent.com/assets/5550969/26029001/7b9e3658-37f0-11e7-95b4-4b15cba81967.png">

**Comment by theandrewbriggs** [comment]
I can't really do this in a good way. I could, on the other hand, move the links above the body text?

**Comment by theandrewbriggs** [comment]
![screen shot 2017-05-13 at 18 59 21 pm](https://cloud.githubusercontent.com/assets/3439795/26030109/652bb684-380e-11e7-9d65-657890e5eaeb.png)

**Comment by smarziano** [comment]
After further discussion, we have decided not to do this because we prefer the links to go under the blurbs. Considering the text has changed, the blurb sizes have also changed and they are lined up more (but not perfectly) than before. I'm going to close this issue for now.
