### ISSUE TITLE
Location detail pages say September 1, 2016

### ISSUE THREAD

**Issue by shua123** [smartchicago/chicago-early-learning#781]
I think this should be 2017. Example: https://chicagoearlylearning.org/location/792/?
![image](https://cloud.githubusercontent.com/assets/1593537/26068865/97a9bc12-3964-11e7-8852-a9567947bc10.png)

**Comment by smarziano** [comment]
Updated on staging:
<img width="941" alt="screen shot 2017-05-23 at 7 24 28 am" src="https://cloud.githubusercontent.com/assets/5550969/26354111/e2131904-3f88-11e7-81ec-98fb73aaf757.png">

Waiting on merge!
