### ISSUE TITLE
Add promotional video to /outreach page

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#787]
Our partners are interested in adding this short video to the /outreach page: https://drive.google.com/file/d/0B3-ILi-hWe7WLWlzVWlqeDJjU0k/view

I'm assigning this to myself because I recommended that this is added on YouTube to make it easier to embed and share.

**Comment by smarziano** [comment]
The video has been added to YouTube:
https://www.youtube.com/watch?v=0-lS0ntMjHc&feature=youtu.be

Here is the embed code:
`<iframe width="560" height="315" src="https://www.youtube.com/embed/0-lS0ntMjHc" frameborder="0" allowfullscreen></iframe>`

This should be added on the "Share" section of the /outreach page.

**Comment by theandrewbriggs** [comment]
Is there any copy that goes along with this video? Should it go at the top of the Share section?
