### ISSUE TITLE
Add icons/visuals to different sections of the /outreach page

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#788]
Our partners requested that we add visual icons to this chicagoearlylearning.org/outreach page. I believe that this is to make each section "Show," "Tell," "Share," clear and defined on the page. I am interested in discussing how this page can work better because currently, it is a list of everything outreach-related on one page. 

Here are the types of icons that were suggested by our partners:
A push pin for the "Show" section which will be added via issue #786...
![push pin](https://cloud.githubusercontent.com/assets/5550969/26159761/0f3cdc06-3ae5-11e7-911a-66aff62d2d57.JPG)

a speech bubble for the "Tell" section...
![speech bubbles](https://cloud.githubusercontent.com/assets/5550969/26159783/21049f64-3ae5-11e7-8424-1fb958f03226.JPG)

...and social media icons for the "Share" section.
![social media](https://cloud.githubusercontent.com/assets/5550969/26159815/368ff93c-3ae5-11e7-931a-2523641abaa6.png)

**Comment by jenmakes** [comment]
Iconography could be a good way to highlight content, so I'll note this for a time we go back to this page specifically. Amy is currently focusing on fleshing out a site audit of everything to help us gage site needs from our perspective that we can all review - which notes addressing some of these visual items.

**Comment by amynicole** [comment]
@smarziano Is this issue still relevant, given the redesign of the outreach page?

**Comment by smarziano** [comment]
This will be implemented in a different way with the new designs seen here: https://github.com/smartchicago/chicago-early-learning/issues/789#issuecomment-307977170

I will close this issue.
