### ISSUE TITLE
Improve functionality and design of /outreach page

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#789]
Issues related to this task include: #758, #759, #786, and #788.

In the future, there is going to be a lot of things happening on this page. I am concerned that it might be too much, and therefore, I want to think about how this page is designed to be as functional as possible and easy to use for the partner organizations who are conducting outreach.

**Comment by smarziano** [comment]
After sharing the design materials with our partners, they _love_ this direction of the outreach page:
![outreach- resources thumbnail 1](https://user-images.githubusercontent.com/5550969/27061347-db2e99bc-4fa8-11e7-80a6-0a00a0a4b309.png)

We are ready to add the current content and materials on the /outreach page to the new designs as well as the ones that are listed in these GitHub issues: #787, #790, #791, #792, #793. 

We expect to receive the data dashboard (#758) and the Google calendar (#759) by Monday, June 19. Therefore, I am also assigning this to myself to get these assets.

**Comment by amynicole** [comment]
![outreach impact](https://user-images.githubusercontent.com/7504439/27343096-8b0ba0b0-55a7-11e7-80b1-15ba4be58d52.png)
![outreach resources](https://user-images.githubusercontent.com/7504439/27343101-8cc3c22a-55a7-11e7-8aa9-d988fccaaa9d.png)
![outreach share](https://user-images.githubusercontent.com/7504439/27343105-8e87b5f8-55a7-11e7-80cd-93916a1f5278.png)

Updated designs for the outreach page.

**Comment by amynicole** [comment]
@theandrewbriggs Here's a zip of all the SVGs for icons
[SVG.zip](https://github.com/smartchicago/chicago-early-learning/files/1093009/SVG.zip)

**Comment by smarziano** [comment]
Here are my notes from reviewing this on staging. 

- [ ] Please add icons to appropriate tabs

## Resources tab
- [ ] Let's remove the "Early Learning Programs" button because that is something that won't be updated until the July 31 redesign deadline
- [ ] Change "Early Learning Resources" to "Chicago Early Learning Resources"

Here are the resources that should be on this tab:
- [ ] Flyer in English: https://chicagoearlylearning.org/static/img/flyer-image.png
- [ ] These logo assets: https://github.com/smartchicago/chicago-early-learning/issues/790
- [ ] Verification packet: https://github.com/smartchicago/chicago-early-learning/issues/793

## Events
I am going to check in with partners and make sure that the events they put on the calendar are listed as public. I am seeing this message on the calendar: "Events from one or more calendars could not be shown here because you do not have the permission to view them."
- [ ] I would add a header (similar to what is on the Resources tab) to say "Events"

## Share
I thought that we were going to construct an image with content to share as described in issue https://github.com/smartchicago/chicago-early-learning/issues/792. If we need to create specific messages for Twitter/Facebook, I think I can help work with our partners on that.

As it is now, let's make the following adjustments:
- [ ] Move video to the top of this tab
- [ ] Add images: https://github.com/smartchicago/chicago-early-learning/issues/733#issuecomment-300895801
- [ ] Add text to direct users of the outreach page before the actual captions: 
Share the news with families on social media. Use any of these captions below on Facebook, Twitter, Instagram, Snapchat or more:
- [ ] Add the following captions:
- The Chicago Early Learning preschool application is now open! Parents looking for quality preschool programs for 3 and 4 year olds in the fall can register today! #chicagoearlylearning
- Are you a parent of a 3 or 4 year old? Don't miss out on early access to over 600 preschool programs throughout the city for next school year. Apply today. Start in September! #chicagoearlylearning
- With over 600 options throughout the city let us help you find the best match for your 3 and 4 year old. Get started at chicagoearlylearning.org #chicagoearlylearning
- OR create your own caption on social media! Just don't forget to use #chicagoearlylearning 
- [ ] Add the "Download all images" below the images

## Impact
I have given instructions to our partners to adjust the view of this dashboard. I don't think there is anything else to do on this tab.

**Comment by theandrewbriggs** [comment]
> I thought that we were going to construct an image with content to share as described in issue #792. If we need to create specific messages for Twitter/Facebook, I think I can help work with our partners on that.

@smarziano This is something that we hardcode, it's not something a user can pick. We pre-populate copy and images that show up when sharing the website on Facebook, Twitter, etc. We can still do this, but it is unrelated to the Outreach page.

**Comment by smarziano** [comment]
@theandrewbriggs We are still waiting for feedback from partners, but here are the tasks to complete from @amynicole and myself:

## Resources tab
- [ ] File name on download pane should 18 px, medium weight
- [ ] File format should be 16 px
- [ ] Download icon can be a little smaller
- [ ] Add thumbnail images for the downloads

**Question** Do we need to make each download asset a separate row? For example, could it be Large Logo then download in Black & White or Color?

## Share tab
- [ ] Column of text is too narrow. Should be the same width as the text on the resources page– (roughly the same width as the video.) If we make that section wider, one photo image can sit next to it and the video can move down.
- [ ] It is a little awkward that you can't see the full image especially since the text is cut out of the first two images
- [ ] I think it'll be good to add a line about following Chicago Early Learning accounts on social media. (I will write this up)

## Impact tab
Every time I come back to this tab in a new session, I get a weird stacking of the Tableau dashboard:
<img width="1251" alt="screen shot 2017-06-28 at 3 31 18 pm" src="https://user-images.githubusercontent.com/5550969/27658824-f1fe8600-5c16-11e7-8bca-a6da60e51d97.png">

**Question** This does fix itself if I do a hard refresh, but is there something we can do to make it appear correctly the first time?

**Comment by smarziano** [comment]
Here is the feedback we got from our partners! 

## General feedback
- [ ] Reorder tabs to be Resources, Share, Events, Impact
- [ ] Apparently, we do **not** have the go ahead to show the Tableau dashboard at this time. They need to check their systems to make sure the data is accurate before launching this. Our partner suggested adding "Coming Soon!" language on this tab.

## Resources
Feedback: "Simple bolding for emphasis in the paragraph text may help draw out the main points a touch more and make it feel less text-heavy – maybe the first paragraph, or the 'social media links, talking points, and outreach resources' bits."
- [ ] Let's bold "Here you will find social media links, talking points, and outreach resources to help share information with Chicago families."

## Share
- [ ] Our partners suggested switching this from "Share" to "Communications"
- [ ] Add these 2 Twitter appropriate length share messages:
- The Chicago Early Learning 3 & 4 year old pre-k application is open! Register today at chicagoearlylearning.org #ChicagoEarlyLearning
- Look what your child can do! Enroll your 3 or 4 year old in Pre-K today at chicagoearlylearning.org #ChicagoEarlyLearning 
- [ ] Add this general social media message (I would replace the first "now open" example"):
- Are you a parent of a 3 or 4 year old? See what your child can do! Don't miss out on access to over 600 preschool programs throughout the city for next school year. Apply today. Start in September!  #ChicagoEarlyLearning
- [ ] Remove Lorem impsum paragraph below "On this page you'll find resources that can be used to spread the word about the Chicago Early Learning site and enrollment process."
- [ ] Replace this text: "Share the news with families on social media....Just don't forget to use the hashtag #chicagoearlylearning" with "Share these messages on social media with #ChicagoEarlyLearning"

**Comment by theandrewbriggs** [comment]
> Column of text is too narrow. Should be the same width as the text on the resources page– (roughly the same width as the video.) If we make that section wider, one photo image can sit next to it and the video can move down.

> Remove Lorem impsum paragraph below "On this page you'll find resources that can be used to spread the word about the Chicago Early Learning site and enrollment process."

If I do both of these (i.e., if we don't add more copy to explain this page), it looks bad:
![screen shot 2017-06-28 at 19 14 59 pm](https://user-images.githubusercontent.com/3439795/27666014-7e9541a2-5c36-11e7-9ed1-48be48555528.png)

**Comment by theandrewbriggs** [comment]
> It is a little awkward that you can't see the full image especially since the text is cut out of the first two images

I can format it better (i.e., make the images frames better fit the flyer page sizes), but this is the problem with making a grid of images that are different sizes, the images are going to have to be cropped to match the grid.

**Comment by smarziano** [comment]
@theandrewbriggs Re: the column width, maybe we can move the video to another part of the page? I thought it'd look better at the top but this might not work. 

If we keep the current column width, maybe we could remove one photo and one caption so that the left-hand column is just text and then right column(s) are content (video, photos, captions). This might make things looks better.

**Comment by theandrewbriggs** [comment]
@smartchicago/chicago-atlas Here's how that looks:
![screen shot 2017-06-28 at 20 56 56 pm](https://user-images.githubusercontent.com/3439795/27668070-7ca83df0-5c44-11e7-9409-93bd2ce9438c.png)

**Comment by smarziano** [comment]
Here are two images from the marketing campaign with the Look What I Can Do! brand text (one in English and one in Spanish) to replace the 2 placeholder images seen in the last comment:

![web-image6](https://user-images.githubusercontent.com/5550969/27712300-0e3252ae-5cec-11e7-90c1-4caf51f13888.jpg)

![web-image3](https://user-images.githubusercontent.com/5550969/27712308-146c0ed0-5cec-11e7-934a-d08d5043d511.jpg)

**Comment by smarziano** [comment]
In addition, let's add the Informational Flyer in Spanish from this issue: https://github.com/smartchicago/chicago-early-learning/issues/786#issuecomment-303122055 on the Resources tab underneath the other Informational Flyer.

**Comment by smarziano** [comment]
Great work!
<img width="1276" alt="screen shot 2017-06-29 at 10 45 57 pm" src="https://user-images.githubusercontent.com/5550969/27720072-dd6ac896-5d1c-11e7-8696-12c0097bfc66.png">
