### ISSUE TITLE
Spanish: Updated /city-resources page translations

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#800]
La Ciudad de Chicago y el Alcalde Rahm Emanuel están comprometidos a darle acceso a oportunidades de educación temprana de alta calidad a las familias a todo lo largo de la ciudad. Además de los programas fuertes existentes en escuelas y sitios comunitarios, también hay un gran número de oportunidades para comenzar a estimular a su niño en su aprendizaje temprano en otros entornos.

## Connect4Tots
Connect4Tots envía mensajes de texto sobre recursos GRATIS para padres y tutores legales de niños que comienzan a dar sus primeros pasos y que tienen de 1 a 3 años de edad. Los padres y tutores legales que se suscriben a Connect4Tots reciben de 2 a 3 mensajes de texto semanalmente con información acerca del crecimiento y desarrollo de su niño y lo conectan a recursos y eventos en la Ciudad de Chicago sobre salud y seguridad, educación, servicios públicos ¡y más!

### ¡Suscríbase hoy!
**Envíe lo siguiente en un texto: TOTOPT7 al 311311 o use este [formulario en línea](http://chitot.org/enroll).**

Cuando se suscriba, se le preguntará la fecha de nacimiento y el sexo de su hijo, la dirección de su domicilio en la ciudad y su idioma preferido para recibir textos (inglés, español o polaco). Una vez suscrito, recibirá automáticamente de 2 a 3 mensajes por semana con consejos y sugerencias útiles.
Las tarifas estándar para enviar mensajes de texto pueden aplicar.

### ¡Dígale a sus amigos en Chicago!
¿Ya es un padre Connect4Tots? Dígaselo a sus amigos de Chicago quienes sean padres de niños que comienzan a dar sus primeros pasos para que ellos también puedan recibir mensajes de texto con recursos GRATIS para los que califiquen.

### Información adicional
Connect4Tots está patrocinado por la Ciudad de Chicago y los Laboratorios Urbanos (Urban Labs) de la Universidad de Chicago. Urban Labs evaluará los efectos del programa cuando analice cómo los participantes usan la información y los recursos incluidos en los mensajes de texto. Revise la hoja de consentimiento para obtener mayor información. Para obtener mayor información sobre el programa, por favor contacte a Urban Labs en Connect4TotsFeedback@cityofchicago.org.

## Chicago Park District
**_Distrito de Parques de Chicago_**

Varios parques ofrecen clases recreativas de educación temprana: interacción entre mamás, papás e infantes, juegos en grupo, preescolar, títeres, cuentos, y gimnasia para mamás, papás e infantes. Los participantes en Educación Temprana desarrollan y mejoran sus habilidades motrices, sociales, y para escuchar a través de los programas de educación en el movimiento. [Visite el Distrito de Parques de Chicago](http://www.chicagoparkdistrict.com/) para buscar e inscribirse en una clase cerca de usted.

## Chicago City of Learning
**_Chicago, Ciudad de Aprendizaje_**

Chicago City of Learning (CCOL) es una iniciativa pionera que reúne oportunidades de aprendizaje para jóvenes de tal forma que les permite pensar, perseguir y desarrollar sus propios intereses. CCOL y sus socios llevan experiencias de educación temprana a diferentes espacios durante el verano para preparar a los niños a entrar al jardín de niños en el otoño. [Visite CCOL](https://chicagocityoflearning.org/) para encontrar las oportunidades que existen cerca de usted.

## Chicago Public Library
**_Bibliotecas Públicas de Chicago_**

Bibliotecas Públicas de Chicago (CPL por sus siglas en inglés) tiene muchas oportunidades enriquecedoras para niños, incluso espacios para la educación temprana en las bibliotecas y horas de lectura para preescolares. CPL también tiene unidades móviles que llevan actividades manuales de aprendizaje de STEAM (por sus siglas en inglés; se refiere a ciencias, tecnología, ingeniería, artes y matemáticas) para los niños pequeños, junto con una programación en alfabetización para la familia, facilitadas por bibliotecarios a lo largo de la ciudad. CPL tiene tres unidades móviles con paquetes de aprendizaje basados en STEAM por toda la ciudad, uno por cada Distrito Bibliotecario. [Contacte a CPL](https://www.chipublib.org/) para obtener más detalles. 

## Chicago Children's Museum
**_Museo de Niños de Chicago_**

El Museo de Niños de Chicago tiene un buen número de espacios para la educación temprana para apoyar el desarrollo de comunidades en donde el juego y el aprendizaje se conecten. Una de sus exhibiciones permanentes, “The Tinkering Lab” (Un laboratorio para juguetear), tiene un rincón de aprendizaje con objetos interactivos seguros y herramientas que se pueden tocar. El Museo de Niños también se asocia con otras entidades para llevar espacios de educación temprana y participación a otros lugares en la ciudad. [Contacte al Museo de Niños de Chicago](http://www.chicagochildrensmuseum.org/) para obtener más detalles.

## Chicago Department of Public Health
**_Departamento de Salud Pública de Chicago_**

Las bases del aprendizaje temprano y del éxito de los niños comienzan con la salud maternal y de los niños. Las clínicas de salud en el vecindario del Departamento de Salud Pública de Chicago (CDPH por sus siglas en inglés) ofrecen apoyo para las mujeres embarazadas y servicios de bienestar para los niños. El CDPH también tiene un buscador de recursos para muchas de las necesidades que tienen las familias que están esperando o que ya tienen niños pequeños, inclusive cuidado de la salud y otros apoyos como ropa, asientos de carro para bebés y más. [Contacte al Departamento de Salud Pública de Chicago](http://www.healthychicagobabies.org/) para obtener más detalles.

**Comment by smarziano** [comment]
@theandrewbriggs I would like to see the English name listed as the title of each section with the Spanish translation below it in a smaller but emphasized font. This would match the formatting in my last comment. 

The reason for it is that Spanish speaking parents might be more familiar with the English name versus our translation.

**Comment by theandrewbriggs** [comment]
Got it, that wasn't super clear. I'll make this change soon.
