### ISSUE TITLE
Spanish: Update FAQs translations

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#801]
We have updated translations for the FAQs page via the admin tool. I am assigning this to myself to complete. Here is a checklist of sections to be completed:

- [x] Applying for Programs
- [x] Returning Students and Families with Multiple Children
- [x] Placement and Registration
- [x] Family Resource Centers
- [x] General Questions

**Comment by smarziano** [comment]
Moving this issue to Phase 2. I have updated most of the translations. I have to double-check some things listed under "General Questions" with the English version before this is entirely completed.

Another task (question) is if I should update the slugs to use the new Spanish language or keep the questions the same in order to keep URLs consistent? @theandrewbriggs -- do you have any thoughts on this?

**Comment by theandrewbriggs** [comment]
@smarziano So I will be rebuilding the FAQs from scratch for this phase as a static page, and building out the application component for it in Phase 3. If you could just put the final FAQ list with full text and translations in a google doc and send to me (or link it here), that'd be great for right now. Re: slugs, lets keep both sets in English - I'm pretty sure it'd break if we tried to do language specific slugs.

**Comment by smarziano** [comment]
@theandrewbriggs This sounds good. Our partners are currently reviewing and editing the FAQs content. I will share in conjunction with the new design (#813). 

I am going to close this issue because all of these translations have been completed as of now.
