### ISSUE TITLE
Create a user-friendly "How to apply" page

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#807]
Currently, the link to the /how-to-apply page is hidden on the homepage. We want to highlight this page and make it very clear for parents on how to apply.

Here is the first pass of the newly designed /how-to-apply page
![how to apply](https://user-images.githubusercontent.com/5550969/27348540-08df5678-55ba-11e7-9565-641e33f5572e.png)

Here are my notes:
- Let's update the top sub-nav bar to include the hotline information and not the event/blog
- Update the header image not to be the stock image
- I think part of the process should be finding and comparing programs on Chicago Early Learning. I don't want parents to think that they should start with the application and then find out that they need to choose a site. If a parent adds and compares a location on Chicago Early Learning, they can choose 2 schools that will be passed to the COPA application.
- The third step needs to be updated. I believe now parents should know immediately if they are eligible for a program. I have a call on Thursday with our partners. I will get clarification.
-  I think there is a step 4 which is to contact the location to see if there are any other location-specific requirements (I will verify with partners on my call)
- It's a little awkward that the "Family Resource" button is duplicated across the "Have you found the right program..." and "Need application support" blocks. Should "Have you found..." lead to the Program types page?
- Verification step 2 isn't to bring documents to a Family Resource Center. This is only for CPS locations. Let's make this extremely clear that there are two processes based on program type (maybe utilize the pencil/book icons or a side by side format)

**Comment by smarziano** [comment]
Here is some important information about the application process. There are three primary steps: **Apply > Verify > Enroll** but then there are other smaller steps around that. I'm going to do my best to explain that here:

## Search/Support
This could be considered part of the "Apply" step. There are possible routes:
- Parents visit ChicagoEarlyLearning.org, search/compare and complete the preschool app (COPA)
- Parents visit ChicagoEarlyLearning.org, and go straight to the application because they know their choice (COPA)
- Parents go directly to a Family Resource Center or community-based organization or an opened school (this varies) and apply there

I am not sure if the in-person route might be confusing to parents already on this website.

## Apply
There are a few steps involved with the application:
- Create an online account for your family (Step 1 in your design)
- Fill in information about your family (Step 2 in your design) like employment and financial info, etc
- Create an application for each child you are applying for a preschool spot for (parents can choose up to two sites)

After completing these steps, parents immediately receive notification about whether they got on the wait list or an offer at their first-choice site. Parents also receive an email explaining how to verify their spot.

## Verification
I added details about this in my last comment, but depending on the type of site, parents have different verification processes. For community-based organizations, the rest of the process can be described as a "one-stop shop" where parents can complete both the **Verification** AND **Enrollment** processes.

For CPS sites, parents need to go to a Family Resource Center to verify. 

For the next design iteration, the verification steps should stay the same.

## Enrollment
This is a new step in the process, but I think it's a good one to have. For CBO's, parents complete this process in the verification step. For CPS-based, parents should contact the school to see about completing the enrollment process. Enrollment process includes things like getting the actual site information that might vary from site-to-site. Like testing to see if bilingual support is required, checking to see if immunizations are up to date, etc.

This might not be standardized across sites so it is important for parents to contact and check. For CPS, parents contact the school. Some of these schools will be open and parents can complete this before the first day of school (which is helpful to the sites) OR they find out how to prepare for the first day of school.

Unlike the verification process, we don't have to go into as much detail about these steps. 

## First day of School!
This isn't really a step, but it is the ending point that should be kept the same.

**Comment by smarziano** [comment]
There are FAQs that have content that we should consider adding onto this page. This does not need to word-by-word or the full content just important points that parents should not have to go to the FAQs to find. 
- [How many sites can I apply to?](https://chicagoearlylearning.org/faq#how-many-sites-can-i-apply-to)
- [Do I need to apply if my child is already enrolled?](https://chicagoearlylearning.org/faq#do-i-need-to-apply-if-my-child-is-already-enrolled) 
- [What does it mean to be on the waitlist for a site?](https://chicagoearlylearning.org/faq#what-does-it-mean-to-be-on-the-waitlist-for-a-site)
- [How can I change something on my submitted application?](https://chicagoearlylearning.org/faq#how-can-i-change-something-on-my-submitted-application)

**Comment by amynicole** [comment]
![how to apply](https://user-images.githubusercontent.com/7504439/27545615-dc9df646-5a55-11e7-841b-36a2ea236789.png)
This version incorporates the first batch of feedback. I'd like to talk through this page on our call today, so we can solve the content together.

**Comment by smarziano** [comment]
Notes from our call today:

- Move the application video spot up, then shown the step-by-step process, then the verification information and ending with the "Have you found the right program...?" and "Need application support?" content
- Combine steps 2 & 3 since this all happens in COPA
- Step 3 is the verification process. Placement happens immediately and then the parent receives information about verifying.

Questions for me to ask our partners:
- Check about the waitlist FAQ content and see about updated information
- Determine the number of documents necessary in the verification process
- Determine how long a parent has during "preliminary placement" before they have to verify or risk losing their seat (I'm not sure if this is the case or not)

**Comment by jenmakes** [comment]
@smarziano Can you please bullet down the steps again — based on our notes and yours I can't tell if we are removing a step completely or if there is a step missing in the flow. 

1. Find Locations
2. Combine 2 + 3 - Create an online profile and fill out information like xyz (COPA)
3. Your child has been placed, parent received information and will need to verify enrollment 
4. ? Missing Step or remove ? 
5. Contact location to see if there are any location specific requirements
Apple Icon. See you the first day of school! ...

**Comment by smarziano** [comment]
@jenmakes Here are the steps as I see them:
Step 1: Find locations
Step 2: (COPA preschool application) Create an account, fill out family information, child application to preschool
Step 3: Receive placement information then verification process
Step 4: Enrollment: prep for the first day by contacting location to see if there are location-specific requirements
Apple icon: School time!

**Comment by jenmakes** [comment]
@smarziano Thanks! I just wanted to double check :)

**Comment by jenmakes** [comment]
Hi @smarziano here is an updated draft of the 'How it Works' page — thanks again for outlining the steps, I am sure the actual content will be modified on your end when they review and we can always update the iconography if CEL thinks there is a better symbol for each step. Please let me know if anything needs to be tweaked before you present. 

https://cl.ly/0J0z30460Y2K

**Comment by smarziano** [comment]
I had a great meeting with our partners and we discussed this page in detail. They loved how far we got and thought we are moving in the right direction.

Our partners want three steps (Apply, Verify, Enroll), therefore, instead of making search step one, why don't we have it at the top so that it mirrors the apple at the bottom. They also suggested a magnifying glass or other illustration for "Search" but thought the map pinpoint could work, too.

We talked a lot about step 3, and the City has concerns that we need to distinguish between community-based and CPS-based sites at this point. After hearing some of the challenges they currently face, I think branching the two is a good idea. Therefore, step 3 is still receive placement information and start the verification process but parents need to check in placement email if they will be at a CPS or community-based site. Then the branch in this step-by-step process occurs where on the CPS side a family is verifying at a Family Resource Center, then contacting the center to finish enrollment (step 4) and on the CBO side a family is verifying and enrolling at their center (steps 3 & 4). The branches come back at the apple!

**Comment by jenmakes** [comment]
Here are a couple of ideas for that graphic on the 'How To Apply' page. 

The first idea stems from the divergent path graphic concept you presented. Our worry is that it doesn't translate to mobile well and looks too cyclical. 

https://cl.ly/2d0l1i2L0n2h

Our second idea was to draw a straight-line down the middle. Still doesn't solve our mobile translation problem well.

https://cl.ly/433Y1m372B2P

The third option was to stack icons to the left and text to the right and to break the options in step two by 'OR' and a horizontal rule. This is much easier to translate to mobile. 

https://cl.ly/0d372V011f2J

Still, having two icons still feels busy, so we reconsidered going back to a single icon that is focused on illustrating a check-list and relying on text to outline the differences. This option feels the most straightforward, simple to read, and easily translates to mobile.

https://cl.ly/2P05333W2t1g

Here is the full page with the last concept mocked up. 

https://cl.ly/2n0K1I1v2l2C

Let us know what you think. 
Jen

**Comment by smarziano** [comment]
@jenmakes Amy and I talked about this page in detail while we were in the same room during tonight's user test sessions. I think that was helpful. We are definitely getting closer to the final design but I think you two are going to connect about those mock-ups before making any adjustments.

**Comment by jenmakes** [comment]
Howdy! I hope you are having a good trip @smarziano 

I meant to post this earlier today. Here is an updated version using Flags. To keep the design responsive-friendly, all the text is stacked in one column on the right and icons are stacked on the left. Since it is unknown whether or not a parent knows the location they want to apply for yet, I wanted to cap the flow with actions — 'Find Locations' or 'Start An Application'. Rest of the page is the same. 

Image: https://cl.ly/1L2R3q0X0G3y

**Comment by smarziano** [comment]
Great work! I am sharing with our partners for their review. I am adding the "Requires info" tag to remind me that we are waiting for their feedback.

**Comment by smarziano** [comment]
Our partners approved the most recent design and this page is ready for implementation. I am going to close this issue and begin another one for implementation.
