### ISSUE TITLE
Update /about page design

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#811]
Here is the most recent About page redesign:
![about](https://user-images.githubusercontent.com/5550969/27447680-8dcdf64e-5747-11e7-8db2-c903923625bf.png)

My notes about this page:
- In the partner sections, we should have the City of Chicago, CPS and DFSS on one line. Then Smart Chicago and other partners on the next line.
- I really like the idea of adding a media library. Can this be something other than videos? Can we show that as an example? Maybe the media library also includes photos or logos? Maybe we add an email for people to contact if they have media inquiries?
- As for the "In-press and testimonials" section, I am trying to think of the audience for this page. I feel like testimonials, while great in other places on the website, are probably not necessary here. Instead, I would like this to be about press releases or media spots that highlight Chicago Early Learning. I would also like you to keep the statistics examples, too.

**Comment by amynicole** [comment]
![about](https://user-images.githubusercontent.com/7504439/27545506-94bd40b6-5a55-11e7-88b9-a98ad53ebd8e.png)
I could not fit the City, CPS, and DFSS on one line due to content length. I instead opted for a fully stacked layout, which better suited the content of the page.

**Comment by smarziano** [comment]
From partner meeting today, they liked the styling of the Press and Media section, but did not think there needed to be a separate Media Library. Any videos from that section could also fit into the Press and Media section.

**Comment by smarziano** [comment]
@jenmakes If you can remove the Media Library section and keep the "Press and Media" (but maybe only have 3-4 boxes in this section since that is more realistic in terms of content) this will be ready to hand over to @theandrewbriggs for implementation.

The content has been requested from partners.

**Comment by jenmakes** [comment]
Hi @smarziano. Here is an update to the About Page. I removed the Media Library but did keep the press-kit download and press contact information on the page. I placed it towards the bottom under the reduced Press+Media blocks. It would possibly sit better above the grid so it doesn't feel buried — either way, the element can easily move or be removed from this layout.

https://cl.ly/2d1G2o3B0Q2r

**Comment by smarziano** [comment]
This is great, @jenmakes. I am not sure if they will have all those content pieces so I appreciate the flexibility to remove those sections as necessary. I am going to close this issue since this design is ready for implementation.
