### ISSUE TITLE
Create new /blog page

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#812]
This blog page will not be a highlighted part of the website because we are more interested in connecting appropriate content to relevant information pages. For example, if our partners want to add a testimonial that will also be seen on the program type page or if there is a blog post about a program for 5-year-olds at Chicago Public Library that could be seen on the /city-resources page.

However, we still want a place for parents to see and read all blog posts. Here is a current page design:
![blog](https://user-images.githubusercontent.com/5550969/27448276-d8d4768e-5749-11e7-8b04-f530b794216a.png)

My notes about this design:
- I think it would be ideal to have some ability to find posts by date. Kind of like what we have on the Smart Chicago website: http://www.smartchicagocollaborative.org/news/all-posts/
- Another thing we may want to add are categories (but this relates to other content management work that will come in phase 3)
- I would limit the view of the blog on this page to a certain number of characters and then have a "read more" button that either leads you to a new page or expands.

**Comment by amynicole** [comment]
![blog index](https://user-images.githubusercontent.com/7504439/27545401-5f31bab2-5a55-11e7-9540-cce37c5438b7.png)
![blog single post](https://user-images.githubusercontent.com/7504439/27545402-5f47ed50-5a55-11e7-89fb-16dc8dde6038.png)

A blog index page and blog post page detail. It has a tabbed navigation at the top for different categories. We could change that to years for the initial launch. The right hand has a sort for "Newest to Oldest"/"Oldest to Newest".

**Comment by smarziano** [comment]
@amynicole This looks great. I don't see any edits at this time. 
I'm adding the "Requires info/approval" label to this issue because I am going to send it in the next review round. If we do not hear any edits we can implement this design.

**Comment by smarziano** [comment]
Closing this issue because this is in implementation phase (#838).
