### ISSUE TITLE
Add Medicaid & SNAP information on City Resources page

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#814]
This relates to #810 where we are updating the design of the /city-resources page. Our partners want to add content about Medicaid & SNAP to this page.

The week of July 10 or 17 is when I will send all text for Spanish translations that relate to the Redesign milestone. 

## Apply for Medicaid and SNAP (Food Stamps)

The Children and Family Benefits Unit (CFBU) of the Office of Student Health and Wellness (OSHW) can help you apply for Medicaid (low cost or free health insurance) and SNAP benefits (food stamps) at no cost. In partnership with the Greater Chicago Food Depository and Patient Innovation Center, the CFBU will:

• Walk you step-by-step through the Medicaid and SNAP application
• Help you understand your eligibility and the documents needed
• Assist you with renewing your medical or SNAP case
• Help you choose a medical plan and a doctor

Call 773-553-KIDS (5437) for more information or to make an appointment.

![logo-medicaid](https://user-images.githubusercontent.com/5550969/27656607-3296a358-5c0f-11e7-83b1-86427d3687ff.png)

![snap-logo](https://user-images.githubusercontent.com/5550969/27656593-289975ce-5c0f-11e7-8c91-275ab2d533c3.jpg)

**Comment by theandrewbriggs** [comment]
@smarziano Do we have transparent PNGs for these?

**Comment by smarziano** [comment]
Here you go, @theandrewbriggs:
![snap_logo_hi_res](https://user-images.githubusercontent.com/5550969/28603933-df2c6872-718c-11e7-953e-ae5942ba456a.png)
![medicaidlogotransparent](https://user-images.githubusercontent.com/5550969/28603934-df48454c-718c-11e7-8bd3-06d6af1f0eac.png)
