### ISSUE TITLE
Issue with "Apply" button highlighted partially in grey

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#815]
It appears when the "Apply" button on the Compare & Apply page is highlighted (meaning that two or more locations are selected) but the cursor is not hovering over the "Apply" button, the button appears half in grey and half in blue. Here is a screenshot:

<img width="699" alt="screen shot 2017-06-29 at 2 45 11 pm" src="https://user-images.githubusercontent.com/5550969/27712202-8bde221a-5ceb-11e7-9732-8352479be44c.png">

**Comment by theandrewbriggs** [comment]
I have not been able to replicate this.

These button components are going to be rewritten as part of the redesign.

**Comment by smarziano** [comment]
I am closing this issue because we have new buttons with our mobile redesign.
