### ISSUE TITLE
Separate "Compare & Apply" into two functions

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#819]
We have discussed this idea in the past, but with my recent conversation around the hand-off between Chicago Early Learning and the COPA preschool application it came up again. 

Currently, we encourage all users to "Compare and Apply" which adds the site to their list. The flow is for parents to search, add sites to their list, compare and then click apply. 

<img width="514" alt="screen shot 2017-06-30 at 8 42 44 am" src="https://user-images.githubusercontent.com/5550969/27738521-2a884884-5d71-11e7-9184-4d26b264f1d7.png">

What we heard is that parents might go directly to the application and then have to go back to Chicago Early Learning if they haven't made a choice. Parents might not need to compare locations and want to directly click an "Apply" button. I want to revisit this and think about separating the Compare & Apply into two actions – 
1) **Add to Compare** that will lead to the same process that currently exists on the site
2) **Apply** that will pass the site ID to the COPA preschool application immediately

A possible issue with this plan is that parents will only be sending one site ID, and not two. I will check in with our partners to see if that is a problem or not. 

I'm adding the "question" label to this issue so we can discuss further on our next call.

**Comment by theandrewbriggs** [comment]
This is pretty straightforward from our end, FYI.
