### ISSUE TITLE
Update navigation bar

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#820]
As part of the redesign milestone, we need to update our current navigation bar:
<img width="1274" alt="screen shot 2017-06-30 at 11 38 22 am" src="https://user-images.githubusercontent.com/5550969/27745368-b1be1024-5d88-11e7-858d-d02b1b1d9c18.png">

This our new design:
![cel-redesign-navigation](https://user-images.githubusercontent.com/5550969/27745982-1ae933ce-5d8b-11e7-8f92-e9eeb88d7857.jpg)

**Questions**
- Is Early Learning Programs too long? Should we just say Programs?
- Do we need to add "Need help?" before "Call the Chicago Early Learning Hotline..." or is that apparent?
- Should "Find Locations" be "Find Locations," "Find Programs" or "Find Sites"? I think I need to check the language that is consistently used. I think it might need to be "Find Sites"  

**Some tasks to complete**
- [x] Update link text
- [x] Create new /early-learning-programs URL
- [x] Redirect /families to /early-learning-programs
- [x] Continue Application Login > should go to https://cys.mycopa.com/familyPortal/welcome.epl

**Comment by theandrewbriggs** [comment]
Just to be clear - do "Continue to Application Login" and the "Apply" button have the same link to COPA? I think it's fine/makes sense, but I just want to clarify that.

**Comment by smarziano** [comment]
Correct, @theandrewbriggs, "Continue to Application Login" will go to the same place as the "Apply" button.

**Comment by theandrewbriggs** [comment]
@smarziano Are we still gonna have the search bar in the nav on every page? I haven't seen it in designs.

**Comment by theandrewbriggs** [comment]
@smarziano Another question - do we want "sticky" nav bar like we currently have, or do we want a nav that scrolls away as you scroll down the page? Compare what's currently on production vs what's on staging /redesign pages now

**Comment by smarziano** [comment]
@theandrewbriggs I think that instead of the search bar we are using "Find Sites" instead. I like this direction, especially on the informational pages. The only place that it would be valuable to have our search bar is on the /search page so that once users searched they can try other address search terms. I'd like to think about that in connection with what we learned today from the user tests. cc: @amynicole 

Honestly, I am not sure about the whether or not to have a sticky nav bar. It's hard for me to tell when there is no content on the page. The longer the pages, the more inclined I am to say have a sticky nav bar.

**Comment by theandrewbriggs** [comment]
I am super onboard with no search in the nav, but it will mean we need a dedicated search bar on the map page itself (which is fine!). 

We can discuss this more on our call tomorrow.

**Comment by amynicole** [comment]
I'm in favor of a sticky nav.

**Comment by smarziano** [comment]
@theandrewbriggs I checked the nav bar on staging and "Read more ->" should be "Continue Application Login ->" I don't know when it was changed. 
<img width="1263" alt="screen shot 2017-07-24 at 6 25 59 pm" src="https://user-images.githubusercontent.com/5550969/28550879-837c73aa-70a1-11e7-8274-dc8cab2ef0bc.png">

**Comment by smarziano** [comment]
The text of the top nav-bar is the same size as the font in the regular nav bar (14px). I think we can use a slightly smaller font size for the top nav bar like 12 px (?) to differentiate the nav bars.

**Comment by theandrewbriggs** [comment]
I made the top nav smaller, but if we make the font of the bottom nav any larger, the words will start wrapping weird

**Comment by smarziano** [comment]
@theandrewbriggs Our partners updated their request and asked that use "Find Locations" instead of "Find Sites."

**Comment by smarziano** [comment]
We are going to want to update "Resources" to something else. There are currently a few contenders:
- Beyond Preschool
- More Activities
- Additional Activities

I am going to close this issue for now and open another to update the name of the /resources page.
