### ISSUE TITLE
Update footer for redesign

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#821]
We need to update the footer as part of our redesign milestone:
<img width="1253" alt="screen shot 2017-06-30 at 1 36 41 pm" src="https://user-images.githubusercontent.com/5550969/27749434-36689fdc-5d99-11e7-9393-cf5eff6872b2.png">

This is our new snazzy design:
![cel-footer](https://user-images.githubusercontent.com/5550969/27749517-7ff27dc6-5d99-11e7-8fbf-b8eadebc412a.jpg)

For the social media, there are only two accounts: [Facebook](https://www.facebook.com/ChicagoEarlyLearning/) and [Twitter](https://twitter.com/ChiEarlyLearn)

In terms of the other text and links, here is the order with changes:
_First column_
- "About Early Learning" should be "About Chicago Early Learning" and lead to /about page
- "Early Learning Programming" should be "Chicago Early Learning Programs" or "Programs" and lead to /early-learning-programs
- "How to Apply"
- "Find Locations
- "FAQs"

_Second column_
- "City Resources" should be "Resources"
- "News and Press" should be "Latest News"
- "Events calendar" should be removed
- "Family Resource Centers"
- "Give us feedback!" should be removed

Since two lines of text will be removed, we can move FAQs to the second column.

**Comment by theandrewbriggs** [comment]
@smarziano do we have a white logo asset somewhere? I'm not seeing it.

**Comment by smarziano** [comment]
I couldn't find one either, so I inverted the black logo. Here is a white version for us to use:
![cel logo white](https://user-images.githubusercontent.com/5550969/27998314-5b181dcc-64d2-11e7-86d5-95078199c1b9.png)

(^ It's there... I promise!)

**Comment by smarziano** [comment]
This is looking really great on staging:
<img width="1275" alt="screen shot 2017-07-09 at 9 43 46 pm" src="https://user-images.githubusercontent.com/5550969/28001103-ba39912e-64ef-11e7-979d-98d1221fc2ae.png">

Some notes:
- Let's remove caps for this text: "FOR APPLICATION INFORMATION PLEASE CALL THE CHICAGO EARLY LEARNING HOTLINE AT (312) 229-1690." 
- Let's remove caps for this text: "FOLLOW US:"
- Can we add a little more space under the Chicago Early Learning logo
- Also, can we add a little more space between the list and the "Copyright..." text?
- Let's change "About Chicago Early Learning" to just "About" or "About us" so it fits on one line
- Can "FAQ" change to "Frequently Asked Questions" and still fit on one line? If not, keep it as is.

**Comment by smarziano** [comment]
After listening to a parent's feedback during the mobile design ux session, I want to move the "For Application Information please call..." and social media content to the left side as in the original design. This is so this will be the first thing parents read in the footer.

**Comment by smarziano** [comment]
@amynicole & @jenmakes This is more of a question for you, but our partners wanted to see if we could incorporate the City of Chicago, DFSS, and CPS logos into footer. What are your thoughts or ideas for this?

I believe that if this becomes too messy or hard to do, I can discuss with our partners about re-adding that Partners section we previously removed in our homepage design (#803). I think this is a better solution, but want to consider their idea and see if it is something we can do.

**Comment by amynicole** [comment]
@smarziano I have an idea of how we might incorporate the logos. I will mock it up and share.

**Comment by amynicole** [comment]
So, the logos don't convert well to a single color, so I do not recommend adding them to the footer. If we want to show the logos, I suggest bringing back the Partner bar from previous designs. Here's another alternative, with the partners names listed in the footer. 

<img width="1108" alt="screen shot 2017-07-20 at 9 09 45 pm" src="https://user-images.githubusercontent.com/7504439/28446374-0285dd5e-6d90-11e7-91c4-4b7dea86003c.png">

**Comment by smarziano** [comment]
@amynicole I like this idea. I am sharing this with our partners and seeing if they prefer this or adding a partner section on the homepage.

**Comment by smarziano** [comment]
# Partner logos
@amynicole Our partners did not prefer this solution, and rather have us add the partners section on the homepage that was in an earlier design (#803).

<img width="1042" alt="screen shot 2017-07-20 at 8 37 03 pm" src="https://user-images.githubusercontent.com/5550969/28546975-f633c5a0-7089-11e7-8ced-e1dafa456aff.png">

# Staging
@theandrewbriggs In terms of our current footer on staging, there need to be a few changes:
<img width="1272" alt="screen shot 2017-07-24 at 4 07 38 pm" src="https://user-images.githubusercontent.com/5550969/28547255-4fd09be6-708b-11e7-8b26-3c536b8e9b03.png">

- It would be nice to get "About Chicago Early Learning" on one line. Maybe this needs to be changed to "About Us" 
- I would move "Resources" to below "How to Apply" so it follows the homepage order
- Change "Find Locations" to "Find Sites" to match navbar text

**Comment by smarziano** [comment]
Here are final edits to the footer:
<img width="1279" alt="screen shot 2017-07-27 at 11 08 02 am" src="https://user-images.githubusercontent.com/5550969/28680435-f6623b72-72bb-11e7-8db3-9983b055daca.png">

On desktop, the text falls too far to the left and this makes the footer seem unbalanced. My suggestion is that "Chicago Early Learning Hotline..." should fall on the second line and that will help make this text less skinny. 

![img_8002](https://user-images.githubusercontent.com/5550969/28680698-bf4cf932-72bc-11e7-83d9-b68a6d13e6a6.PNG)

On mobile, there is a lot of space at the bottom of the footer that could possibly be removed.

**Comment by theandrewbriggs** [comment]
Setting the break at that point before "Chicago Early Learning Hotline" results in cases like this:
![screen shot 2017-07-27 at 19 19 29 pm](https://user-images.githubusercontent.com/3439795/28697324-9772c27c-7300-11e7-9fba-865ae6a6688c.png)

**Comment by smarziano** [comment]
That's too bad re: the break point. It still looks unbalanced to me, but it's a great improvement and hits all of the requirements. Adding "Waiting on Merge" tag.

**Comment by smarziano** [comment]
With the update to the nav bar from "Find sites" to "Find locations" (https://github.com/smartchicago/chicago-early-learning/issues/820#issuecomment-318922300), we need to make the same change to the footer.
