### ISSUE TITLE
Implement new design of /connect page

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#822]
The new design for the /connect (newsletter) page is completed via issue #816.
![newsletter page](https://user-images.githubusercontent.com/5550969/27934734-bd10235c-626c-11e7-9c0c-f4bc23072952.png)

Only updates to content include:
"Stay up to date on Chicago early learning!" should be "Stay up to date on Chicago Early Learning" so that Chicago Early Learning always stays capitalized.

**Comment by theandrewbriggs** [comment]
@amynicole Can you get me this shapes background asset

**Comment by smarziano** [comment]
Assigning @amynicole just as a reminder to get background asset to @theandrewbriggs for this page if it hasn't been given already.

**Comment by smarziano** [comment]
Updates for this page:
<img width="1275" alt="screen shot 2017-07-30 at 1 55 10 pm" src="https://user-images.githubusercontent.com/5550969/28756183-da3a5180-752e-11e7-9c2c-5a86c23c3951.png">
- [ ] Confetti looks very large (@amynicole)
- [ ] Font is also a bit large (@amynicole)

**Comment by amynicole** [comment]
Headline should be:
Montserrat Medium, 24 px tall

**Comment by smarziano** [comment]
This is implemented. I'm closing this issue, but I'm going to open another issue to help with the spacing.
