### ISSUE TITLE
Add Outdated Browser plugin

### ISSUE THREAD

**Issue by theandrewbriggs** [smartchicago/chicago-early-learning#824]
As a part of the upgrade to Bootstrap 4, we'll have to leave behind a lot of older unsupported browsers.

We'll implement this plugin to recommend people upgrade their browsers:

https://github.com/burocratik/Outdated-Browser/tree/master

**Comment by smarziano** [comment]
@theandrewbriggs Was this completed with our last launch?

**Comment by theandrewbriggs** [comment]
Yes! We can close this out.
