### ISSUE TITLE
Implement new /about page design

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#826]
The design for the about page is completed via issue #811. 

![about v2](https://user-images.githubusercontent.com/5550969/28152332-72ea29a0-6765-11e7-97b9-e9442d3a73e0.png)

# Content
About Chicago Early Learning

### City of Chicago
Mayor Rahm Emanuel and the City of Chicago are committed to supporting children across the City access high-quality education, from early learning programs through college. Since taking office, Mayor Emanuel has invested over $75 million into expanding early childhood programs and ensuring quality, access throughout the city. Launched in 2012, the online Early Learning Portal has helped parents make the choices that are best for their children and families.

### Chicago Public Schools
Chicago Public Schools works to ensure that every student in every community has access to a high-quality education that prepares them for success in college and career.

### Chicago Department of Family and Support Services
The Chicago Department of Family and Support Services (DFSS) is dedicated to supporting a continuum of coordinated services to enhance the lives of Chicago residents, particularly those most in need, from birth through the senior years.

### Smart Chicago Collaborative
The Smart Chicago Collaborative is a civic organization devoted to using technology to make lives better in Chicago. We work to apply the transformative power of technology to solve problems for the people of Chicago.

## Press and Media 
Placeholder text for now; content has been requested by partners

# Other notes
Let's make sure we use a different photo for the header image since this one is being used for the /city-resources page. Since I have limited availability, I am calling to @amynicole to choose an appropriate one. My thought is maybe the one of the little boy dressed up as a mayor from the most recent photo shoot? But we are not using many of those images on other places on the website.

**Comment by smarziano** [comment]
Here are transparent logos that are currently not on staging:
- Ounce of Prevention: 
![ounce-logo-transparent](https://user-images.githubusercontent.com/5550969/28547547-a442c22a-708c-11e7-846d-151dd918e3d7.png)
- Erikson:
![eriksoninstitute_logo_rgb](https://user-images.githubusercontent.com/5550969/28547569-b6f1d7a8-708c-11e7-91c8-341243251947.png)
- Metropolitan Family Services:
![mfs-logo-campaign-vertical](https://user-images.githubusercontent.com/5550969/28547581-c2e0c79a-708c-11e7-807d-b870610c07ed.png)
- Illinois Action for Children
![iafc-logo-purple](https://user-images.githubusercontent.com/5550969/28547598-dd3e8e6a-708c-11e7-81b6-423aa0661b38.png)
- Healthy Chicago
![healthychilogo](https://user-images.githubusercontent.com/5550969/28547659-25470264-708d-11e7-87fc-a1f93016ad18.png)
- Smart Chicago Collaborative
![smart-chicago-collaborative-logo-transparent](https://user-images.githubusercontent.com/5550969/28547879-3b8b2f7c-708e-11e7-9be1-294ee4c5c799.png)

**Comment by smarziano** [comment]
Based on what is currently on staging, below are some recommendations:
<img width="1248" alt="screen shot 2017-07-24 at 4 39 38 pm" src="https://user-images.githubusercontent.com/5550969/28547989-b8c06f84-708e-11e7-9262-629043a0b0ee.png">
- Move the "Partners" text a bit further down under the header image
- Adjust logo sizes of the main partners so they are a little more equal. Currently, the City of Chicago logo seems too big
- Change the font color of "Other partners" to the same orange being used for "Partners" near the top
- For the header image, I might recommend using this one because I don't think it's being used in other places:
![marycrane6](https://user-images.githubusercontent.com/5550969/28548243-1f6231e0-7090-11e7-8dfb-676ba1d3ac6e.jpg)
Here are a couple of other options that I like and might not be used elsewhere:
![roseland1](https://user-images.githubusercontent.com/5550969/28548293-6744115e-7090-11e7-99f0-e2906ba40b12.jpg)
![belmont2](https://user-images.githubusercontent.com/5550969/28548309-826dfac6-7090-11e7-8588-2acb9f060b5e.jpg)

**Comment by jenmakes** [comment]
@smarziano I went ahead and mocked up the hug/smile option. It frames a little better in the skinny horizontal hero image. https://cl.ly/2E011f0r0p31

I also like this image, but Amy mentioned we might be using it already elsewhere. 
https://cl.ly/0f3M0X0N320T

I also tried out some political images — since this is the About page maybe tying it closer to the city partners makes sense? Rahm is a little hard to frame here https://cl.ly/1m2L2t30322I

Rahm and this girl frame okay https://cl.ly/3o1S2p1n063d

I'm indifferent to using a more political image but you may have stronger feelings about that. 
- Jen

**Comment by smarziano** [comment]
Let's try to make this photograph work for the header image:
https://drive.google.com/file/d/0B3-ILi-hWe7WZWlvNXRnR3lTWEk/view?usp=sharing

**Comment by smarziano** [comment]
@theandrewbriggs - For this sentence "Since taking office, Mayor Emanuel has invested over $45 million into expanding early childhood programs and building quality, access, and transparency throughout the city..." the $45 million needs to be updated to $75 million
