### ISSUE TITLE
Create and implement Family Resource Centers page

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#828]
The design for this page is near completion via issue #811.
![family resource centers v5](https://user-images.githubusercontent.com/5550969/28249060-614ecf6c-6a0c-11e7-83a7-50cb64377387.png)

# Content

## Family Resource Centers
Family Resource Centers are a place for all Chicago families seeking more information or in-person support on preschool enrollment. Our friendly staff will help you answer questions about your child’s application. For families with a preschool placement at a Chicago Public Schools site, staff at Family Resource Centers will also verify income and employment documentation. (Families with a preschool placement at a community-based site will verify their documentation directly at the site location.) 

All visitors to Family Resource Centers will have access to internet and computers. If a family would like to use a library computer, the user must have a library card. Anyone with a valid ID with name, photo and Chicago address can sign up for a library card on site.

**_Applications will be taken 30 minutes after opening and will end 30 minutes before closing._**

[Icon] Bilingual support available

## List of Centers
Use the current list: https://chicagoearlylearning.org/faq#en-family-resource-centers

## What is the preschool application process?
Are you ready to apply for a preschool program for your 3- or 4-year-old? Learn about the process here or call (312) 229-1690 with your questions.
[Learn more]

# Other notes
- I believe the URL should be /family-resource-centers
- I think we might need to adjust the last illustration depending on the feedback we get from the /how-to-apply page
- We still need to update the speech bubble (https://github.com/smartchicago/chicago-early-learning/issues/808#issuecomment-314573026)

**Comment by theandrewbriggs** [comment]
This page is ripe for converting into something more automated. Let's revisit this in Phase 3.

**Comment by smarziano** [comment]
The Family Resource Centers Page is looking really great so far; I really like the new bilingual support icon. Here are some notes:
<img width="659" alt="screen shot 2017-07-24 at 5 00 40 pm" src="https://user-images.githubusercontent.com/5550969/28548513-a6ce034c-7091-11e7-8c8e-18a2af02d35d.png">
- The following text should be a separate paragraph and in a different color as seen in the earlier design. I think this will help break up the text. 
_For families with a preschool placement at a Chicago Public Schools site, staff at Family Resource Centers will also verify income and employment documentation. (Families with a preschool placement at a community-based site will verify their documentation directly at the site location.)_
- Let's not italicize the phone numbers of the Family Resource Centers

**Comment by theandrewbriggs** [comment]
Update on map assets - I think I can generate these quickly, but I don't want to make any promises for the 31st. They'll be lower down on my "Weekend Before Launch" list, but if I have time I'll try to get them up. At the very least, they'll be up next week.

**Comment by smarziano** [comment]
We still need to add the map images to the /family-resource-centers page. Otherwise, this is implemented. I am going to close this issue and open a new one for map adding.
