### ISSUE TITLE
Implement new How to Apply page

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#833]
The design for the How to Apply page is ready via issue #807.
![how to apply - v5 2](https://user-images.githubusercontent.com/5550969/28548899-d9bd4086-7093-11e7-8f08-3166bb977f60.png)

We are currently waiting for content updates for this page from our partners. We are also waiting for the video asset from the communications firm.

**Comment by smarziano** [comment]
@theandrewbriggs Here are few suggestions/improvements based on what is currently on staging; I understand that there are a lot of items (assets and content) that need to be added so I will do another review later. 

## High Priority
- [ ] Update header image
- [ ] Add styling to “Are YOU ready to apply for a preschool?”
- [ ] “Let the learning begin!” text is missing styling

## Lower Priority
- [ ] Adjust alignment of text under “How will you verify your child's placement?” section
- [ ] Not enough space around the Enrollment Process steps text

**Comment by smarziano** [comment]
Here is the content for this page that has been reviewed and approved by our partners. 

# How to Apply

## Are you ready to apply for preschool?
Enrolling your 3- or 4-year-old in a Chicago Early Learning preschool program is easy and open year-round. Follow these easy steps to get your child enrolled in preschool. 

If you have any questions, please reference our [FAQ page](chicagoearlylearning.org/faq) for more details.

## Enrollment Process

### Search Locations
Find and compare Chicago Early Learning programs to find the right one for your child. Get Started!

### Apply to Program
Narrow it down to your top two picks. Create an online account, fill out family information, and a child application to preschool sites. If your child qualifies for an offer, you will follow next steps verify their placement. If your child remains on a waitlist, stay tuned for more information from the Chicago Early Learning team. 

### For CPS Site Offers: Verify placement through a Family Resource Center
Within two weeks of receiving your offer, bring proof of your family’s income, address, and your child’s birth to one of 12 Family Resource Center sites across the city. [Click here](chicagoearlylearning.org/family-resource-centers) for more information about Family Resource Centers. See below for more details about what documents you will provide. 

**OR**

### For Community-Based Site Offers: Verify placement through your community-program location
Within two weeks of receiving your offer, bring proof of your family’s income, address, and your child’s birth to your assigned community-based program location. See below for more details about what documents you will provide.

### Enrollment at CPS-Program Location
Visit your child’s preschool over the summer or as soon as school starts to complete the enrollment process. The school may have more specific enrollment directions that they will communicate. 

**OR**

### Enrollment at Community-Program Location
When you visit your child’s community-based site to verify your child’s offer, your site will communicate any additional expectations they have to complete the enrollment process. 

### Go to School!
If you have questions, please call our Chicago Early Learning Hotline: (312) 229-1690 or visit a Family Resource Center near you.

[Search Locations] 	[Start an application]

## How will you verify your child's placement?
If your child is offered a preliminary preschool placement, you will receive an email with verification instructions.

_Follow these three steps to accept your child’s placement:_

### Step 1) Gather Documents

#### Proof of child’s age
Original birth certificate
Passport

#### Proof of address
Driver’s license/ID card
Utility bill
Lease agreement/mortgage statement
Current voter’s registration card

#### Proof of income
Current paystub
1040/W-2
SSI Letter
Unemployment letter/stub
Workers’ compensation letter/stub
Retirement or pension stub/letter
Alimony
Official child support letter
TANF
Income verification form

Note: If your family is in a temporary living situation, you are not required to present the documents listed above for verification. All schools must immediately enroll students in temporary living situations even if the student lacks health, immunization or school records, proof of guardianship, proof of residency, or any other documentation normally required for school enrollment.

## Have you found the right program for your child?
The City of Chicago and its partners offer early learning programs at over 600 sites. Visit our search page to identify sites in areas near your home or work. The Chicago Early Learning Portal allows you to identify a program’s quality rating, schedule and ages served.

[Learn about Program types]

## Need Application Support?
If you have any concerns with the online application, please call our Chicago Early Learning Hotline at (312) 229-1690, or visit any of the Family Resource Centers.

[View Family Resource Centers]

**Comment by smarziano** [comment]
I went ahead and checked off the items from our last comments that were completed from commits (f0769f3...ddffa0f). _Please see above._

Here is a new header image option to try for this page:
![cb fave 3](https://user-images.githubusercontent.com/5550969/28741298-b62f760a-73d8-11e7-81af-552db508e908.jpg)

Here are some other final tasks:
## Desktop
### Higher priority
- [ ] Add content for "Have you found the right program for your child?" and "Need application support?"
- [ ] Add line and numbers between steps
- [ ] Check font styling of "Are YOU ready to apply for preschool?" headline (@amynicole)

### Lower priority
- [ ] Make the CPS and Community-based icons a little smaller. (@amynicole)
- [ ] Add some space between "Are YOU ready to apply for preschool?" headline and text

**Comment by amynicole** [comment]
Font styling of "Are you ready for preschool" looks correct.

**Comment by theandrewbriggs** [comment]
@smarziano @amynicole I couldn't figure out a way to do the line between the step SVGs, I think if we add numbers, that should be enough?

**Comment by smarziano** [comment]
That absolutely should be enough. Especially for tomorrow.

**Comment by smarziano** [comment]
Last tweaks to this page: 
- [ ] Zoom out of the header image
- [ ] Add a space below the questions "Have you found the right program for your child?" & "Need application support?" and the content
- [ ] Make sure buttons are linked to the right places

**Comment by smarziano** [comment]
I am going to create a new issue for remaining items. Closing this issue.
