### ISSUE TITLE
Update splash announcement text

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#835]
We need to update the splash announcement as soon as possible on our current hero image:
"Parents! Join us on August 4 for a FREE, fun-filled conference designed specifically for parents of young children. Register today: www.2017parentconference.eventbrite.com"

There is no Spanish text currently.

On our redesigned homepage for July 31 (#825) this text should go in the "Important update" section.

**Comment by smarziano** [comment]
Here is the Spanish text: ¡Padres! Acompáñenos el 4 de agosto para una conferencia GRATUITA y divertida diseñada específicamente para padres de niños pequeños. Regístrese hoy: www.2017parentconference.eventbrite.com

**Comment by theandrewbriggs** [comment]
This is live.

**Comment by smarziano** [comment]
I'm closing this issue because it's live and also part of the homepage redesign (#825).
