### ISSUE TITLE
Spanish: Programs redesigned page translations

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#841]
Here are some of the translations for the newly redesigned /programs page.

<img width="969" alt="screen shot 2017-07-28 at 10 56 48 pm" src="https://user-images.githubusercontent.com/5550969/28741961-0f3d3390-73e8-11e7-9b87-e6a6ca6f44b1.png">

**¡Mira lo que Nuestro podemos hacer!**

En la Educación Temprana de Chicago, todas nuestras familias, sin importar cuales sean sus necesidades, podrán encontrar y asegurar un programa de educación temprana de calidad.

“Cada niño, en cada vecindario, se merece una educación de calidad y esta debe comenzar en sus años tempranos.” - Rahm Emanuel, Alcalde de Chicago

<img width="1267" alt="screen shot 2017-07-28 at 10 57 24 pm" src="https://user-images.githubusercontent.com/5550969/28741966-2e4322e0-73e8-11e7-9232-9ed558159f02.png">

_What early learning program should your child(ren) be enrolling in?
Enter a birthdate. The result will reflect what you should enroll in Fall 2017._
[Submit birthday]

<img width="582" alt="screen shot 2017-07-28 at 10 58 54 pm" src="https://user-images.githubusercontent.com/5550969/28741969-58f140ee-73e8-11e7-8b9e-0ab0abfd30b2.png">

Infantes y los que comienzan a dar sus primeros pasos
0 a 2 años
Estos programas pueden llamarse “Early Head Start” (Comienzo temprano), “Prevention Initiative” (Iniciativa de prevención), o “Early Intervention” (Intervención temprana).

¿A quienes sirven?
Desde los niños recién nacidos hasta los niños de 3 años que califiquen.

¿Qué proporcionan?
- Actividades educativas y para el desarrollo social.
- Los programas pueden incluir servicios gratis para la salud (médicos, dentales, salud mental), comidas nutritivas, así como educación y capacitación para los padres.

<img width="572" alt="screen shot 2017-07-28 at 11 00 24 pm" src="https://user-images.githubusercontent.com/5550969/28741978-8f19f8fa-73e8-11e7-8164-c1e8baeaa268.png">

Preescolar
3 y 4 años
Los programas preescolares pueden llamarse “Head Start” (Comienzo temprano) o “Preschool for All” (Preescolar para todos).

¿A quiénes sirven?
A los niños de 3 y 4 años de edad que califiquen.

¿Qué proporcionan?
- Actividades educativas y para su desarrollo social que promueven su preparación para la escuela.
- Ya sea medio día o un día completo de instrucción.
- Los programas pueden incluir servicios gratis para la salud (médicos, dentales, salud mental), comidas nutritivas, así como educación y capacitación para los padres.

<img width="1001" alt="screen shot 2017-07-28 at 11 01 44 pm" src="https://user-images.githubusercontent.com/5550969/28741982-bf39419e-73e8-11e7-8f38-63ca64249a57.png">

_Kindergarten
Age 5
Children who are 5 years old by September 1st of the current school year should enroll in kindergarten at a CPS preschool. Visit the CPS website to enroll a child in kindergarten._
[Aprenda más]

<img width="957" alt="screen shot 2017-07-28 at 11 02 49 pm" src="https://user-images.githubusercontent.com/5550969/28741988-e5044298-73e8-11e7-846a-dc86a118eb4f.png">

Tipos de programas
Los programas de educación temprana en la Ciudad de Chicago están disponibles en una variedad de sitios diferentes:

Escuelas Públicas de Chicago (CPS)
Edades 3 y 4 años
Muchas escuelas primarias de CPS ofrecen programas de educación temprana como parte de sus servicios.

Basados en la comunidad 
Edades 0 a 5 años
Hay lugares en el vecindario que proporcionan educación temprana, así como cuidado infantil para infantes y aquellos que comienzan a dar sus primeros pasos. Las horas varían por sitio.

_Home Visiting Care is also available for qualifying families, for children between the ages of birth to 3. _ Los entrenadores que visitan casas proveen cuidado temprano y asesoría en casa a las familias que califiquen.

<img width="920" alt="screen shot 2017-07-28 at 11 06 47 pm" src="https://user-images.githubusercontent.com/5550969/28742002-73df82ca-73e9-11e7-9e38-1ee6eb8bffb4.png">

_Choosing the Right Program
Quality ratings for Chicago Early Learning programs, and programs across Illinois and the country, offer families more insight before they make final choices about a program for their child._

¿Qué significa “calificación de calidad”?
La calificación de calidad indica qué calidad tiene un sitio en base al sistema “ExceleRate Illinois”. Este es un nuevo sistema para calificar la calidad y la mejoría de los sistemas en Illinois. Ha sido diseñado para calificar la calidad de los programas de educación temprana y para establecer un estándar, basado en los resultados de investigación, para los proveedores de educación temprana y de desarrollo. Hay Círculos de Calidad en ExceleRate en diferentes niveles y mientras más alto se encuentra el nivel otorgado a un programa, quiere decir que el programa ha realizado más mejorías significativas en cuanto a la preparación del niño para la escuela y para la vida. Se puede encontrar más información sobre ExceleRate en ExcelerateIllinois.com.

¿Qué es la "acreditación"?
La acreditación significa que un programa ha alcanzado los estándares altos de excelencia determinados por una organización nacional como la Asociación Nacional para la Educación de los Niños Pequeños (NAEYC por sus siglas en inglés), la Acreditación Nacional de los Programas de Educación Temprana (NEPCA por sus siglas en inglés), o el Consejo de Acreditación (COA por sus siglas en inglés). Los programas que reciben acreditación nacional han demostrado su calidad en áreas como la enseñanza, el currículum, las evaluaciones del aprendizaje, la salud, las relaciones comunitarias, el entorno físico y la administración escolar.
Para aprender más acerca de la acreditación de los programas de educación temprana, presione en uno de los siguientes enlaces:

[Asociación Nacional para la Educación de los Niños Pequeños](http://www.naeyc.org/)
[Acreditación Nacional de los Programas de Educación Temprana](http://www.necpa.net/index.php)
[Consejo de Acreditación](http://coanet.org/)

<img width="1192" alt="screen shot 2017-07-28 at 11 15 47 pm" src="https://user-images.githubusercontent.com/5550969/28742040-b638455c-73ea-11e7-93bc-83d326ef756d.png">

_Other Local Activities and Resources
See our Resources page to learn more about programs for young children throughout the city that are not part of Chicago Early Learning._
[Aprenda más]

**Comment by smarziano** [comment]
@theandrewbriggs Here are changes that we can currently make
- [ ] "CHICAGO MAYOR RAHM EMANUEL" = "Rahm Emanuel, Alcalde de Chicago"
- [ ] "Edades 0 a 5 años" should be "Edades 0 a 4 años" to match the English content

I will see about getting the rest of the translations for this page.

**Comment by smarziano** [comment]
Here are the rest of the translations:

**Kindergarten section**

Jardín de niños
5 años de edad
Los niños que han cumplido 5 años de edad para el 1º de septiembre del año escolar corriente deben inscribirse en un jardín de niños en un preescolar de CPS. Visite el sitio Web de CPS para inscribir a su niño en el jardín de niños.

-----
**Transportation note**

Nota: Las Escuelas Públicas de Chicago y los sitios basados en la comunidad no pueden proporcionar transportación hacia todos los programas de Educación Temprana a lo largo de la ciudad. Sin embrago, el programa de Educación Temprana de Chicago recomienda a las familias que tomen ventaja de las oportunidades que ofrece el transporte público. Conozca más en el sitio Web de CTA.

----
**Choosing the Right Program**

Cómo escoger el programa apropiado
Las clasificaciones de calidad de los programas de Educación Temprana de Chicago y de otros programas en Illinois y el país ofrecen a las familias información adicional para que puedan hacer sus decisiones finales acerca del mejor programa para su niño.

-----
**Venn Diagram section**

¿Qué es lo que hace que los programas sean estupendos?
Visite sus programas preferidos en persona si puede hacerlo.
Usted sabrá si un programa es sólido cuando vea lo siguiente:

_Child-Friendly Spaces..._

Espacios especiales para niños
Un espacio seguro especial para hasta 20 niños en edad preescolar con juguetes y materiales, tanto en el interior como en el exterior.
 
_Top-notch teachers_

Maestros de alta calidad
Maestros atentos e involucrados con carreras de cuatro años y capacitación; 1 maestro por cada diez estudiantes en los programas antes del jardín de niños.
 
 _Engaged students_

Estudiantes involucrados
Una variedad de actividades apropiadas uno a uno, en grupos pequeños y grandes, junto con la oferta de comidas y tiempo para la siesta.

_And much more_
 
Y mucho más…
Los visitantes son bienvenidos pero tienen que pasar por medidas de seguridad requeridas; los adultos y niños se lavan las manos frecuentemente.

----
**Other local activities... section**

Otras actividades y recursos locales
Vea nuestra página de recursos para conocer más acerca de los programas que hay para los niños a lo largo de la ciudad y que no son parte de la Educación Temprana de Chicago.

----
Find sites = Encuentre los sitios

**Comment by theandrewbriggs** [comment]
This is live on production.

**Comment by smarziano** [comment]
Opened up issue #925 for @amynicole to help us update the venn diagram asset with the Spanish translations. Everything else looks good and so I will close this issue.
