### ISSUE TITLE
Implement new center detail page

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#842]
The design for the center detail page is completed via issue #823. The biggest change to this design is to remove the colors associated with the X and checkmarks next to the Ages served.

![28447776-a9c27b24-6d98-11e7-97f6-7a05641d52e4](https://user-images.githubusercontent.com/5550969/28742109-13ddfed4-73ed-11e7-9c84-1e20fdcb6f19.png)

**Comment by smarziano** [comment]
Here is the design for the mobile center detail page:
![mobile location 1](https://user-images.githubusercontent.com/5550969/29477685-ffd0366c-842e-11e7-8df1-ff2cfe387c00.png)

Some notes about this design that should also be represented in the desktop version:
- We are removing the "Share" button
- We are not going to show the site's URL
- Make the grey (?) icon darker
- Do not show the X and checkmark symbol next to the ages served field

**Comment by smarziano** [comment]
Here are changes that need to be made on the **mobile** center detail page:
- [ ] Update font sizes at the top of the page @amynicole 
- [ ] Update button sizes @amynicole 
- [ ] Add "Back to results" link at top as seen in mobile design
- [ ] Change "Location website" to "View website >" 
- [ ] Switch "Get Directions" button with "View on Map" button
- [ ] Change order of buttons to "View on Map" then "Compare Location" then "Apply Today!"
- [ ] Check spacing between sections @amynicole 
- [ ] Add grey line to separate "Duration and Hours" and "Program Information" sections
- [ ] Add grey line to separate "Accreditation" and "Quality Rating" sections
- [ ] Utilize shortened accreditation and quality rating content seen in design
- [ ] Do not show "Accreditation" block when a site is not nationally accredited (we do this currently on the live site)
- [ ] Make the quality rating (Gold, Silver, Bronze, Licensed) more obvious. Right now it's getting hidden with all of the other text. @amynicole might have ideas

**Comment by theandrewbriggs** [comment]
> Switch "Get Directions" button with "View on Map" button
Do we want the "Get Directions" button on Desktop (or both?), distinct from View on Map?

**Comment by smarziano** [comment]
@theandrewbriggs I want only the "Get Directions" button on desktop, and (only) "View on Map" on mobile.

**Comment by amynicole** [comment]
Mobile Notes:

@theandrewbriggs On this page, I'd like for us to use the standard height buttons.

For the telephone and website links, let's make them 16px font.

It also looks like there's an extra space between Duration and Program information, and between Accreditation and Quality Rating.

**Comment by amynicole** [comment]
For the quality ratings, can we try them in bold?
