### ISSUE TITLE
Spanish: Navigation bar

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#844]
<img width="1277" alt="screen shot 2017-07-29 at 3 16 24 pm" src="https://user-images.githubusercontent.com/5550969/28747958-e9ed17f2-7470-11e7-96fa-7867a62070f9.png">

Early Learning Programs = Programas
How to Apply = Proceso de inscripción
Find sites = Encuentre centros
Resources = Recursos
FAQ = Preguntas frecuentes
Apply = Aplique

Call the Chicago Early Learning Hotline at (312) 229-1690 = Llame al Chicago Early Learning línea de acceso directo al (312) 229-1690
_For mobile, you could just say Llame al Chicago Early Learning al (312) 229-1690 to save on space._

Continue to Application Login = Continue a la solicitud

**Comment by smarziano** [comment]
@theandrewbriggs Does "Preguntas frecuentes" not fit for FAQ? 

All of the other translations look good.

**Comment by smarziano** [comment]
To follow-up on my last comment, is there any way that we can fit  "Preguntas frecuentes" into the nav bar? Even "Preguntas" may be an improvement.

**Comment by smarziano** [comment]
Adding "Waiting on Merge" label since this is updated on staging, but not on the live site.

**Comment by theandrewbriggs** [comment]
This is live on production.
