### ISSUE TITLE
Spanish: About page designs

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#846]
Here are the translations for the /about page:

## Sobre Nosotros

**Ciudad de Chicago**
El alcalde Rahm Emanuel y la ciudad de Chicago tienen el compromiso de apoyar a los niños de toda la ciudad para que tengan acceso a educación de alta calidad, desde los programas de educación temprana hasta la universidad. Desde que comenzó a fungir en su puesto, el Alcalde Emanuel ha invertido más de $75 millones para expandir los programas de Educación Temprana y asegurar la calidad y el acceso a lo largo de la ciudad. Lanzado en 2012, el Portal de Educación Temprana en línea ha ayudado a los padres a realizar las mejores selecciones para sus niños y familias.

**Escuelas Públicas de Chicago**
Las Escuelas Públicas de Chicago (Chicago Public Schools / CPS) trabajan para asegurar que todos los alumnos de todas las comunidades tengan acceso a educación de alta calidad que los prepare para desempeñarse con éxito en sus estudios universitarios y su carrera.

**Departamento de Servicios Familiares y de Apoyo de Chicago**
El Departamento de Servicios Familiares y de Apoyo de Chicago (Chicago Department of Family & Support Services / DFSS) está dedicado al apoyo de una gama de servicios coordinados para mejorar la vida de los residentes de Chicago, sobre todo los más necesitados, desde el nacimiento hasta la edad avanzada.

**Smart Chicago Collaborative**
El Smart Chicago Collaborative es una organización cívica dedicada al uso de la tecnología para mejorar la vida de los residentes en Chicago. Trabajamos para aplicar el poder de transformación de la tecnología para resolver los problemas de las personas de esta ciudad.

**Comment by smarziano** [comment]
@theandrewbriggs "About" needs to be updated to "Sobre nosotros"

I will see about getting translations for "Partners" and "Other Partners."

**Comment by smarziano** [comment]
Partners = Socios
Other Partners = Otros socios

**Comment by theandrewbriggs** [comment]
This is live on production.
