### ISSUE TITLE
Re-crop header image on How to Apply page

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#849]
The header image on the /how-to-apply page seems too zoomed in. I want to explore how this header image would look if we zoomed out a bit.

<img width="1280" alt="screen shot 2017-07-31 at 1 37 34 pm" src="https://user-images.githubusercontent.com/5550969/28792515-85a56214-75f5-11e7-8093-37816789c029.png">

**Comment by amynicole** [comment]
@theandrewbriggs Do you need me to crop this image for you?

**Comment by theandrewbriggs** [comment]
This is the image I have. We're constrained by width in all of these header images, so I can't "zoom out" this photo without pillarboxing. Maybe we pick a different photo?

![headphone-girls](https://user-images.githubusercontent.com/3439795/30785069-0a358f6c-a126-11e7-912f-eeb269fa7b3e.jpg)

**Comment by theandrewbriggs** [comment]
I can zoom out a teensy bit:

![screen shot 2017-09-24 at 12 47 58 pm](https://user-images.githubusercontent.com/3439795/30785108-c362b8ac-a126-11e7-9a17-fcbb35cfe856.png)

**Comment by theandrewbriggs** [comment]
@smarziano We need a new header image, see above comment.

**Comment by amynicole** [comment]
It seems like all of the photos we were given are cropped to these very strange proportions.

**Comment by smarziano** [comment]
The more I look at this header image the less I have a problem with it. Our partners have not expressed an issue with it either. Closing issue!
