### ISSUE TITLE
Add line and number steps to How to Apply steps

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#850]
We are missing the line and number steps on the Enrollment Process section of the How to Apply page seen in the original design (#833).

**Comment by amynicole** [comment]
@theandrewbriggs Anything I can do to help with this?

**Comment by theandrewbriggs** [comment]
@amynicole Can I get numbered illustration SVGs? 

I haven't figured out a good way to do the line, but I'll try to come up with something.

**Comment by amynicole** [comment]
https://www.dropbox.com/sh/7v3d6rlw9qwk101/AADcPByrB98rWw_I45q2qHs7a?dl=0

**Comment by theandrewbriggs** [comment]
@amynicole Can you re-export these? I think we're getting that overlapping styling problem again, this is how they render on the site:
![screen shot 2017-09-24 at 12 56 20 pm](https://user-images.githubusercontent.com/3439795/30785166-e483d9f2-a127-11e7-8307-c6a8ad712c4b.png)
![screen shot 2017-09-24 at 12 56 22 pm](https://user-images.githubusercontent.com/3439795/30785167-e48f4fe4-a127-11e7-90e4-95e2e7cecbb4.png)

**Comment by theandrewbriggs** [comment]
Lines between steps are not doable without significant reconstruction of this page (relates to #879)

**Comment by amynicole** [comment]
Re-exported and added to the Dropbox!

https://www.dropbox.com/sh/7v3d6rlw9qwk101/AADcPByrB98rWw_I45q2qHs7a?dl=0
