### ISSUE TITLE
Chalk font is not appearing on some Windows browsers

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#865]
We are still facing some issues with the chalkduster font on a couple of Windows browsers: Chrome & Firefox.

**Comment by amynicole** [comment]
Can our fallback on these browsers be Montserrat? That way, it's on-brand with the rest of the site.

**Comment by smarziano** [comment]
@theandrewbriggs & @amynicole Can we investigate other chalk fonts that could work on these other browsers? While this is a good short-term solution, this chalk font is a big part of the marketing campaign and I'd like to get closer to the correct font.

**Comment by amynicole** [comment]
@theandrewbriggs You're using @font-face, correct? What font format are you using? WOFF should work. I converted the font file online to all formats. Try using this, if you're not already.
[Chalkduster.zip](https://github.com/smartchicago/chicago-early-learning/files/1223118/Chalkduster.zip)

**Comment by smarziano** [comment]
@theandrewbriggs It looks like the fonts have been fixed on Windows browsers, but this chalk font takes a quick moment to load. I am not sure if there is a solution to that.
