### ISSUE TITLE
Add missing FAQ content

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#875]
_Add following question after "How can I get off of a preschool site’s waitlist?"_

I’m on a waitlist and I want to consider a different site for my child. How do I do that? 
- Visit ChicagoEarlyLearning.org to compare other preschool sites and consider new options
- Visit a [Family Resource Center](https://chicagoearlylearning.org/family-resource-centers) near you for support
- Call our Family Support Hotline at 312-744-9322
- Call the preschool site that you are interested in directly 

Estoy en una lista de espera y quiero considerar un sitio diferente para mi niño, ¿cómo lo hago?
- Visite ChicagoEarlyLearning.org para comparar otros sitios preescolares y considerar nuevas opciones
- Visite un [Centro de Recursos para la Familia](https://chicagoearlylearning.org/family-resource-centers) cercano a usted para obtener apoyo
- Llame a la línea de acceso directo de Apoyo para las Familias al 312-744-9322
- Llame directamente al sitio preescolar en el cual está interesado

**Comment by theandrewbriggs** [comment]
I'm adding this, but it's weird that we're saying "Visit ChicagoEarlyLearning.org"? Could that be a link to /search?

**Comment by smarziano** [comment]
Regarding your last comment, I've added an update to the content in #886. Therefore, I am closing this issue.
