### ISSUE TITLE
Update button sizes across the site

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#882]
@amynicole shared that buttons should be 50px tall and 240px wide. Buttons may be wider in certain cases (mobile, long label text, etc), but the design to follow is on the left:
<img width="676" alt="screen shot 2017-08-16 at 4 01 20 pm" src="https://user-images.githubusercontent.com/5550969/29385129-3c96f03e-829c-11e7-9dee-c855014a6bc3.png">

**Comment by theandrewbriggs** [comment]
This is live on production.
