### ISSUE TITLE
Mobile: Clicking "Find Locations" leads to search prompt page

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#884]
Currently on our mobile experience, if a parent clicks on "Find locations" they are taken directly to the search map. Since we are prioritizing list view search (#693), we want to change this so that parents are taken to a page that asks them to enter an address, site or zip code to begin their search process.  

<img width="299" alt="screen shot 2017-08-18 at 4 11 12 pm" src="https://user-images.githubusercontent.com/5550969/29477948-287b364c-8430-11e7-8219-532737adcfb9.png">

**Comment by theandrewbriggs** [comment]
Should we get rid of the homepage search bar in general and just have a single button and funnel people here?

**Comment by smarziano** [comment]
I think the homepage search bar is great and would prefer to keep it. 

Parents have many other ways to get to the /search mobile page, and currently, they are getting to the list of community areas and instead should come to this newly designed page.

**Comment by smarziano** [comment]
@theandrewbriggs Let's update the text here to say "Enter address, site, or zip code" to be the same as the homepage.
