### ISSUE TITLE
Mobile: Add birthday check after a parent begins address search

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#885]
I think the functionality of this should be pretty similar to what we see in #829. After a parent searches by address, we want to ask parents to input the birth date(s) of their child(ren) to help filter the results. 

<img width="858" alt="screen shot 2017-08-18 at 4 24 51 pm" src="https://user-images.githubusercontent.com/5550969/29478300-ccfc038a-8431-11e7-9c4e-fe254b9f1591.png">

A couple of things that we should think about are:
- How many children do we want parents to be able to add?
- What should happen if a parent adds a child that is over the age of 4? For example, we do know that CPS locations also serve older children, and ideally, parents would want to try and place both children in a location but this might be too far outside of the scope of this website. If that is the case, should we tell parents that the results are only for their younger child?

**Comment by amynicole** [comment]
1. Thoughts on a maximum of 5 children added? I don't want to provide a subpar user experience to parents of quintuplets, or other multiples if they have that many children under age 4– but it seems statistically unlikely that this would exclude many families.
2. Can we give a warning message when a parent adds a child over age 4 that they will be seeng results for the younger child?

**Comment by smarziano** [comment]
@amynicole I agree, let's make it a maximum of 5 children. I think that the solution should be that a parent can add a child that is 5 or older, but on the search results page there should be a note that reads:

"All locations near you for a 2 year old child and 4 year old child.

_For information about your (older age) child and (older age) visit [this website/page]._"

We are getting similar content from our partners for the /programs page birthday checker (#829) for kids over 5, so that info could be utilized here, too.

**Comment by smarziano** [comment]
Changes that need to be made based on what is on staging:
- [ ] Check font sizes @amynicole 
- [ ] Update button size @amynicole 
- [ ] Add option to add another child
- [ ] Make

**Comment by amynicole** [comment]
Font sizes look good. I think we should use the standard height button on this page, if we can.
