### ISSUE TITLE
Design tweaks to /faq page

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#886]
Here are design tweaks to our /faq page:
- [x] Make each section divider (ex: "Finding Programs") a H1 element
- [x] Decrease the scale of the drop-down triangle to 60% 
- [x] Make sure all telephones are hyperlinked
- [x] Make sure all websites are hyperlinked

**Comment by theandrewbriggs** [comment]
I've cleaned up the hyperlinks, but as I mentioned in #875, there's references to the site itself - Those links should probably go somewhere else rather than the homepage?

**Comment by smarziano** [comment]
I agree, @theandrewbriggs, I've found two cases when the site references itself and should be updated. 

1. "I’m on a waitlist and I want to consider a different site for my child. How do I do that?
Visit ChicagoEarlyLearning.org to compare other preschool sites and consider new options..."

Change "Visit ChicagoEarlyLEarning.org to compare..." to "Use the Find and Compare tool to compare..."

2. "What is the application process? ... Visit chicagoearlylearning.org, click on the link to apply to preschool, and create an online account for your family..."

Change "Visit chicagoearylearning.org, click on the link..." to "Click on ['Apply'](https://cys.mycopa.com/familyPortal/welcome.epl), and create an online account..."

**Comment by theandrewbriggs** [comment]
This is live on production.
