### ISSUE TITLE
Add map of locations to /starred page

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#888]
We want parents to make choices of early learning programs based on the characteristics of the program, but we also understand that making a final decision on which preschool my child should go to might be affected by location. Therefore, a parent might choose 6 sites to compare, all 6 are excellent and meet my needs, but the 2 a parent might choose to apply to are based on being in an ideal location.

We think adding a map of locations on the Compare & Apply page will help parents compare locations of multiple sites and help them make a final decision of which one(s) to apply to. We also want to show the parent's location marker of the location they searched (represented as the blue marker).

<img width="585" alt="screen shot 2017-08-22 at 4 10 15 pm" src="https://user-images.githubusercontent.com/5550969/29587717-6be3c58a-8754-11e7-9944-3031fe88c314.png">

**Comment by smarziano** [comment]
@amynicole Do the colors of the map pinpoint reference the slot availability? Currently, on desktop we use green for slots available and yellow for limited availability. I think we can show that on the map if we explain it or match it in the chart. 

The other option is to use colors that are not green or gold but are within the style guide.

**Comment by amynicole** [comment]
I was just copying what I saw on the live site. I believe they should use the same logic on mobile that they do on desktop.

**Comment by smarziano** [comment]
Some tasks to complete based on what is currently on staging
- [ ] Add map of starred locations (obvious task)
- [ ] Add "Remove" option at end of row
- [ ] Fix alignment of "Scroll to View Location Details" text so it doesn't overlap with chart (see screenshot below)

![img_8240](https://user-images.githubusercontent.com/5550969/29907635-21cabc8a-8de2-11e7-82a6-6eb9b5a10b79.PNG)

**Comment by smarziano** [comment]
@theandrewbriggs I am not sure if we need the map of starred locations on the desktop version. I do not think we discussed this before, but as I was reviewing staging I was thinking how that might not be necessary. If you agree, then we can also remove the numbers next to the rows, but it also doesn't hurt to have those numbers there.
