### ISSUE TITLE
Update CPS/Community-based list icons to match map pinpoints

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#890]
This is less of an issue on the mobile designs (https://github.com/smartchicago/chicago-early-learning/issues/697#issuecomment-324335348), but on desktop the icons used in the list view for CPS-based or community-based really need to be closer to what we use on the map since we see both at the same. So across the designs, CPS-based centers should use a pencil and community-based should use the book icon. 

<img width="1269" alt="screen shot 2017-08-28 at 12 01 00 pm" src="https://user-images.githubusercontent.com/5550969/29784146-9b28ebc0-8be8-11e7-889d-f4705ef543f8.png">

**Comment by amynicole** [comment]
What do we think of these? https://www.dropbox.com/sh/al2ax5rzez7y4pl/AABGyGAPi_0mzgIsk4kUJHYea?dl=0

**Comment by smarziano** [comment]
@amynicole Adorable and much closer to what I was thinking.

**Comment by amynicole** [comment]
Great! They should match the pins more directly, too. Andrew, let me know if the color/stroke needs to be adjusted.
