### ISSUE TITLE
Staging: "Use your current location" button is not working

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#896]
The "Use your current location" button was not active and wouldn't do anything when clicking on it. @theandrewbriggs fixed that via commit https://github.com/smartchicago/chicago-early-learning/commit/69ef7791482b688855fcdb5013afc7ab4d9aaba2.

Unfortunately, that did not fix everything because now the "Use your current location" button takes you to the general /search page (#884) that asks you to enter your address.

**Comment by smarziano** [comment]
@theandrewbriggs It looks like the current location button is working, but an address is not be captured in the "Enter an address" search bar. This is confusing because it makes it seem on the age checker page that you need to still enter an address.

**Comment by theandrewbriggs** [comment]
So this is like a feature that would take some technical stuff to figure out. Capturing an address is different than capturing a Lat/Long which is what we do.

We already have some of the Google Locations stuff in place, so it shouldn't be too hard, but this isn't something that we can just cut and paste into place.

**Comment by smarziano** [comment]
As we discussed in Slack, the quicker solution should be to show "Current Location" in the address search box so parents know they do not have to enter an address again and that we have considered their address in the search results.
