### ISSUE TITLE
Mobile: Add note if parents check the birthdate for children who are 5 years or older

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#899]
This is a continuation of work started in issue #885.

I think that the solution should be that a parent can add a child that is 5 or older, but on the search results page there should be a note that reads:

"All locations near you for a 2 year old child and 4 year old child.

For information about your (older age) child and (older age) visit [this website/page]."

**Comment by theandrewbriggs** [comment]
I've added this capability in on my end, but I need final copy. There will not be support for multiple children, so the copy will read something to the effect of:

> For information for your 6 year old, visit CPS.edu.
> All locations near you that offer full day, etc..
