### ISSUE TITLE
Remove Summer Family Resource Centers on 9/29

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#912]
This relates to issue #911. Since we are moving into the Fall months, the libraries will no longer act as Family Resource Centers. Therefore, there are a couple of content edits that need to be made, and all Family Resource Centers except for Colman should be removed. The map image for Colman should also be added (#851).

When we move into phase 3 of our work, we should think of utilizing the admin tool to turn on/off Family Resource Centers to show up on this page. 

-------
"...staff at Family Resource Centers will also verify income and employment documentation."

**needs to be changed to**

"...staff at Family Resource Centers will also verify income, employment, and birth record documentation."

_Spanish translation of new content:_
el personal en los Centros de Recursos para la Familia también verifica la documentación sobre el ingreso económico, el empleo, y el nacimiento.

--------
All visitors to Family Resource Centers will have access to internet and computers. If a family would like to use a library computer, the user must have a library card. Anyone with a valid ID with name, photo and Chicago address can sign up for a library card on site.

**needs to be changed to**

At least one Family Resource Center is available year-round for families verifying their documentation. For the 2017 - 2018 school year, Colman, 4655 S. Dearborn St., is open from 9AM - 5PM, Monday - Friday. "

In the summer months, about a dozen Chicago Public Libraries across the city serve as Family Resource Centers. All summer visitors will have access to internet and computers. If a family would like to use a library computer, the user must have a library card. Anyone with a valid ID with name, photo and Chicago address can sign up for a library card on site.

_Spanish translations needed, keep current text_

------

**Comment by theandrewbriggs** [comment]
This is live on production.

**Comment by smarziano** [comment]
Work still needs to be completed via #851. Closing this issue.
