### ISSUE TITLE
Spanish: Copyright line translation

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#918]
COPYRIGHT ©2017 CHICAGO EARLY LEARNING / BUILT BY SMART CHICAGO COLLABORATIVE

_**translates to**_

DERECHOS DE AUTOR ©2017 CHICAGO EARLY LEARNING / CONSTRUIDO POR SMART CHICAGO COLLABORATIVE

**Comment by theandrewbriggs** [comment]
This is live on production.
